- modules/EnsEMBL/Draw/GlyphSet/genetree.pm
- modules/EnsEMBL/Web/Component/Compara_Alignments.pm
- modules/EnsEMBL/Web/Object.pm
same as #154, but on postreleasefix/78
> Genomic align tree

- modules/EnsEMBL/Web/Factory/Feature.pm
get_species_and_object_type is an expensive call, especially for sites with many species
> Don't do stable id check until it is needed

- conf/ini-files/DEFAULTS.ini
- modules/EnsEMBL/Web/Component/Variation/IndividualGenotypes.pm
- modules/EnsEMBL/Web/Object/Variation.pm
This update removes the "i" icons in the tables, like we did for the "Population genetics" tables.
> Individual genotypes updates

- modules/EnsEMBL/Web/Document/HTML/Compara.pm
- modules/EnsEMBL/Web/Document/HTML/Compara/BlastZ.pm
- modules/EnsEMBL/Web/Document/HTML/Compara/MLSS.pm
* A few modifications in the page with the pairwise-alignments stats:
http://www.ensembl.org/info/genome/compara/mlss.html?mlss=713
http://enssand-01.internal.sanger.ac.uk:9073/info/genome/compara/mlss.html?mlss=713
*  New page: statistics for syntenies
http://enssand-01.internal.sanger.ac.uk:9073/info/genome/compara/mlss.html?mlss=10101
> Synteny stats

- conf/SiteDefs.pm
Pull request for the correct file :)
> Updated for e79.

- conf/ini-files/DEFAULTS.ini
And merge a couple of new links from the 'master' branch
> Update the rat RGD link

- conf/ini-files/DEFAULTS.ini
- modules/EnsEMBL/Web/Component/Gene/GenePhenotypeVariation.pm
- modules/EnsEMBL/Web/Component/Variation/Phenotype.pm
- modules/EnsEMBL/Web/Data/Bio/Variation.pm
- Mainly minor refactoring code
- Change the pubmed links to EPMC links
- Change the NHGRI link
> Phenotype pages updates 

- modules/EnsEMBL/Web/Component/StructuralVariation/Summary.pm
> Use EMPC instead of PubMed + update the 'Study' link

- modules/EnsEMBL/Web/Component/Location/SequenceAlignment.pm
The code expects yes/no rather than on/off
We've got two tickets regarding this that came from Ensembl #467028, Ensembl #467306 and Ensembl #466232
> ensembl-3875 Problem showing "Resequencing alignements

- modules/EnsEMBL/Draw/GlyphSet/snp_fake_haplotype.pm
- modules/EnsEMBL/Web/Component/Location/LD.pm
- modules/EnsEMBL/Web/Component/Location/SequenceAlignment.pm
- modules/EnsEMBL/Web/Component/Variation/Explore.pm
- modules/EnsEMBL/Web/Component/Variation/PopulationGenotypes.pm
- modules/EnsEMBL/Web/Component/Variation/SampleGenotypes.pm
- modules/EnsEMBL/Web/Component/Variation/SampleGenotypesSearch.pm
- modules/EnsEMBL/Web/Component/Variation/Summary.pm
- modules/EnsEMBL/Web/Configuration/Variation.pm
- modules/EnsEMBL/Web/Object/Location.pm
- modules/EnsEMBL/Web/Object/Slice.pm
- modules/EnsEMBL/Web/Object/Transcript.pm
- modules/EnsEMBL/Web/Object/Variation.pm
The first big batch of updates for the webcode to work with the new variation sample schema for 81. I updated the code and tested the changes against a patched human and mouse database.
> At7/feature 81/new sample schema

- modules/EnsEMBL/Web/Component/Variation/Explore.pm
- modules/EnsEMBL/Web/Component/Variation/Summary.pm
- modules/EnsEMBL/Web/Configuration/Variation.pm
- modules/EnsEMBL/Web/Object/Variation.pm
Separated out transcript and regfeat counting code, with a
summed "features" count that is used to check availability
and to put the number on the icon on the Explore component
> Update variation counts code

- modules/EnsEMBL/Web/Component/Variation/HighLD.pm
Use the correct array for counting the number of variants.
> At7/feature 81/ld bug

- modules/EnsEMBL/Draw/GlyphSet/tsv_missing.pm
- modules/EnsEMBL/Web/Component/Gene/GenePhenotypeVariation.pm
- modules/EnsEMBL/Web/Component/Gene/GeneSummary.pm
- modules/EnsEMBL/Web/Component/LRG/LRGPhenotypeVariation.pm
- modules/EnsEMBL/Web/Component/LocalGenes.pm
- modules/EnsEMBL/Web/Component/Transcript/PopulationImage.pm
- modules/EnsEMBL/Web/Component/Transcript/PopulationTable.pm
- modules/EnsEMBL/Web/Component/UserData/UploadVariations.pm
- modules/EnsEMBL/Web/Component/Variation/HighLD.pm
- modules/EnsEMBL/Web/Component/Variation/Mappings.pm
- modules/EnsEMBL/Web/Component/Variation/Phenotype.pm
- modules/EnsEMBL/Web/Component/VariationImage.pm
- modules/EnsEMBL/Web/Component/VariationTable.pm
- modules/EnsEMBL/Web/Constants.pm
- modules/EnsEMBL/Web/ImageConfig.pm
- modules/EnsEMBL/Web/ViewConfig/TextSequence.pm
- modules/EnsEMBL/Web/ViewConfig/Variation/FlankingSequence.pm
- modules/EnsEMBL/Web/ViewConfig/Variation/HighLD.pm
I'll stop now for a while! Hope these are ok.
> Changed variation to variant

- modules/EnsEMBL/Web/Component/Variation/HighLD.pm
- modules/EnsEMBL/Web/Configuration/Variation.pm
More variation variant replacing.
> not urgent!

- conf/ini-files/DEFAULTS.ini
http://rgd.mcw.edu/rgdweb/report/gene/main.html?id=2465
works
http://rgd.mcw.edu/rgdweb/report/reference/main.html?id=2465
does not any more
> RGD reference link changed

- modules/EnsEMBL/Web/Component/Transcript/TranscriptSummary.pm
As discussed with Harpreet, helptip is now added to trans-spliced transcript row.
Thanks, 
Sanjay
> ENSEMBL-4008 - Helptip added to trans-spliced transcript row

- modules/EnsEMBL/Web/ImageConfig.pm
- modules/EnsEMBL/Web/ViewConfig.pm
Prints trackhub's long label only if it exists.
Thanks,
Sanjay
> ENSEMBL-4053 - making possible for hyperlink display in the trackhub labels - Implemented

- modules/EnsEMBL/Web/Component/Gene/GenePhenotypeVariation.pm
- Update the 'phenotype' label to include the 'disease' and 'trait' terms
- Remove COSMIC phenotype
- Use the prefix 'PMID' instead of 'pubmed' for the external references
> Several updates on the Gene Phenotype Variation table

- conf/SiteDefs.pm
Reverts Ensembl/ensembl-webcode#289 
Will accept this later when databases are ready on dev.
> Revert "Updated for release 82"

- modules/EnsEMBL/Web/Document/HTML/Compara.pm
Some fixes to use recent additions to the Compara API / data-model
> Compara misc 82

- modules/EnsEMBL/Web/Component/Variation/Phenotype.pm
Please, could you push it to the branch release/82 as well ?
Thanks.
> Update Clinical significance review status

- modules/EnsEMBL/Web/Component/Variation/SampleGenotypes.pm
Please, could you push it to the branch "release/82" as well ?
Thanks!
> Only shorten the population names for 1000Genomes and HapMap

- modules/EnsEMBL/Web/ZMenu/TextSequence.pm
Please, could you push it to the branch "release/82" as well ?
Thanks
> Display consequence colour for 3 prime UTR and 5 prime UTR

- modules/EnsEMBL/Draw/GlyphSet/lrg_band.pm
- modules/EnsEMBL/Web/Component/LRG/Summary.pm
- modules/EnsEMBL/Web/Component/LRG/TranscriptsImage.pm
- modules/EnsEMBL/Web/ImageConfig/contigviewbottom.pm
- modules/EnsEMBL/Web/ImageConfig/lrg_summary.pm
Please, could you push this changes to the branch "release/82" as well ?
> LRG fixes and updates

- modules/EnsEMBL/Web/Component/LD.pm
- modules/EnsEMBL/Web/Component/PopulationSelector.pm
- modules/EnsEMBL/Web/Component/Variation/HighLD.pm
- modules/EnsEMBL/Web/Component/Variation/LD.pm
- modules/EnsEMBL/Web/Component/Variation/LDPlot.pm
- modules/EnsEMBL/Web/Component/Variation/SelectPopulation.pm
- modules/EnsEMBL/Web/Configuration/Variation.pm
- modules/EnsEMBL/Web/ImageConfig/ldmanplot.pm
- modules/EnsEMBL/Web/ViewConfig/Variation/LDPlot.pm
- modules/EnsEMBL/Web/ZMenu/Variation.pm
The content of the modules Component::Location::SelectPopulation and Component::Location::LD have been moved in the Component directory, because the code of these 2 modules is also used in the new LD Plot view (under Component::Variation)
> Several commits to add the new LD Plot view for Variation

- modules/EnsEMBL/Web/Component/Transcript/PopulationTable.pm
- modules/EnsEMBL/Web/Component/Variation/Summary.pm
- modules/EnsEMBL/Web/Object/Slice.pm
- modules/EnsEMBL/Web/Object/Variation.pm
We deprecate the validation_status data for the variants this release, so the webcode need few updates
There are other minor display changes with these commits.
> Remove the deprecated call to validation_status

- modules/EnsEMBL/Web/Component/Variation/PopulationGraphs.pm
Please, could you push the fix on release/82 as well ?
Thanks
> Fix display issue with the truncated alleles

- modules/EnsEMBL/Draw/Style/Plot/LD.pm
This has been requested by few people
> Change the display of the threshold horinzontal line

- modules/EnsEMBL/Web/Component/DataExport/GeneTree.pm
- modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm
- modules/EnsEMBL/Web/ViewConfig/Gene/ComparaTree.pm
Reverts Ensembl/ensembl-webcode#361, because we need to merge these commits into the release branch first
> Revert "Allow export of genetrees in pan-compara db"

- modules/EnsEMBL/Web/Object/Go.pm
> FamilyAdaptor::fetch_by_Member_source_stable_id() is deprecated

- htdocs/components/90_variation_table.css
- modules/EnsEMBL/Web/Component/Shared.pm
- modules/EnsEMBL/Web/Component/StructuralVariation/Mappings.pm
- modules/EnsEMBL/Web/Component/Variation/Mappings.pm
The feature coverage glyph has been updated in the "Genes and regulation" page for StructuralVariation and has been added for the "Genes and regulation" page as well in Variation.
> Add coverage glyphs in Variation and update it in StructuralVariation

- modules/EnsEMBL/Web/Component/Transcript/PopulationImage.pm
- modules/EnsEMBL/Web/Component/Transcript/PopulationTable.pm
- modules/EnsEMBL/Web/Object/Transcript.pm
Some small changes. Replace deprecated core methods with calls in the variation API. Population comparison and table are still working on my sandbox after the changes.
> 84 feature/strain slice

- modules/EnsEMBL/Draw/GlyphSet/ld.pm
- modules/EnsEMBL/Web/Object/Location.pm
Needs updated ensembl-variation (release/84) too
> update LD code to use new var API methods

- modules/EnsEMBL/Draw/GlyphSet/bigbed.pm
- modules/EnsEMBL/Draw/GlyphSet/flat_file.pm
- modules/EnsEMBL/Draw/GlyphSet/vcf.pm
- modules/EnsEMBL/Draw/Role/Bam.pm
- modules/EnsEMBL/Web/IOWrapper.pm
- modules/EnsEMBL/Web/IOWrapper/Bed.pm
- modules/EnsEMBL/Web/IOWrapper/BigBed.pm
- modules/EnsEMBL/Web/IOWrapper/BigWig.pm
Only active if USE_SEQREGION_SYNONYMS is set in species configs or DEFAULTS.ini
> Add support for seq region synonyms in userdata file formats

- htdocs/components/05_DataTable.js
- modules/EnsEMBL/Web/Component.pm
- modules/EnsEMBL/Web/Component/Variation/SampleGenotypes.pm
- modules/EnsEMBL/Web/Document/HTML/Compara/GeneTrees.pm
New class `no-export` to handle table column or data exports
If this class is present in the table heading like `<th class="no-export">`, then that column will be completely ignored while exporting.
> Fix #ENSWEB-2243 - New class "no-export" to handle exports

- conf/ini-files/DEFAULTS.ini
The old PFAM link is no longer in operation, updated with new URL.
Please could this change go to branch and master and be pushed live.
> Update PFAM external link template

- modules/EnsEMBL/Draw/GlyphSet/vcf.pm
Remove +1 as both positions are already 1-based
> ENSEMBL-4473 fix off-by-one VCF feature bug

- modules/EnsEMBL/Web/Component/Regulation/CellTypeSelector.pm
- modules/EnsEMBL/Web/Component/Regulation/Summary.pm
- modules/EnsEMBL/Web/ConfigPacker.pm
- modules/EnsEMBL/Web/Object/Regulation.pm
Updates from @juettemann and @mn1 for release 85
> Updates from @juettemann and @mn1 for release 85

- modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm
Modified so that this new sub can be overridden from plugins to generate their own links
> Code Optimization

- modules/EnsEMBL/Web/Component/Gene/GenePhenotype.pm
I also updated the ini file for mouse with the new url for MGI phenotype data
> Add source link for phenotypes from MGI

- conf/ini-files/DEFAULTS.ini
- modules/EnsEMBL/Web/Component/Phenotype.pm
- modules/EnsEMBL/Web/Component/Phenotype/OntologyTerm.pm
- modules/EnsEMBL/Web/Configuration/Phenotype.pm
- modules/EnsEMBL/Web/Object/Phenotype.pm
This adds a table of mapping ontology terms to the locations page. It is written to be extended for e!86
> add ontology term tab 

- modules/EnsEMBL/Web/Object/Variation.pm
Use correct way to iterate over and access elements in an array of hashes.
> Fix a bug introduced in change 2230a35.

- modules/EnsEMBL/Web/Component/Gene/GenePhenotype.pm
- modules/EnsEMBL/Web/Component/Gene/GenePhenotypeVariation.pm
Paul K. is quite keen to make the messages consistent.
Fix ENSEMBL-4535.
> Reword messages in gene phenotype page.

- modules/EnsEMBL/Web/Document/HTML/Compara/GeneTrees.pm
Can this be on the live site and master branch too 
Thanks
> fixed some ncRna piecharts and some asthetics on the pages

- modules/EnsEMBL/Web/Object/Export.pm
Fix ENSWEB-2791 and ENSEMBL-4593.
> fix(Export): check variation db exists before accessing it

- modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm
- modules/EnsEMBL/Web/ViewConfig/Gene/ComparaTree.pm
> Use correct db for pan_compara gene tree.

- modules/EnsEMBL/Web/Component/Compara_Alignments.pm
- modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm
- modules/EnsEMBL/Web/Component/Variation_Context.pm
- modules/EnsEMBL/Web/Document/HTML/Compara.pm
- modules/EnsEMBL/Web/Document/HTML/Compara/MLSS.pm
- Updated calls to a deprecated Compara method
- Fixed http://test.ensembl.org/info/genome/compara/analyses.html by adding in the mappings web name <-> production name
- Added a simple page to list the species in the HAL file
I have pushed other changes to public-plugins. You'll have to rebuild web_tree because I've renamed a page
> Compara misc

- modules/EnsEMBL/Web/Document/HTML/Compara/GeneTrees.pm
- modules/EnsEMBL/Web/Hub.pm
I addressed several comments from Paul K. and fixed http://www.ensembl.org/info/genome/compara/prot_tree_stats.html?page=coverage
All tested on my sandbox http://enssand-02.internal.sanger.ac.uk:9073/info/genome/compara/prot_tree_stats.html
> Gene-tree stats

- modules/EnsEMBL/Web/ZMenu/UserData.pm
Requested by @ens-gmaslen for VectorBase
> Mark up URL links provided in BigBed extra data

- modules/EnsEMBL/Web/Component/Gene/HomologAlignment.pm
> Fetch homoeologues for homoeologue alignments view

- modules/EnsEMBL/Web/Component/Transcript/Haplotypes.pm
If you merge this in you can close this one https://github.com/Ensembl/ensembl-webcode/pull/464
Will need applying to release/87 too.
> redo of PR from Will Spooner

- modules/EnsEMBL/Web/Document/HTML/Compara.pm
- modules/EnsEMBL/Web/Document/HTML/Compara/BlastZ.pm
- modules/EnsEMBL/Web/Document/HTML/Compara/GeneTrees.pm
Two bugfixes:
- ENSCOMPARASW-873. Matthieu Barba complained that the colour of our piecharts were not legible
- ENSWEB-3397
All tested on my sandbox
http://enssand-02.internal.sanger.ac.uk:9073/info/genome/compara/analyses.html
vs
http://test.ensembl.org/info/genome/compara/analyses.html
and
http://enssand-02.internal.sanger.ac.uk:9073/info/genome/compara/prot_tree_stats.html
vs
http://test.ensembl.org/info/genome/compara/prot_tree_stats.html
Matthieu
> Matthieu misc compara

- modules/EnsEMBL/Web/ZMenu/StructuralVariation.pm
Can't assume $vstatus is an array
> Check datatype of validation status

- conf/ini-files/DEFAULTS.ini
- modules/EnsEMBL/Web/Component/Gene/FamilyGenes.pm
- modules/EnsEMBL/Web/Component/Gene/FamilyProteins.pm
- between pages
- link out to the source Panther and Hamap databases
Tested on my sandbox
http://enssand-02.internal.sanger.ac.uk:9073/Homo_sapiens/Gene/Family/Genes?cdb=compara;db=core;family=PTHR11289_SF0;g=ENSG00000139618;r=13:32315474-32400266 vs http://www.ensembl.org/Homo_sapiens/Gene/Family/Genes?cdb=compara;db=core;family=PTHR11289_SF0;g=ENSG00000139618;r=13:32315474-32400266
http://enssand-02.internal.sanger.ac.uk:9073/Multi/Family/Details?fm=PTHR11289_SF0 vs http://www.ensembl.org/Multi/Family/Details?fm=PTHR11289_SF0
> Added more hyperlinks for the Compara families

- modules/EnsEMBL/Draw/GlyphSet/V_density.pm
Simple fix for papercut bug (tested on local instance).
> ENSWEB-2241: fix GC graph drop at end of chromosomes

- modules/EnsEMBL/Draw/GlyphSet/TSE_transcript.pm
- modules/EnsEMBL/Draw/GlyphSet/tsv_transcript.pm
Instead of EnsEMBL::Web::Object::Gene ...
Fixes ENSEMBL-4805.
> Use Bio::EnsEMBL::Gene object to get colour key

- modules/EnsEMBL/Web/Component/Shared.pm
- modules/EnsEMBL/Web/Component/Variation_Context.pm
> Replace empty table with single line text

- modules/EnsEMBL/Web/TextSequence/Markup/LineNumbers.pm
- modules/EnsEMBL/Web/TextSequence/Markup/Variations.pm
- modules/EnsEMBL/Web/TextSequence/View.pm
Two main things here:
1. remove some of the warns
2. reduce the number of undefined errors written to the logs
> Reduce warnings in error logs

- modules/EnsEMBL/Web/Component/Variation/PairwiseLD.pm
Filter out variants from ALT LOCI
> Exclude non-reference variants

- modules/EnsEMBL/Web/Factory/Feature.pm
@juettemann found this error:
```
http://staging.ensembl.org/Caenorhabditis_elegans/Location/Genome?fdb=funcgen;ftype=ProbeFeature;id=CE_WBGene00016000_A
Can't locate object method "primary_id" via package "Bio::EnsEMBL::Funcgen::ProbeTranscriptMapping" at
... /nfs/public/release/ensweb/staging/www/ensembl-webcode/modules/EnsEMBL/Web/Factory/Feature.pm line 201.
```
This should fix it.
> New funcgen api calls

- htdocs/components/15_TranscriptHaplotypes.js
Replacing Homo_sapiens by Ensembl.species to make it more general
> Replace Homo_sapiens by Ensembl.species

- modules/EnsEMBL/Web/Controller/Json.pm
- modules/EnsEMBL/Web/Hub.pm
Previously only the default POST_MAX was being set and tools POST_MAX was being ignored
> Fix to ensure that upload limits are set correctly

- modules/EnsEMBL/Web/Object/Experiment.pm
Hopefully this should fix this issue https://www.ebi.ac.uk/panda/jira/browse/ENSREGULATION-774
Please use the latest master branch from funcgen's repository.
> fix for ENSREGULATION-774 jira issue

- modules/EnsEMBL/Web/Component.pm
- modules/EnsEMBL/Web/Component/Variation/PopulationGenotypes.pm
- modules/EnsEMBL/Web/Object/Variation.pm
Example: http://ves-hx2-76.ebi.ac.uk:8799/Homo_sapiens/Variation/Population?v=rs699
> Add frequency bar plot to population genotypes page

- modules/EnsEMBL/Web/Component/SVTable.pm
- modules/EnsEMBL/Web/Component/Variation_Context.pm
Fixing issues reported on ENSWEB-4007
> Minor fix for the variant and structural variant context pages

- htdocs/das/das.xsl
- modules/EnsEMBL/Web/Document/Element/Copyright.pm
Issue originally raised in ENSWEB-4136. We should get this out before 90 if possible
> Remove WTSI references

- conf/ini-files/DEFAULTS.ini
- modules/EnsEMBL/Web/Component/Variation/Summary.pm
For e!91 - create links to a new resource from the variant summary.
> Add links to PharmGKB from variant synonym

- conf/preload_modules.txt
- modules/EnsEMBL/Draw/GlyphSet/fg_multi_wiggle.pm
- modules/EnsEMBL/Draw/GlyphSet/fg_regulatory_features.pm
- modules/EnsEMBL/Web/Component/Regulation/Evidence.pm
- modules/EnsEMBL/Web/ConfigPacker.pm
- modules/EnsEMBL/Web/DBSQL/DBConnection.pm
- modules/EnsEMBL/Web/Object/Slice.pm
- modules/EnsEMBL/Web/ZMenu/FeatureEvidence.pm
- modules/EnsEMBL/Web/ZMenu/Methylation.pm
These should make the webcode work with the new regulation api on master as soon as this pull request:
https://github.com/Ensembl/ensembl/pull/216
has been merged into Ensembl core.
> Updates to make the webcode work with the new regulation api

- modules/EnsEMBL/Web/Document/HTML/ToolsTable.pm
Add row for LD tool to tools [table](http://www.ensembl.org/info/docs/tools/index.html)
> Add row for LD tool

- modules/EnsEMBL/Web/Component/StructuralVariation/PopulationFrequency.pm
If possible we would like to push this fix to master as well
> Fix minor issue with empty object

- modules/EnsEMBL/Web/Component/UserData/TrackHubSearch.pm
typo in calling `$sd->TRACKHUB_REGISTRY_URL`
> ENSEMBL-5092 Fix wrong link

- modules/EnsEMBL/Web/Document/HTML/Compara/MLSS.pm
> MethodLinkSpeciesSet::species_set_obj is deprecated

- modules/EnsEMBL/Draw/GlyphSet/genetree.pm
- modules/EnsEMBL/Web/Document/HTML/Compara.pm
- modules/EnsEMBL/Web/Document/HTML/Compara/MLSS.pm
All tested on my sandbox
1. Table of multiple alignments
Static version on [staging](http://staging.ensembl.org/info/genome/compara/multiple_genome_alignments.html) vs dynamic version on my [sandbox](http://ves-hx2-76.ebi.ac.uk:5080/info/genome/compara/multiple_genome_alignments.html)
2. Consensus cigar-lines
I actually feel like it's made my sandbox faster than the live site !
- BRCA2: [www](http://www.ensembl.org/Homo_sapiens/Gene/Compara_Tree?collapse=19779259%2C19779227%2C19779254%2C19779205%2C19779209%2C19779240%2C19779191%2C19779283%2C19779437%2C19779386%2C19779214%2C19779188;db=core;g=ENSG00000139618;gtr=order;r=13:32315474-32400266) vs [sandbox](http://ves-hx2-76.ebi.ac.uk:5080/Homo_sapiens/Gene/Compara_Tree?collapse=19779214%2C19779240%2C19779283%2C19779209%2C19779437%2C19779386%2 …
> Misc. updates for Compara

- modules/EnsEMBL/Web/ZMenu/Transcript.pm
This pull request is for ENSWEB-4218. The sandbox link is: http://ves-hx-78.ebi.ac.uk:8310/Homo_sapiens/Location/View?r=17%3A63992802-64038237.
> Fix for broken Genscan transcript links in zebrafish

- modules/EnsEMBL/Web/Component/Gene/GenePhenotypeVariation.pm
- modules/EnsEMBL/Web/Component/LRG/LRGPhenotypeVariation.pm
- modules/EnsEMBL/Web/Component/Phenotype/Locations.pm
- modules/EnsEMBL/Web/Component/Shared.pm
- modules/EnsEMBL/Web/Component/Variation/Phenotype.pm
- Distinct source entry for each submission
- List of PubMed IDs as evidence
> Display extra information from ClinVar in the phenotype-related pages

- modules/EnsEMBL/Web/Component/Shared.pm
- modules/EnsEMBL/Web/Component/Transcript/ProteinVariations.pm
- modules/EnsEMBL/Web/Component/VariationTable.pm
I updated the colour for one of the predictors from blue to green if the score is interpreted as neutral.
> show a neutral prediction as good (=green) and not neutral (=blue)

- modules/EnsEMBL/Web/Controller/Psychic.pm
- There are about 1 billion HGVS identifiers in human 38. If we can get Psychic to intercept queries for them we can save a lot of resources and hopefully make Solr search more reliable
_Add HGVS Parsing to Psychic_
_Search_
_Not any_
_Not any_
_https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-4802_
> Add HGVS parsing to Psychic (ENSWEB-4802)

- modules/EnsEMBL/Web/Component/Variation/Summary.pm
Update help tip string for MAF to reflect how it's calculated.
The variant summary page will display the new help tip.
_We …
> update help tip maf

- conf/ini-files/DEFAULTS.ini
Update link to the new dbSNP variant page
Variation views
> Update dbSNP link to point to a new page on the NCBI website

- htdocs/newtable/00_jquery_newtable_filter.js
**NOTE:** This needs to released along with the following PR:
https://github.com/Ensembl/public-plugins/pull/238
Fixed the issue with tracking the `Filter Other Columns` button on the variation table.
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5228
> Fix Filter Other Columns tracking on variation table

- modules/EnsEMBL/Web/Document/HTML/Compara.pm
- modules/EnsEMBL/Web/Document/HTML/Compara/MLSS.pm
> Removed extra word

- conf/ini-files/DEFAULTS.ini
Update link out to COSMIC using the new COSMIC identifiers.
The variation summary page 'View in COSMIC' link.
Sandbox …
> update cosmic link out -e99

- modules/EnsEMBL/Web/ZMenu/Transcript/CLS.pm
Add exon count to long reads zmenu. Link to sandbox is: http://ves-hx-78.ebi.ac.uk:8320/Homo_sapiens/Location/View?db=core;g=ENSG00000139618;r=13:32016955-32698402
Long reads zmenu
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5331
> Add exon count to long reads zmenu

- conf/SiteDefs.pm
Updating release dates from December 2019 to January 2020 in SiteDefs config.
> Update release date to January 2020

- htdocs/components/99_announcement_banner.css
- modules/EnsEMBL/Web/Document/Element/TmpMessage.pm
- modules/EnsEMBL/Web/Template/Legacy.pm
> Add option to display announcement banner (#753)

- conf/ini-files/DEFAULTS.ini
Variation summary section contains variation synonyms and link out to the original source. The ClinVar synonym link out is broken. This PR is to fix it.
Variation summary section and all views that contain it.
None expected.
None.
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3193
> fix clinvar url - ENSVAR-3193 -e100

- conf/ini-files/COLOUR.ini
Related JIRA:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEBREL-745
> Missing transcript colours for 101

- conf/ini-files/DEFAULTS.ini
Add Mastermind external URL to be used in web VEP e103.  
None
None
None
> Add Mastermind URL

- modules/EnsEMBL/Web/Document/HTML/ToolsTable.pm
We are going to add a web interface for Variant Recoder (https://github.com/Ensembl/public-plugins/pull/410).
This PR updates the tools table with the new Variant Recoder info. 
Update table: https://www.ensembl.org/info/docs/tools/index.html 
Sandbox: http://ves-hx2-76.ebi.ac.uk:7040/info/docs/tools/index.html 
None
No conflicts
ENSVAR-2598
> Update tools table - add Variant Recoder

- modules/EnsEMBL/Web/Query/GlyphSet/Transcript.pm
- Fixed the issue where the Gencode basic track was not getting displayed
- The solution was the append the species name to the logic names as pointed out by Mag [here](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6132?focusedCommentId=349340&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-349340)
http://ves-hx2-75.ebi.ac.uk:42229/Homo_sapiens/Location/View?align=677;db=core;g=ENSG00000198826;r=15:32615144-32639941
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6132
> Fix GENCODE basic track

- modules/EnsEMBL/Web/Query/GlyphSet/Transcript.pm
Reverts Ensembl/ensembl-webcode#810
> Revert "Fix GENCODE basic track"

- modules/EnsEMBL/Web/Query/GlyphSet/Transcript.pm
http://ves-hx2-75.ebi.ac.uk:42229/Homo_sapiens/Location/View?db=core;g=ENSG00000139618;r=13:32315086-32400268
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6132
> Fix GENCODE basic track  - V2

- modules/EnsEMBL/Web/ImageConfigExtension/Tracks.pm
- modules/EnsEMBL/Web/ZMenu/Variation.pm
Mastermind was added to the variation private database. Some code needs to be updated to display the new track. 
There is a new track in the Variation track page. 
Sandbox: http://ves-hx2-76.ebi.ac.uk:7040/Homo_sapiens/Location/View?r=17%3A63992802-64038237 
None
No conflicts
ENSVAR-3907
> Add Mastermind track (e104) 

- htdocs/components/02_LayoutManager.js
Added the EBI survey banner.
http://ves-hx2-75.ebi.ac.uk:42229/index.html
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6192
> Add search survey

- htdocs/components/20_Configurator.js
- htdocs/components/25_ConfigRegMatrixForm.js
- htdocs/components/25_ConfigTrackHubMatrixForm.js
- modules/EnsEMBL/Web/Configuration.pm
- modules/EnsEMBL/Web/ImageConfig.pm
- modules/EnsEMBL/Web/ImageConfig/MultiSpecies.pm
This PR fixes the bug that is described in the related ticket.
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6001
TODO:
Need to cherry-pick this fix up until e100
http://ves-hx2-75.ebi.ac.uk:42226/Homo_sapiens/Location/Compara_Alignments/Image?align=677&db=core&g=ENSG00000198826&r=15%3A32615144-32639941
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6001
> Fix multispecies renderer reset issue

- htdocs/components/20_ComparaOrtholog.js
- modules/EnsEMBL/Web/Component/DataExport.pm
- modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm
- modules/EnsEMBL/Web/Object/Gene.pm
- Added the functionality to filter the orthologues downloads based on the filters applied on the table
http://ves-hx2-75.ebi.ac.uk:42229/Mus_musculus/Gene/Compara_Ortholog?g=ENSMUSG00000017167;r=11:101170523-101190724
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6112
> Apply orthologues species filters

- htdocs/info/website/upload/sample_files/Pulmonary_function.vcf.txt
_Update document to replace ftp to http in a 1000g url._
_GRCH37 & ensembl.org
_
_
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6221
> Update 1000g ftp url to use http.

- modules/EnsEMBL/Web/Command/UserData/TrackHubRedirect.pm
- modules/EnsEMBL/Web/Query/Generic/GlyphSet.pm
Some alignsliceslices could not be serialized/deserialized successfully in some circumstances owing to representing truncated regions not directly present in the alignsliceslices within the alignslice itself. There is no good way to serialise alignsliceslices, this is something that was confirmed with compara at first implementation. An alignsliceslice resembles a slice (from the core API) but is not a fully featured slice. However it can be used in its place in most circumstances, supported by perl's loose typesystem. To this end, all the properties of the alignsliceslice _apart from_ the start and end co-ordinates are stored in a similarly fake coordsystem (referenced from the slice), species into species, etc, but those without a natural home go into "version". If we can't find an …
> Bug fix/ensweb 6115

- modules/EnsEMBL/Web/Object.pm
This PR fixes the image export issue on the EG sites described in the linked ticket.
- Unable to get plants sandbox to work properly.
- I have tried this fix on that staging site.
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6339
> Fix EG image export issue

- modules/EnsEMBL/Web/Component/Location/SyntenyImage.pm
This PR disables the synteny view image for cases where all of the synteny regions in the target species map to contigs. This addresses the cases where there are no chromosome pairs to draw, even when the target species has chromosome(s) defined.
Synteny image in Location view.
* [Sandbox with disabled synteny view](http://wp-np2-1d.ebi.ac.uk:1680/Apis_mellifera/Location/Synteny?otherspecies=Solenopsis_invicta&r=CM009931.2%3A9468-116509)
* [Sandbox with enabled synteny view](http://wp-np2-1d.ebi.ac.uk:1680/Apis_mellifera/Location/Synteny?db=core&r=CM009931.2%3A9468-116509&otherspecies=Bombus_terrestris)
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6159
> Disable synteny view for contigs

- utils/solr_replication.sh
Updates the dictionary generation command (part of SOLR replication pipeline) to use the correct option for grch37 VMs.
> Fix dict generation command for grch37

- utils/solr_replication.sh
Updated commands for post-release SOLR replication on www machines.
> Updated commands for post-release

- htdocs/info/data/ftp/rsync.html
Minor, add an example of using rsync for EG sites
http://wp-np2-1d.ebi.ac.uk:8096/info/data/ftp/rsync.html
Not tested on a NV sandbox, but there's only one rsync.html so content will be identical with V
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6412
> added an example for using rsync with EG FTP site

- modules/EnsEMBL/Web/ZMenu/Transcript.pm
Added MANE Select / Clinical Plus information to transcript zmenus
http://wp-np2-1d.ebi.ac.uk:42229/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000053747;r=18:23689453-23956222;t=ENST00000313654
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6347
> Add Mane select / clinical plus info to transcript zmenu

- conf/ini-files/DEFAULTS.ini
Adding the url pattern for links to the Alphafold site.
Relates to PR https://github.com/Ensembl/public-plugins/pull/555. To be included in release 107.
> Add Alphafold url pattern to DEFAULTS.ini

- conf/ini-files/DEFAULTS.ini
- modules/EnsEMBL/Web/ZMenu/Variation.pm
[ENSVAR-4675](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4675)
> Changing decipher links

- conf/ini-files/COLOUR.ini
Added color code for CSHL non-protein coding genes.
_We appreciate this can be difficult but please highlight any views that you think might possibly be adversely affected by this change. For example a change to method in …
> Added CSHL non-coding protein color

- modules/EnsEMBL/Web/Document/HTML/ConsequenceTable.pm
Update ConsequenceTable.pm with consequences available in Ensembl/public-plugins#652 (and from previous releases). Also, reverted impact of one consequence based on Ensembl/public-plugins#653.
[ENSVAR-4796](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4796)
> Update ConsequenceTable.pm (e110)

- modules/EnsEMBL/Web/JSONServer/RegulationData.pm
The previous PR (https://github.com/Ensembl/ensembl-webcode/pull/960) placed the code that adds epigenomic activity and segmentation features entities for the regulation matrix inside of an inner loop, which resulted in duplicate entries. See on staging (https://staging.ensembl.org/Json/RegulationData/data?species=Homo_sapiens, search for `segmentation_features`), where the response contains 1432 `segmentation_features` entries
This PR moves the code responsible for adding these entries into an outer loop.
See sandbox: http://wp-np2-1e.ebi.ac.uk:8410/Json/RegulationData/data?species=Homo_sapiens
The number of `segmentation_features` entries dropped to 120:
> Prevent adding duplicate entries on epigenomic activity and segmentation features

- modules/EnsEMBL/Web/Document/HTML/ConsequenceTable.pm
VEP consequences table: add missing VEP consequence and update order of consequences.
http://wp-np2-11.ebi.ac.uk:6070/info/genome/variation/prediction/predicted_data.html
No complications expected.
[ENSVAR-5607](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5607)
> Update VEP consequences (110)

- modules/EnsEMBL/Draw/GlyphSet_transcript_new.pm
Fix Compara issue 
Compara
_We appreciate this can be difficult but please highlight any views that you think might possibly be adversely affected by this change. For example a change to method in ApacheHandlers.pm has potential for widespread consequences._
_At certain stages of the release there is potential for many people to be working on the same modules. To avoid merge conflicts please confirm …
> Fix compara ENSWEB-6819

- htdocs/info/about/collaborations/index.html
A minor change to the content to correct a missing update for  [ENSWEB-6783 Paul Flicek leaving](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6783)
> Updated contact details for collaboration

- conf/SiteDefs.pm
- htdocs/components/22_dynamic_content.css
- htdocs/components/25_ConfigRegMatrixForm.js
- modules/EnsEMBL/Web/Component/Regulation/Summary.pm
This is [w.r.t the shared regulation and location view config changes](https://github.com/Ensembl/ensembl-webcode/pull/979).
An text with information has been added. Also the button text was renamed from `View tracks` to `Apply config` as there are no more track view in regulation view.
> Update regulation summary page UI to add info message

- modules/EnsEMBL/Web/Component/DataExport/Orthologs.pm
In support of https://github.com/EnsemblGenomes/eg-web-metazoa/pull/27
See details in the description of that PR.
> Split out a method for preparation of download form

- modules/EnsEMBL/Web/Query/Generic/GlyphSet.pm
Method `EnsEMBL::Web::Query::Generic::GlyphSet::fixup_alignslice` is used as part of the process of drawing `AlignSlice` transcript tracks in alignment views.
As part of this method, the `AlignSlice::Slice` is fetched from the relevant `AlignSlice` object and matched by species (specifically, `genome_db`) name.
This works fine in the vast majority of cases, but for the per-subgenome Wheat Cactus alignment views being introduced in e111, it results in gene/transcript tracks of one subgenome being shown for all subgenomes in that species.
This change affects comparative genomic alignment views containing gene/transcript tracks, such as the Wheat Cactus alignment.
Because the change only takes effect if a given `AlignSlice::Slice` has a `distinct_Slice_name` which is different from its …
> Match by distinct_Slice_name when fixing up slice

- modules/EnsEMBL/Web/ZMenu/Variation.pm
[ENSVAR-4674](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-4674)
https://www.ensembl.org/Homo_sapiens/Location/View?r=19%3A35723836-35723836 
/modules/EnsEMBL/Web/ZMenu/Variation.pm
> Removing GRCh37

- modules/EnsEMBL/Web/Component/Info.pm
- modules/EnsEMBL/Web/Component/Regulation/Summary.pm
- modules/EnsEMBL/Web/ImageConfigExtension/Tracks.pm
- modules/EnsEMBL/Web/ZMenu/Regulation.pm
Update labels for tracks and zmenu
Region in detail, Configuration and Regulation views
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6911
> ENSWEB-6911 update labels for regulation tracks and zmenu

- modules/EnsEMBL/Web/Component/Summary.pm
The changes in this PR update the transcript summary code to recover the `Ensembl Canonical` tag in transcripts for which the `is_canonical` transcript attribute is missing.
This affects the transcript summary, enabling the …
> Recover Ensembl Canonical tag in transcript summary

- conf/SiteDefs.pm
We have been asked to link to the EMBL-EBI data preservation article now on www.ebi.ac.uk. This is stage one of that work, which adds the URL to sitedefs. Another PR is going in on public-plugins ensembl/public-plugins#773 which uses the value to render a link to it.
- No views in this change
- Eventually this will filter to all fat footer pages
This is a change in SiteDefs so it will potentially be …
> Data preservation work

- modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm
With the [recent removal of several Compara REST API endpoints](https://www.ensembl.info/2023/06/09/changes-to-endpoints-of-ensembl-compara-apis/), Wasabi links generated using one of the removed REST endpoints no longer work.
In addition, [recent changes to Metazoa gene-trees](https://www.ensembl.info/2023/07/19/expanding-ensembl-metazoa-gene-trees/) have changed the conditions under which it might be appropriate to use a gene stable ID to generate a Wasabi link. To be specific, 70-75% of gene trees in the Protostomes and Insects collections lack a gene-tree stable ID, so using a gene stable ID represents perhaps the most practical alternative way of generating a Wasabi link for most Metazoa gene trees.
In addition, these changes expand the set of strain/breed/cultivar gene trees with …
> Update and expand Wasabi link generation

- modules/EnsEMBL/Web/Query/Availability/Gene.pm
In conjunction with [staging patch 656](https://github.com/Ensembl/staging-patches/pull/656) and [eg-web-common PR 121](https://github.com/EnsemblGenomes/eg-web-common/pull/121), this PR would make homoeologues accessible for Triticum aestivum cultivars and some Triticum species in the Ensembl Plants website.
This PR helps with this by adding a `strain_homoeologs` count.
These changes would help add a …
> Add strain_homoeologs count

- modules/EnsEMBL/Web/Object/Gene.pm
Nested supertrees pose a couple of challenges for the supertree web view.
As reported in [ENSCOMPARASW-7495](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-7495), in the supertree view of some genes (e.g. [A. thaliana gene AT1G71695](https://plants.ensembl.org/Arabidopsis_thaliana/Gene/Compara_Tree?g=AT1G71695)), the set of subtrees includes among them a supertree (e.g. `PTHR31235_SF5`). The …
> Unfurl nested supertree in supertree view

- modules/EnsEMBL/Web/ConfigPacker.pm
- modules/EnsEMBL/Web/Document/HTML/Compara.pm
In conjunction with [eg-web-plants PR 65](https://github.com/EnsemblGenomes/eg-web-plants/pull/65), this PR (for the `release/112` branch only) makes it possible to suppress the Wheat Cactus alignment on the Ensembl Plants 112 site.
To take effect, it is necessary to repack the `MULTI` packed file.
This change has the effect of making the Wheat Cactus alignment disappear from the Wheat genomic …
> Add method to enable Cactus alignment to be hidden

- conf/ini-files/COLOUR.ini
- modules/EnsEMBL/Draw/GlyphSet/fg_regulatory_features.pm
Add EMAR as a regulatory feature type.
http://wp-np2-25.ebi.ac.uk:6020/Homo_sapiens/Location/View?r=17:63992802-64038237
> [113] Add EMAR as reg. features

- modules/EnsEMBL/Web/Component/Regulation/FeatureDetails.pm
- modules/EnsEMBL/Web/ZMenu/Regulation.pm
Disable activity for EMARs and CTCFs.
http://wp-np2-25.ebi.ac.uk:6020/Homo_sapiens/Regulation/Summary?db=core;fdb=funcgen;r=17:63992802-64038237;rf=ENSR17_5K3LDJ
> [113] Disable activity for EMARs and CTCFs

- modules/EnsEMBL/Web/Command/Help/SendEmail.pm
- modules/EnsEMBL/Web/Component/Help/Contact.pm
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6954
Add a simple logic to stop spamming contact us page
http://wp-np2-1e.ebi.ac.uk:9000/
> Add logic question to contact us form to avoid spamming

- conf/Plugins.pm-dist
Added missing comma preventing compilation.
_We appreciate this can be difficult but please highlight any views that you think might possibly be adversely affected by this change. For example a change to method in …
> add missing comma

- modules/EnsEMBL/Web/Document/HTML/Compara/GeneTrees.pm
This PR changes the `EnsEMBL::Web::Document::HTML::Compara::GeneTrees` module to:
- order taxa in the gene-tree stats species tree by decreasing number of descendant taxa, then by first-sorting leaf label; and
- change the `species_tree_node_label` function to a method, and cache node labels by `species_tree_node.node_id`.
These changes should make the ordering of the gene-tree stats species tree more consistent across releases, with a view to facilitating Compara staging-site testing, and perhaps even make it easier for the user to find their species of interest in the tree.
This PR affects:
- protein-tree stats view: [sandbox](http://wp-np2-25.ebi.ac.uk:5092/info/genome/compara/prot_tree_stats.html) vs [live site](http://www.ensembl.org/info/genome/compara/prot_tree_stats.html)
- …
> Order stats species tree more consistently across releases

- modules/EnsEMBL/Web/Component/Info/HomePage.pm
Use `funcgen` PERL API to retrieve the sample reg. feature instead of the `INI` file.
Species INFO pages:
- http://wp-np2-25.ebi.ac.uk:6020/Homo_sapiens/Info/Index
- http://wp-np2-25.ebi.ac.uk:6020/Sus_scrofa/Info/Index
- ...
[ENSREGULATION-2281](https://www.ebi.ac.uk/panda/jira/browse/ENSREGULATION-2281)
> [r114] Retrieve sample reg. features from funcgen DB

- modules/EnsEMBL/Web/ConfigPacker.pm
This PR would change `ConfigPacker::_summarise_pan_compara` to take the list of Pan Compara genomes directly from the Pan Compara database.
This would allow Pan Compara databases to be configured on a sandbox or staging site prior to Compara handover, with the following benefits:
- it would remove a potential hiccup in the configuration of a Pan Compara database in a sandbox/staging site;
- it would …
> Get Pan Compara status from Pan Compara database

- conf/SiteDefs.pm
- ctrl_scripts/precache-farm.pl
- Migrate precache generation script from using LSF to Slurm for job submission
- Update datafiles root path
Related tickets: [ENSWEBREL-1018](https://www.ebi.ac.uk/panda/jira/browse/ENSWEBREL-1018), [ENSWEBREL-1056](https://www.ebi.ac.uk/panda/jira/browse/ENSWEBREL-1056)
> Migrate precache script to slurm

- conf/SiteDefs.pm
Startup E!115
N/A
None
None
https://embl.atlassian.net/browse/ENSWEBREL-854
> Startup E!115

- conf/SiteDefs.pm
Updating 114 go live to May
Footer 
None
None
> Updating 114 go live to May

- modules/EnsEMBL/Web/Document/HTML/FTPtable.pm
Fix broken ftp link that references a species defs value. Tested on staging.
https://www.ensembl.org/info/data/ftp/index.html
> Fix FTP URL

- modules/EnsEMBL/Web/Document/Element/TmpMessage.pm
Re-enable banner cfg behaviour as per ENSWEBSOPS-136
Main page
None
None
> Fixed announcement colour behaviour as per Web SOP

- modules/EnsEMBL/Web/ConfigPacker.pm
Recent changes to Compara config packing have facilitated the display of more relevant species-set information in Ensembl Vertebrates, Plants and Metazoa. However, this change was not applied to Ensembl Fungi/Protists Compara databases, though each has many genomes with comparative data that are not included in gene trees.
This PR would pack `CLUSTERSET_PRODNAMES` for every gene-tree collection in each Compara division's `MULTI.db.packed` file, making it possible to provide more relevant species-set info in Ensembl Protists and Fungi.
This change would affected the following features in Ensembl Fungi/Protists:
- the orthologue tallies in the summary shown above orthologue tables;
- the list of "Species without orthologues" below orthologue tables;
- the list of "Selected species" in the …
> Pack CLUSTERSET_PRODNAMES for all gene-tree collections
