modules/EnsEMBL/Web/ConfigPacker.pm
e.g. table may only contain ranks 3,4,5, in which case we want to choose 3
=> Fix ASSEMBLY_VERSION bug - don't assume top rank will be 1 

modules/EnsEMBL/Draw/GlyphSet/_prediction_transcript.pm
E.g. see call in parent class https://github.com/nicklangridge/ensembl-webcode/blob/master/modules/EnsEMBL/Draw/GlyphSet_transcript.pm#L129
=> Allow for case where _prediction_transcript::href is called without a transcript

modules/EnsEMBL/Web/ViewConfig/Gene/ComparaTree.pm
As far as I know TAXON_LABEL is not a compulsory field in every species ini file (but I'm not sure how to verify this...?)
=> Don't assume TAXON_LABEL is always set

conf/ini-files/DEFAULTS.ini
Decipher is only available on https (http does a redirect).
#t_features no longer exists.
=> Updated links to Decipher

modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm
In this piece of code, $tree is in fact the root node of the tree. $tree->tree is the tree object itself
=> get_SimpleAlign is faster when called on GeneTree rather than GeneTreeNode

modules/EnsEMBL/Web/Text/FeatureParser.pm
Otherwise the window may be too big to display for small genomes
=> When choosing nearest feature, scale the window according to genome size

modules/EnsEMBL/Web/Component/Shared.pm
This should fix the background colour rendering bug e.g. on this page:
http://www.ensembl.org/Homo_sapiens/Variation/Mappings?db=core;r=9:128322579-128323579;tl=G0g9KEdTlIpzyFBE-773424;v=rs377735694;vdb=variation;vf=67052133
(SIFT column has some values rendered white text on grey BG)
Would be nice if this could go on release/79 too, but wasn't sure how to do the git mpush thing with a forked repo.
=> add SIFT low confidence prediction strings

modules/EnsEMBL/Web/Object/Export.pm
Removing an emty line between headers when we export a sequence. 
(GO to an example transcript page, click the Export Data button, then select FASTA, export as text.)
http://www.ensembl.org/Danio_rerio/Transcript/Summary?db=core;g=ENSDARG00000062187;r=22:22801609-22839541;t=ENSDART00000089622
=> ensembl-3452: Removing blank line between headers when export sequence

modules/EnsEMBL/Draw/GlyphSet/genetree.pm, modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm, modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm
1. New option to collapse the gene-tree nodes at a given taxonomic rank
There is a new drop-down menu at the bottom of the gene-tree display, after the other links to collapse / expand nodes. The code lists the nodes that are under the rank cutoff and collapses them
http://enssand-01.internal.sanger.ac.uk:9073/Homo_sapiens/Gene/Compara_Tree?;db=core;g=ENSG00000139618;r=13:32315474-32400266
2. Table header in the Orthologues page
Feedback from workshops tells that there is sometimes some confusion in this table. People think that the numbers represent #orthologues. They are in fact #species
OLD http://staging.ensembl.org/Homo_sapiens/Gene/Compara_Ortholog?db=core;g=ENSG00000139618;r=13:32315474-32400266
NEW http://enssand-01.internal.sanger.ac.uk:9073/Homo_sapiens/Gene/Compara_Ortholog?db=c …
=> Species genus order

modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm
to solve ENSWEB-1400
I don't know why but `$self->hub->param('clusterset_id')` in the ZMenu can't access the parameter defined in the page... To overcome this, we fetch the node from the database
=> Allow ZMenus on gene-tree nodes when the non-default tree has been selected

modules/EnsEMBL/Web/Object/Transcript.pm
A new feature has been introduced by James Allen team to indicate a transcript is trans-spliced or not. This method gets the information when a particular transcript is trans-spliced. 
At the moment, I am calling this method/sub from EnsEMBL::Web::Component::Transcript::TranscriptSummary (see below) on eg-web-common to populate the information on the page and will be pushed once this pull request is accepted.
``` my $trans_spliced_transcript_info = $object->get_trans_spliced_transcript_info;```
``` $table->add_row($trans_spliced_transcript_info->name, $trans_spliced_transcript_info->description) if $trans_spliced_transcript_info;```
I was told this feature will also be needed in Ensembl(Please read the ticket ENSEMBL-4008) - So, this pull request - For example, for fruit fly and few …
=> ENSEMBL-4008 - Added feature to retrieve trans-spliced transcript information if the transcrpt is trans-spliced    

modules/EnsEMBL/Web/Component/Transcript/TranscriptSummary.pm
This code calls a method
get_trans_spliced_transcript_info which was created in the commit 395509e18215ecbc2bce3300cd267d51c596c0a6
This code was initially added to eg-web-common into a method which overrides its equivalent method in ensembl-webcode. 
Now adding it in ensembl-webcode to make it work on ensembl website too.
=> Code added to call get_trans_spliced_transcript_info method added in the commit 395509e18215ecbc2bce3300cd267d51c596c0a6.

htdocs/components/90_configurator.css
A very small css update - Added margin bottom to long label. Please see the attached images for clarity. No space between long label and the next line in the case of single track[Image 1]. But when we have multiple tracks with the line 'Enable/disable all ..', there is enough space[Image 2].
Thanks,
Sanjay
=> Added margin bottom to the long_label in the trackhub label display

modules/EnsEMBL/Web/ConfigPacker.pm
Also, we can simply take all the GenomeDBs regardless of their first/last_release status
=> genome_db.assembly_default has been removed in e82

modules/EnsEMBL/Draw/GlyphSet/_alignment_multiple.pm
This fixes some warnings noticed by Anne in the logs whilst working on ENSWEB-1690
=> Faster way to detect whether a species is "low-coverage" or not

modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm
Fixes a bug of the live website:
1. go to http://www.ensembl.org/Homo_sapiens/Gene/Compara_Tree?collapse=none;db=core;g=ENSG00000276057;r=22:30971296-30971382;t=ENST00000614234 
2. Click "configure this page"
3. In "Model used for the tree reconstruction" choose another option
4. Close the panel
You'll get
```
AJAX error - Runtime Error in component "EnsEMBL::Web::Component::Gene::ComparaTree [content]"
Function EnsEMBL::Web::Component::Gene::ComparaTree fails to execute due to the following error:
Can't call method "taxon" on an undefined value at
... /ensemblweb/www/www_82/ensembl-webcode/modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm line 421, <DATA>
... line 1000.
```
Tried on my sandbox http://enssand-01.internal.sanger.ac.uk:9073/Homo_sapiens/Gene/Compara_Tree?collapse=none;db=cor …
=> Trees may be missing the taxon annotation. Skip those

modules/EnsEMBL/Draw/GlyphSet/V_density.pm
Original ticket https://www.ebi.ac.uk/panda/jira/browse/ENSEMBL-4088?filter=-1
Chromosome summary doesn't appropriately scale the bars showing gene counts.
The max value for the image should be set based on the real array values
rather than $image_config->get_parameter( 'max_value' )
Currently, in some cases $image_config->get_parameter( 'max_value' ) <  max value of the array elements and the image is scaled incorrectly, adding horizontal scrolling to the page.
=> ensembl-fix: ensembl-4088 Chromosome summary not scaled properly

modules/EnsEMBL/Web/ViewConfig/Gene/ComparaTree.pm
The option to control taxonomic colouring of gene trees needs to be in the "order" list, otherwise it is omitted from the config menu.
=> Display box for controlling gene tree colouring in the config menu

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm
On page:
http://www.ensembl.org/Homo_sapiens/Gene/Compara_Ortholog?g=ENSG00000139618;r=13:32315474-32400266
species under section 'Selected Orthologs' are again appearing under the section 'Species without orthologues'. This little tweak should fix it.
=> ENSEMBL-4243 - Incorrect message on ortholog page

modules/EnsEMBL/Web/Component/Gene/FamilyProteins.pm
Could you merge it to Master and release/83 please?
That variable '$current_taxon' is not being used anywhere else in this module and is also causing issues on live EG sites.
Thanks,
Sanj
=> Removed unused/obsolete code as it is causing error on EG

modules/EnsEMBL/Draw/GlyphSet/genetree.pm, modules/EnsEMBL/Web/Component/Gene/SpeciesTree.pm, modules/EnsEMBL/Web/Object/Gene.pm
The related schema + API changes are on Compara master (=e84). We haven't handed over yet, but I have successfully run this on the protein-trees database
In the end, I found a relatively simple solution to make the species-tree view work, and it shouldn't impact the fallback view. There is a related pull-request in public-plugins/widget https://github.com/Ensembl/public-plugins/pull/48
=> Use Compara's precomputed JSONs

modules/EnsEMBL/Web/Component/Transcript/PopulationImage.pm
This is broken on live on both E and EG. Please see the following page:
http://www.ensembl.org/Mus_musculus/Transcript/Population/Image?db=core;g=ENSMUSG00000041143;r=4:138972905-139059167;t=ENSMUST00000050949
This update seems to fix the issue on EG. Not sure how to test this fix against Ensembl site.
Thanks,
Sanjay
=> Export this image bug - Broken on live

modules/EnsEMBL/Web/Document/HTML/Compara.pm, modules/EnsEMBL/Web/Document/HTML/Compara/BlastZ.pm, modules/EnsEMBL/Web/Document/HTML/Compara/MLSS.pm
Several changes in the Compara documention
http://enssand-01.internal.sanger.ac.uk:9073/info/genome/compara/analyses.html is quite different and is faster than http://www.ensembl.org/info/genome/compara/analyses.html
Multiple alignments have their own page:
http://enssand-01.internal.sanger.ac.uk:9073/info/genome/compara/mlss.html?mlss=780
Stats for self-alignments are not duplicated any more:
http://enssand-01.internal.sanger.ac.uk:9073/info/genome/compara/mlss.html?mlss=739
http://www.ensembl.org/info/genome/compara/mlss.html?mlss=739
=> Compara stats

modules/EnsEMBL/Draw/GlyphSet/_variation.pm, modules/EnsEMBL/Draw/GlyphSet/cnv_probes.pm, modules/EnsEMBL/Draw/GlyphSet/structural_variation.pm, modules/EnsEMBL/Web/Component/Gene/TranscriptComparison.pm, modules/EnsEMBL/Web/Component/LRG/LRGDiff.pm, modules/EnsEMBL/Web/Component/Location/SequenceAlignment.pm, modules/EnsEMBL/Web/Component/SVTable.pm, modules/EnsEMBL/Web/Component/Shared.pm, modules/EnsEMBL/Web/Component/TextSequence.pm, modules/EnsEMBL/Web/Component/Transcript/ExonsSpreadsheet.pm, modules/EnsEMBL/Web/Component/Variation/Mappings.pm, modules/EnsEMBL/Web/Component/VariationTable.pm, modules/EnsEMBL/Web/Component/Variation_Context.pm, modules/EnsEMBL/Web/Object/Export.pm, modules/EnsEMBL/Web/Object/Location.pm, modules/EnsEMBL/Web/Object/Slice.pm
This PR replaces methods from the core API that will be deprecated in release 84. All the methods are now in the variation API. We want to get rid of all variation API dependencies in the core API. You need the variation and core API master branches for this PR.
=> 84 feature/update deprecated methods

modules/EnsEMBL/Web/Component/Transcript/Haplotypes.pm
get_all_flags method only exists on ProteinHaplotype but not on CDSHaplotype, so the can() test is valid and doesn't require eval
=> Remove eval and erroneous empty hashref return

modules/EnsEMBL/Web/Document/Element/StaticNav.pm
I noticed that the left-hand side menu for the Compara static documentation places "ncRNA (...)" at the end of the list: http://www.ensembl.org/info/genome/compara/index.html
I found these two places in StaticNav.pm that are used to sort stuff and I simply turned the comparison to a case-insensitive one. It works on my sandwork
=> Sort the items in a case-insensitive manner

modules/EnsEMBL/Web/Object/Export.pm
Seems we did not minus 1 from our output when we were exporting into BED. Since BED is 0-based start and 1-based end we only need to minus this from the start. We assume all input coordinates are 1-based (they're from the API so this should be right).
=> Fixing BED. Missed conversion to 0-based start

modules/EnsEMBL/Web/Component/Transcript/DomainSpreadsheet.pm
Requested by @markmcdowall
Seems reasonable, but not sure if Ensembl has specific reason to avoid the hit description.
=> Use the hit description before looking for interpro description

modules/EnsEMBL/Web/Component/Transcript/PopulationImage.pm, modules/EnsEMBL/Web/Component/Transcript/PopulationTable.pm
More details in JIRA ENSEMBL-4500
This fix configures the variation db to use VCF files if that is what is configured for the species - without it we will sometimes get adaptors that don't use the VCF and so return no data.
It's a pragmatic fix; it feels like a hack to put this configuration in the components and better solution might be to do it in a generic way at the time the adaptors are created. But after talking with @ens-ds23 it sounds like this approach has been tried before and is difficult to get right.
=> Fix intermittent 'no data' bug for population image/table

modules/EnsEMBL/Web/Component/Variation/Summary.pm, modules/EnsEMBL/Web/Object/Variation.pm
Insertions and deletions in dbSNP do not have their positions normalised, so a variant in a repetitive sequence may have multiple records with with different rs ids reflecting different possible positions. We are now comparing all insertions/deletions and flagging matching records.
=> show variants with identical alleles when descriptions normalised

modules/EnsEMBL/Web/Object/Variation.pm
We are currently not displaying the submitter handle for one subsnp when multiple subsnps for a variant are typed twice in the same population. Example : rs1333049 & HapMap-HCB
=> fix to display submitter when a variant typed twice in a population

conf/ini-files/DEFAULTS.ini
we have new VGNC (Vertebrate Gene Nomenclature Committee) symbols for this release, only for chimp
note the website is not live yet, but they promised it would be by the end of the week
=> url for VGNC symbols

modules/EnsEMBL/Web/Document/HTML/Compara.pm, modules/EnsEMBL/Web/Document/HTML/Compara/MLSS.pm
A couple of commits to add more stats in the WGA pages:
- a barplot distribution of the size of the alignment blocks
- added the %identity at the exon level
All the stats were already in the database, so it was just a matter of displaying them
Pairwise alignments:
http://enssand-01.internal.sanger.ac.uk:9073/info/genome/compara/mlss.html?mlss=688 vs http://www.ensembl.org/info/genome/compara/mlss.html?mlss=688
Multiple alignments
http://enssand-01.internal.sanger.ac.uk:9073/info/genome/compara/mlss.html?mlss=647 vs http://www.ensembl.org/info/genome/compara/mlss.html?mlss=647
=> More WGA stats

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm, modules/EnsEMBL/Web/Component/Gene/ComparaParalogs.pm
ENSWEB-2583 (show %id with 2 decimal places) and ENSEMBL-2872 (definition of "Target %ID" and "Query %ID")
Tested on my sandbox
http://enssand-01.internal.sanger.ac.uk:9073/Homo_sapiens/Gene/Compara_Ortholog?g=ENSG00000138759;r=4:78057570-78544269
http://enssand-01.internal.sanger.ac.uk:9073/Homo_sapiens/Gene/Compara_Paralog?g=ENSG00000138759;r=4:78057570-78544269
=> Several tweaks to the ortholog table

modules/EnsEMBL/Web/File/AttachedFormat/TRACKHUB.pm
This is an extension to the commit by Anne
https://github.com/Ensembl/ensembl-webcode/commit/5641ad73378129ec6c5e91578c3c9b5f511709f7
Takes care of error messages like the following:
Found 1 problem:
Unsupported type 'cram' in hub ftp://ftp.ensemblgenomes.org/pub/misc_data/Track_Hubs/SRP033660/hub.txt genome TAIR10 track SRR1046889
Also changed the way we run the hubcheck command. system() is returning exit status information rather than the command output. So, using Backticks.
=> Skip error messages that we don't care about while attaching trackhubs

conf/ini-files/DEFAULTS.ini, modules/EnsEMBL/Web/Component/Location/LDImage.pm, modules/EnsEMBL/Web/Component/Variation/HighLD.pm, modules/EnsEMBL/Web/Component/Variation/LDPlot.pm, modules/EnsEMBL/Web/Component/Variation/PairwiseLD.pm, modules/EnsEMBL/Web/Object/Location.pm
We have a new, faster method for calculating LD from VCF files.
This involves compiling and installing a new binary; this PR contains the config to point to that and set it up for use when the appropriate method is called.
For 86 e! webservers will need to have this new ld_vcf binary in $PATH (I've copied the current DEFAULTS.ini setup for the existing calc_genotypes binary, which is still required).
Compilation instructions are in the [README](https://github.com/Ensembl/ensembl-variation/blob/master/C_code/README.txt).
=> updates to use new ld binary from ensembl-variation

modules/EnsEMBL/Web/Component/UserData.pm, modules/EnsEMBL/Web/Component/UserData/FeatureView.pm
As discussed with Steve, users should be uploading only on the species they are viewing.
=> 'Add Feature' modal on chromosome page needs to default to current species

modules/EnsEMBL/Web/Object.pm
When fetching alignment, match entire species name as mouse strains were matching mus_musculus and were, therefore, being skipped
=> Bugfix: HAL alignment display

modules/EnsEMBL/Web/Apache/Handlers.pm
In the event that $path_seg->[0] is not defined, this line creates a warning in the logs
=> Check $path_seg->[0] is defined

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm
This is to fix 
https://www.ebi.ac.uk/panda/jira/browse/ENSEMBL-4780
=> Display link to ortholog gene page even when it doesnt have any display id

modules/EnsEMBL/Web/Component/Gene/RegulationImage.pm, modules/EnsEMBL/Web/Component/Gene/TranscriptsImage.pm, modules/EnsEMBL/Web/Component/Location/ViewBottom.pm, modules/EnsEMBL/Web/Component/Regulation/Summary.pm, modules/EnsEMBL/Web/Component/Transcript/ProteinVariations.pm, modules/EnsEMBL/Web/Component/Variation/HighLD.pm, modules/EnsEMBL/Web/Component/Variation/Mappings.pm, modules/EnsEMBL/Web/DBSQL/DBConnection.pm, modules/EnsEMBL/Web/Factory/StructuralVariation.pm, modules/EnsEMBL/Web/ImageConfig/contigviewbottom.pm, modules/EnsEMBL/Web/ImageConfig/regulation_view.pm, modules/EnsEMBL/Web/ImageConfigExtension/Tracks.pm, modules/EnsEMBL/Web/Object/Gene.pm, modules/EnsEMBL/Web/Object/LRG.pm, modules/EnsEMBL/Web/Object/Regulation.pm, modules/EnsEMBL/Web/Object/Slice.pm, modules/EnsEMBL/Web/Object/Variation.pm, modules/EnsEMBL/Web/ViewConfig/Regulation/FeatureDetails.pm
Due to Perl's autovivification feature, if a key is not defined, dereferencing
it will automaticaly create an empty hash as value for that key. This will be
an issue when checking if the key is defined elsewhere.
This change remove this potential problem for 'DATABASE_FUNCGEN' and 'DATABASE
_VARIATION' keys in species_defs->databases.
Related to ENSEMBL-4611.
=> fix: check if a key is defined before dereferencing it

modules/EnsEMBL/Web/Controller/Ajax.pm
=> ENSWEB-2158 Replace non-breakable spaces for csv export

conf/perl.startup
This change allows us to set different value for the MAX_PROCESS_SIZE for each division
and make it under source control.
Related to ENSEMBL-4763.
=> Make MAX_PROCESS_SIZE configurable

modules/EnsEMBL/Web/Component/Gene/GenePhenotypeOrthologue.pm
Unfortunately for Plants compara, there are other species from other divisions.
But we do not have species defs for those species.
Fixes ENSEMBL-4853.
=> fix: check if a config exists before dereferencing it

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm
- GOC and WGA values need to be n/a only when their value is undef.
- High confidence values need to be Yes/No
Please see the ticket for more details
=> ENSEMBL-4867 - Zero-valued GOC and WGA scores not displayed

modules/EnsEMBL/Draw/GlyphSet/genetree.pm, modules/EnsEMBL/Web/Component/Gene/ComparaParalogs.pm, modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm, modules/EnsEMBL/Web/ConfigPacker.pm, modules/EnsEMBL/Web/Document/HTML/Compara/GeneTrees.pm, modules/EnsEMBL/Web/Document/HTML/Compara/MLSS.pm, modules/EnsEMBL/Web/Hub.pm, modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm, modules/EnsEMBL/Web/ZMenu/SpeciesTree.pm
From e88 we have a number of new methods to get common names (also known as "ensembl alias" or "display name"), scientific names, etc. This simplifies several modules, and removes the need of building lookup tables in the ConfigPacker (which @Zhicheng-Liu should like). 
I don't know how to test the changes at the EBI, so I have used my Sanger sandbox with the e87 databases instead.
Pages affected are:
/Homo_sapiens/Gene/Compara_Tree?g=ENSG00000139618 : common names on the collapsed nodes, clade names in the zmenus, ability to hide/show some clades (in Configure This Page)
/Homo_sapiens/Gene/Compara_Paralog?g=ENSG00000189167 : the "Ancestral taxonomy" column
/info/genome/compara/prot_tree_stats.html?page=coverage and the other pages in the same section : Species/clade names
=> Use new Compara methods to get species/clade names

modules/EnsEMBL/Web/ViewConfig/Gene/ComparaTree.pm
If TAXON_GENETREE_BGCOLOUR or TAXON_GENETREE_FGCOLOUR contain less entries than TAXON_ORDER (which may be the case if these colours are not being used - as in case of e!g) previously this caused 'uninitialised' warnings.
=> Prevent spamming the logs with uninitialised warnings

modules/EnsEMBL/Web/Component/Gene/HistoryLinked.pm, modules/EnsEMBL/Web/Component/Gene/HistoryMap.pm, modules/EnsEMBL/Web/Component/Gene/HistoryReport.pm
Some sites may not have an archive db so we shouldn't always expect to get an archive object.
=> Don't die if there is no archive db

modules/EnsEMBL/Draw/GlyphSet/alignscalebar.pm
When we see a jump between scaffolds / contigs, it may well be there in fact part of the same chromosome.
This is done by checking whether the Slice objects are on the karyotype.
Tested on my sandbox: http://enssand-02.internal.sanger.ac.uk:9073/Homo_sapiens/Location/Compara_Alignments/Image?align=829;db=core;g=ENSG00000139618;r=13:32232872-32482873
Select human and pig from the "EPO LOW COVERAGE"
=> Only mention "There is a breakpoint in the alignment between chromosome" between real chromosomes

conf/ini-files/DEFAULTS.ini
Beta version is now retired and causing issues when used to search trackhub registry.
=> Beta is retired now

modules/EnsEMBL/Web/Query/Availability/Gene.pm
With current implementation, in order to decide whether to enable ontology related menu items
on the left hand side of a page (e.g. gene summary), it needs to fetch from ontology database
for related ontologies.
The lookup of ontology adaptor takes long time for Bacteria because the underlying implementaion
requires an exhaustive iteration through the whole registry:
https://github.com/Ensembl/ensembl/blob/release/88/modules/Bio/EnsEMBL/Registry.pm#L705-L714
Furthermore, the current implementation repeatly fetches from the database for the same query:
https://github.com/Ensembl/ensembl-webcode/blob/release/88/modules/EnsEMBL/Web/Query/Availability/Gene.pm#L282
This change tries to fetch from the ontology database for only once.
=> Avoid loop when querying for ontology availability

modules/EnsEMBL/Web/SpeciesDefs.pm
Every species of a collection has reference to same DB_SPECIES array. 
And hence this will cause duplicate entries if pushed into an array.
=> Remove duplicates from valid_species in case of collection species

modules/EnsEMBL/Draw/Role/Bam.pm
For some cram files, the htslib consumes large amount of memory to parse and fetch data
from them. This creates a problem for a location view that has multiple those cram tracks
configured. The memory will quickly exceed the process limit.
This change removes the htsobj cache once the data is fetched for a certain track which
effectively clean up the memory so that all the following tracks could have enough memory
to be processed.
Related to ENSEMBL-5035.
=> Remove htsobj cache once data is fetched from bam/cram

modules/EnsEMBL/Web/SpeciesDefs.pm
When renaming keys, allow for the case where production_name and species.url are the same.
=> Don't delete config if key wasn't renamed

utils/google_sitemaps/make_google_sitemap_by_species.pl, utils/make_gene_autocomplete.pl
Use SiteDefs PRODUCTION_NAMES as it contains db names (including collections), instead of SpeciesDefs ENSEMBL_DATASETS which contains individual genome names. This wy we can process in bulk instead of every individual genome.
=> Make scripts work better with collection core databases

modules/EnsEMBL/Web/Factory/Feature.pm
Some of the transcripts associated with a probe or probeset are not present in transcript table.
See ticket for more info.
=> ENSEMBL-5002 - Oligo probe "View all locations" broken

modules/EnsEMBL/Web/Component/LD.pm, modules/EnsEMBL/Web/Component/Variation.pm, modules/EnsEMBL/Web/Component/Variation/HighLD.pm, modules/EnsEMBL/Web/Component/Variation/PairwiseLD.pm, modules/EnsEMBL/Web/Component/Variation/PopulationGenotypes.pm, modules/EnsEMBL/Web/Component/Variation/SampleGenotypes.pm, modules/EnsEMBL/Web/Component/Variation/Summary.pm
dbSNP is no longer supporting non-human variants (will be supported by EVA next year) therefore we need to remove the deprecated links to dbSNP for the non-human species
=> Remove dbSNP links for the non-human species

modules/EnsEMBL/Web/Object/Gene.pm
As discussed with Myrto, this will fix the gene regulation image, but not the table.
A git pull from the regulation repository is not required.
=> Fix for https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-4278

modules/EnsEMBL/Web/ZMenu/Gene.pm, modules/EnsEMBL/Web/ZMenu/Transcript.pm
This is a proposed fix for https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-4174.
=> The 'novel' terminology has been deprecated, so remove term from z-menu title

htdocs/components/90_configurator.css
Proposed fix for https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-3273; there was no image attached to the 'scatter' class, which is what 'Manhattan Plot' map to.
=> Display scatter plot image for Manhattan Plot option

modules/EnsEMBL/Web/Object/Export.pm
This is a proposed fix for https://www.ebi.ac.uk/panda/jira/browse/ENSEMBL-2731. I think users are more familiar with the abbreviations for GTF, GFF and GFF3 than they are with the long forms, so it makes sense to put the filetypes first.
=> Include file type abbreviations that are in common usage in the export options

conf/ini-files/DEFAULTS.ini
I believe this link should take you to KEGG directly, rather than the context-free EC page on www.genome.jp. For example, http://www.kegg.jp/entry/EC00983+1.1.1.205, versus http://www.kegg.jp/entry/1.1.1.205, and the original link which now fails to resolve.
=> Fix KEGG_ENZYME URL resolver in DEFAULTS.ini

conf/ini-files/DEFAULTS.ini, modules/EnsEMBL/Web/Component/Shared.pm
This is the configuration that EG have had for some time. The xref here is actually a compound of two (or more...) things. Firstly a pathway, and then a set of enzymes (EC IDs) - usually it's just one enzyme, but not always. So, rather than linking to a single enzyme page, we can link to a pathway page, with all the enzymes highlighted in red.
=> Link to pathway diagram for InterPro-derived KEGG xrefs

modules/EnsEMBL/Web/Component/PopulationSelector.pm, modules/EnsEMBL/Web/ViewConfig/Location/LDImage.pm, modules/EnsEMBL/Web/ViewConfig/Variation/LDPlot.pm
This fix is for ENSWEB-4360. The sandbox link is: http://ves-hx-78.ebi.ac.uk:8300/Homo_sapiens/Variation/LDPlot?db=core;pop1=373508;r=9:22125004-22126004;v=rs1333049;vdb=variation;vf=906984.
=> Fix for LDPlot redirecting to LD after selecting populations

modules/EnsEMBL/Web/Component/Compara_Alignments.pm
Seems to be fixing ENSWEB-4401
Tested on my sandbox: http://ves-hx2-76.ebi.ac.uk:5080/Capra_hircus/Location/Compara_Alignments?align=1136;db=core;r=5:23186176-23233107
[cc @carlacummins ]
=> bugfix/improvement: there is a cleaner way of checking if the species is "low-coverage" or not

modules/EnsEMBL/Web/Document/HTML/Compara.pm, modules/EnsEMBL/Web/Document/HTML/Compara/BlastZ.pm, modules/EnsEMBL/Web/Document/HTML/Compara/MLSS.pm
[ cc @ens-emily ]
I have copied the [EG way](http://fungi.ensembl.org/compara_analyses.html) of [listing the pairwise alignments](http://staging.ensembl.org/info/genome/compara/analyses.html) (see [my sandbox](http://ves-hx2-76.ebi.ac.uk:5080/info/genome/compara/analyses.html)) with two changes:
- added the common names of species
- replaced the capital letter codes LASTZ_NET, SYNTENY, etc with capitalized text 
There is still an open question. In Ensembl we were sorting the species according to the phylogeny, orienting the tree with the favourite species (by default: human, mouse, zebrafish). Other options are sorting by common name or by scientific name.
=> New way of listing alignments

htdocs/components/91_config_matrix.css, modules/EnsEMBL/Web/Form/ViewConfigMatrix.pm
This is a fix for ENSWEB-4344. With this fix show/hide tutorial button will be displayed next to the configuration modal title.
=> Fix the hide/show tutorial button overlapping the configuration input box

modules/EnsEMBL/Web/Document/HTML/ToolsTable.pm
This pull request is for ENSWEB-4391. The documentation links for Assembly Converter and ID History Converter have been added. The sandbox link is: http://ves-hx-78.ebi.ac.uk:8320/info/docs/tools/index.html.
=> Add missing documentation links in Tools page

modules/EnsEMBL/Web/Document/HTML/GenomeList.pm
This would enable invertebrates divisions to decide whether to add species dropdown or not based on the number of species that particular division has.
=> Allow species dropdown choice for sister sites

modules/EnsEMBL/Web/Component/Variation/PopulationGenotypes.pm, modules/EnsEMBL/Web/Component/Variation/PopulationGraphs.pm
Display populations that only have 2 layers: super_population -> sub_population. At the moment we only deal with 3 layers (1000 genomes project) or 1 layer (everything else). 
I test views for human and sheep and all is working fine. But getting the PR in early would give us more time for testing. Probably @ens-lgil knows the code best and can comment.
=> Display population structures that only have 2 layers

modules/EnsEMBL/Web/Component/Gene/ComparaParalogs.pm
This pull request is for the JIRA ticket 4427. The link to the sandbox is: http://ves-hx-78.ebi.ac.uk:8310/Homo_sapiens/Location/Multi?db=core;g=ENSG00000116539;g1=ENSG00000109685;r=1:155335268-155562807;r1=4:1871424-1982207:1;s1=Homo_sapiens--4.
However, the problem was in the link itself as Steve pointed out. So the fix had to be made in the gene paralogues table. The code for 'Region Comparison' link had to be changed to append the paralogues sequence region rather than the gene's sequence region at the end of the link. The link to the table is: http://ves-hx-78.ebi.ac.uk:8310/Homo_sapiens/Gene/Compara_Paralog?db=core;g=ENSG00000116539;r=1:155335268-155562807.
=> Fix for broken paralogues region comparison

modules/EnsEMBL/Web/Component/Gene/ComparaParalogs.pm
This pull request is for JIRA ticket ENSWEB-4474. A whitespace character is added using the HTML special character 'nbsp' to separate the stable ID and the gene symbol in the generated CSV file for download. The link to the sandbox is: http://ves-hx-78.ebi.ac.uk:8310/Homo_sapiens/Gene/Compara_Paralog?db=core;g=ENSG00000147044;r=X:41514934-41923645.
=> Space delimiter to paralogues table export field

modules/EnsEMBL/Web/Document/HTML/Compara.pm
The most important change is that we store the alignment statistics in a different object. This fixes the stats page: http://staging.ensembl.org/info/genome/compara/mlss.html?mlss=1142
See: http://http://ves-hx2-77.ebi.ac.uk:5083/info/genome/compara/mlss.html?mlss=1142
The other change is to use the pre-built species-tree rather than creating a new one
=> Multiple-alignment stats

modules/EnsEMBL/Draw/GlyphSet/_alignment_multiple.pm
This is a follow-up to 0d885cf7767bc7c85f0f8b61581511d6c832d0ed
=> bugfix/improvement: cleaner way of checking if the species is "low-coverage" or not

modules/EnsEMBL/Draw/GlyphSet/_alignment_multiple.pm
As highlighted by @ens-ap5 , `$object` doesn't exist.
Is it ok to use `$slice->{'web_species'}` (`$slice` is the container) ? It seems I can also do `$self->species`
Tested on my sandbox (human and armadillo) and I could see this in my debug log
```
homo_sapiens is_low_coverage_species= at /net/vnas_homes/ens_adm30/workspace/src/sandbox_staging/ensembl-webcode/modules/EnsEMBL/Draw/GlyphSet/_alignment_multiple.pm line 264.
homo_sapiens is_low_coverage_species= at /net/vnas_homes/ens_adm30/workspace/src/sandbox_staging/ensembl-webcode/modules/EnsEMBL/Draw/GlyphSet/_alignment_multiple.pm line 264.
homo_sapiens is_low_coverage_species= at /net/vnas_homes/ens_adm30/workspace/src/sandbox_staging/ensembl-webcode/modules/EnsEMBL/Draw/GlyphSet/_alignment_multiple.pm line 264.
dasypus_novemcinctus …
```
=> Fix for #637

utils/static_content/update_webdb.pl
Species code is not compulsory, but the unique constraint on the species db table will not allow duplicate rows with empty string for this field.
=> Default to NULL instead of empty string when no species code

modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm, modules/EnsEMBL/Web/ConfigPacker.pm, modules/EnsEMBL/Web/ViewConfig/Gene/ComparaTree.pm
The information is not provided any more on recent Vertebrates assemblies. I think it's (almost) never been set in EG either.
:warning: I haven't tested this on my sandbox !
Then you can also remove the line in public-plugins/ensembl/conf/ini-files/DEFAULTS.ini that has "LOWCOVERAGE"
=> Removed the option to hide so-called "low-coverage" species

modules/EnsEMBL/Web/Object/Variation.pm
The MT link is fixed to link to a genomic location. Previously linked to a transcript location causing an error (ENSVAR-1424)
Transcript links now only set for  'c' or 'n' 
For other types and url is not assigned
=> For HGVS fix MT links and restrict transcript links

modules/EnsEMBL/Web/Component/Variation/Summary.pm
Add external links for OMIM synonym data in the Variation summary panel.
The OMIM data has been moved to the variation synonym in release 94.
Variation pages (summary panel)
http://www.ensembl.org/Homo_sapiens/Variation/Explore?;v=rs333
(with the "Synonyms" line expanded)
=> Add external links for OMIM synonym data

modules/EnsEMBL/Web/Component/Transcript/ProteinVariations.pm, modules/EnsEMBL/Web/Component/VariationTable.pm
When adding the new protein function predictors for release/94 I forgot to exclude mutation assessor for non-human species. The column is displayed for mouse [here](http://staging.ensembl.org/Mus_musculus/Gene/Variation_Gene/Table?db=core;g=ENSMUSG00000050530;r=2:3114224-3227806;source=dbSNP;v=rs27096498;vdb=variation;vf=802802).
gene, transcript, protein variation tables
no
no
na
=> show mutation_assessor only for human

conf/ini-files/DEFAULTS.ini, modules/EnsEMBL/Web/Component/Phenotype/Locations.pm
Wrong URL to MGI when using a MP accession number.
See JIRA issue [ENSVAR-597](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-4798).
Phenotype/Locations:
http://www.ensembl.org/Mus_musculus/Phenotype/Locations?ph=346
Sandbox:
http://ves-hx2-76.ebi.ac.uk:5060/Mus_musculus/Phenotype/Locations?ph=346
=> Use the correct link to MGI when it is using a MP ontology accession

modules/EnsEMBL/Web/Component/Shared.pm, modules/EnsEMBL/Web/Component/Transcript/ProteinVariations.pm, modules/EnsEMBL/Web/Component/VariationTable.pm
Remove code redundancy to associated protein prediction result with CSS classes (for colouring the score boxes) by grouping the hashes into a common hash/method
(look for missense variants)
- Transcript/Variation_Transcript/Table
http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Transcript/Variation_Transcript/Table?t=ENST00000366667
- Transcript/ProtVariations
http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Transcript/ProtVariations?t=ENST00000366667
- Gene/Variation_Gene/Table
http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Gene/Variation_Gene/Table?g=ENSG00000135744
- Variation/Mappings
http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Variation/Mappings?v=rs699
=> Regroup the protein prediction classes into a common method

modules/EnsEMBL/Web/Component/Variation/PopulationGraphs.pm
Depending on the size of the alleles and their frequencies, sometimes they are truncated because the "box" is too small. This fix will allow more flexibility, however the boxes will all be of the same size in the page.
Population genetics, e.g.:
Test: http://test.ensembl.org/Homo_sapiens/Variation/Population?v=rs527885045
Sandbox: http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Variation/Population?v=rs527885045
=> Better width adjustement, depending on the alleles sizes

modules/EnsEMBL/Web/Component/VariationTable.pm
Data export from the Gene/Variation_Gene/Table page were missing entries for all the transcripts except the last one.
The issue was due to the fact we were skipping the loop if the transcript was already in the cache.
Didn't know that the export of the NewTable was rerunning the method `variation_table`, therefore was skipping the transcripts
Vue: Gene/Variation_Gene/Table (for all the species)
- Live website: http://www.ensembl.org/Canis_familiaris/Gene/Variation_Gene/Table?g=ENSCAFG00000016290
- Sandbox: http://ves-hx2-76.ebi.ac.uk:5060/Canis_familiaris/Gene/Variation_Gene/Table?g=ENSCAFG00000016290
Try to export the `missense_variant` only (2 transcripts and 12 rows in total).
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-4826
=> Fix issue with data export missing entries

modules/EnsEMBL/Web/Component/Shared.pm
Change the variation link in "About this transcript" to point to the table for variants associated with the transcript  instead of those associated with the protein.
If there are no proteins, the link currently returns a message  "Sorry, this page is not available for this feature. Please select a valid link from the menu on the left"
The variation count is for the number of transcript variations - changing the link to this table.
Transcript/Summary
Live site:
http://Jan2019.archive.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000262228;r=17:763565-765319;t=ENST00000358446
Sandbox: 
http://ves-hx2-76.ebi.ac.uk:5050/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000262228;r=17:763565-765319;t=ENST00000358446
Checked for merge conflicts and changes are only for update …
=> Update variation link in 'About this transcript'

conf/ini-files/DEFAULTS.ini
Change the dbSNP URL to point to the new rsID pages
Variant summary page for instance (`View in dbSNP` link at the line `Original source`):
- Live: https://www.ensembl.org/Homo_sapiens/Variation/Explore?v=rs699
- Sandbox: http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Variation/Explore?v=rs699
=> Updated dbSNP URL to point to their new website/pages

htdocs/components/85_spreadsheet_table.css, modules/EnsEMBL/Web/Component.pm
The display of the long alleles and the long codons in the Variant Table views are not correct:
2 `+` buttons and when you click on them (only 1 works), the content of the cell is hidden
- Live: http://www.ensembl.org/Homo_sapiens/Transcript/ProtVariations?t=ENST00000525701
- Sandbox: http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Transcript/ProtVariations?t=ENST00000525701
=> Fix display issue on long allele variants in Variant tables

conf/ini-files/DEFAULTS.ini, modules/EnsEMBL/Web/Component/Shared.pm
Biomart uses the data in the defaults.ini file to construct links for output page. But it doesn't do the post-processing in the Shared.pm file, so the biomart urls are broken. We can tweak the url template such that it works without modification, so it works for biomart and means we can eliminate the special treatment in the webcode.
URLs for KEGG_Enzyme xrefs on "General Identifiers" page will be different, but will resolve to the same external page as they currently do.
Not aware of any.
=> Update KEGG_Enzyme url

modules/EnsEMBL/Draw/GlyphSet/genetree.pm, modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm, modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm
In e95 we introduced the term "sub-speciation" for non-duplication splits within a species ("speciation" is not right in those cases). I had misread the web-code and was assuming that the node type would be shown as is, but it isn't :) so I've added it.
Gene-tree view: http://ves-hx2-76.ebi.ac.uk:5085/Homo_sapiens/Gene/Compara_Tree?collapse=none;db=core;g=ENSG00000139618;r=13:32315474-32400266
Click on the parent node of the two Naked mole-rats and it will now show "Sub-speciation"
`modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm` now has the mapping between database terms and display terms. Perhaps you'd prefer this in a Compara module instead ?
Also, this change is only for Vertebrates I believe since EG have overridden several modules:
``` …
```
=> bugfix: Add the missing label of sub-speciation nodes

modules/EnsEMBL/Web/Component/Variation/Summary.pm, modules/EnsEMBL/Web/Object/Variation.pm
None
This is a fix for a bug which I noticed on [staging](http://staging.ensembl.org/Meleagris_gallopavo/Variation/Explore?r=18:72663-73663;v=rs119118426;vdb=variation;vf=5810). The problem being that there was no vcf config file under public-plugins/ensembl/conf/json/ for the species.
Variant summary page
Is $c->{'CONFIG'} always pointing to public-plugins/ensembl/conf/json/ if there is a config file for the given species stored in that directory?
None
None
=> check if there is a vcf config file first

modules/EnsEMBL/Web/Object/Variation.pm
None
This a bugfix. The LD icon on the variant page is switched on if the variant has LD populations and sample genotypes. There are cases where a variant has sample genotypes from HapMap and not 1000Genomes. However, we don't display HapMap LD plots anymore. The fix checks that for the LD populations there are the samples from those populations represented in the sample genotypes.
Variant summary page. Switched off [here](http://ves-hx2-76.ebi.ac.uk:5040/Homo_sapiens/Variation/Explore?db=core;r=19:39248014-39249015;v=rs368234815;vdb=variation;vf=143410401) and on [here](http://ves-hx2-76.ebi.ac.uk:5040/Homo_sapiens/Variation/Explore?db=core;r=19:39248014-39249014;v=rs11322783;vdb=variation;vf=142426185).
I'm slightly worried about how the fix affects speed. If I can rule out that the …
=> check pops against samples

modules/EnsEMBL/Web/Object/Variation.pm
-- Recently merged PR into [ensembl-variation/release/96](https://github.com/Ensembl/ensembl-variation/pull/331).
-- Setup of new ftp site with updated GERP files for release/96
-- [PR](https://github.com/Ensembl/public-plugins/pull/194) to public-plugins
As [discussed](https://github.com/Ensembl/public-plugins/pull/194) with @ens-ap5 : We want to generate the part of GERP file URL which contains the release number automatically. 
Variation summary page. GERP score displays on my [sandbox](http://ves-hx2-76.ebi.ac.uk:5040/Capra_hircus/Variation/Explore?r=17:60279944-60280944;v=rs666529295;vdb=variation;vf=8972194). However, I'm pointing to release-95 ftp which is why it is working on my sandbox already.
None
None
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-4943
=> Set GERP root file directory

modules/EnsEMBL/Web/Component/Variation/Summary.pm
Add link to the EVA study source for a variant in the variant summary panel.
All the pages from the Variant portal (Variant summary panel)
Example on my sandbox (end of the line `Original source`):
http://ves-hx2-76.ebi.ac.uk:5060/Chlorocebus_sabaeus/Variation/Population?v=11:6825247:G_A:PRJEB22989;vf=11:6825247:G_A:PRJEB22989
=> Add the EVA source link for variants coming from an EVA study

modules/EnsEMBL/Web/Component/Variation/Summary.pm, modules/EnsEMBL/Web/Object/Variation.pm
The Variant summary page currently makes ClinGen Allele Registry REST API calls to look up the Canonial Allele Identifier(CAid). The information is available in the variation database and is now looked up using the variation API
Variant …
=> Fetch ClinGen Allele Registry from database instead of REST call

modules/EnsEMBL/Web/Document/HTML/Compara/GeneTrees.pm, modules/EnsEMBL/Web/Hub.pm
We process polyploid genomes (wheat) in a particular way: instead of using the whole genome at once, we use the so-called "components" (A, B, D) as if they were distinct genomes. Some gene-tree stats views were not aware of this:
- http://plants.ensembl.org/prot_tree_stats.html displays the components *and* the whole genome, but there are no stats for the whole genome, thus displaying a tribute to Trivial Pursuit instead.
- http://plants.ensembl.org/prot_tree_stats.html?page=coverage#cladegroup1 is not aware that multiple GenomeDBs can thus have the same name when it sorts them by clade. Once fixed, the entry for the whole genome also has to be discarded as it has no stats attached to it.
Both views fixed on my sandbox:
- http://ves-hx2-77.ebi.ac.uk:5082/prot_tree_stats.html
- …
=> Various bugfixes for the gene-tree stats of polyploid genomes

modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm
This PR is to fix the popup error that appears when the Wasabi viewer is opened from the gene tree.
http://staging.ensembl.org/Homo_sapiens/Gene/Compara_Tree?db=core;g=ENSG00000148572;r=10:63133247-63155031
None
None
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5027
=> Unescape wasabi rest URL

modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm
This commit allows viewing the gene-tree page even if the Compara database doesn't have all the genomes.
I did that change locally a while ago, after trying to visualize our production gene-tree databases (which are missing either the mouse-strains or the non-murinae species) on my sandbox. Yesterday, @jyothishnt noticed that the same error happens on staging as the database is the e96 one (thus missing the e97 species). See http://staging.ensembl.org/Homo_sapiens/Gene/Compara_Tree?g=ENSG00000139618;r=13:32315086-32400266
Gene-tree view. Fixed on my sandbox: http://ves-hx2-77.ebi.ac.uk:5081/Homo_sapiens/Gene/Compara_Tree?g=ENSG00000139618;r=13:32315086-32400266 (note that the sandbox is using the same database as staging.ensemblorg)
As the page will now be displayed on staging, people may …
=> Be more careful as not all genomes are in the compara db

modules/EnsEMBL/Web/Query/Availability/Gene.pm
This PR is to fix the phenotypes count inconsistencies in the gene summary section. I have updated the code in the summary section to only count the associated phenotypes based on Gene and not on  HGNC.
http://www.ensembl.org/Homo_sapiens/Gene/Phenotype?db=core;g=ENSG00000173153;r=11:64305063-64317335;t=ENST00000405666
None
None
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-4979
=> [ENSWEB-4979] Gene phenotypes missing/reported incorrectly 

modules/EnsEMBL/Web/Component/Help/Biotypes.pm, modules/EnsEMBL/Web/ConfigPacker.pm, modules/EnsEMBL/Web/Document/HTML/Biotypes.pm
This PR replaces static html content of the [biotypes page](http://www.ensembl.org/info/genome/genebuild/biotypes.html) with the definitions retrieved from Ontology Lookup Service. The list of definitions is retrieved once, at the build time of the MULTI package, and then used when rendering the page. This is done in a similar way to how the [glossary page](http://www.ensembl.org/info/website/glossary.html) is displayed.
See related PR in the public-plugins repo: https://github.com/Ensembl/public-plugins/pull/208
[Biotypes page](http://www.ensembl.org/info/genome/genebuild/biotypes.html).
Screenshot of the updated page:
None that I am aware of.
https://www.ebi.ac.uk/panda/jira/projects/ENSWEB/issues/ENSWEB-4912
=> [ENSWEB-4912] Use data from Ontology Lookup Service for the biotypes page

modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm
This PR is to revert the commits from PR https://github.com/Ensembl/ensembl-webcode/pull/697.
It turns out the Wasabi viewer URL needs to be escaped to prevent the subtree_node_id from getting stripped off.
http://ves-hx2-76.ebi.ac.uk:42229/Homo_sapiens/Gene/Compara_Tree?db=core;g=ENSG00000148572;r=10:63133247-63155031
None
None
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5027
=> Escape wasabi viewer url to preserve subtree_node_id

modules/EnsEMBL/Web/Document/HTML/FTPtable.pm
Disable the VCF & GVF file links based on the meta key 'variation.source.vcf'.
http://www.ensembl.org/info/data/ftp/index.html
http://ves-hx2-76.ebi.ac.uk:42229/info/data/ftp/index.html
None
None
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5024
=> [ENSWEB-5024] Fix empty variation file dump dirs for vervet

modules/EnsEMBL/Web/Component/Variation/Explore.pm, modules/EnsEMBL/Web/Component/Variation/Summary.pm, modules/EnsEMBL/Web/Configuration/Variation.pm
Minor fixes to hide phenotype entries which are associated with variants that no longer map to the genome. 
The Variation/Phenotype pages.
This cause an issue because the Phenotype page is made available, but when you click on it, it's empty (mainly because the page is looking at the variation_feature, in case a variant maps to several locations).
Here is an example on my sandbox:
http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Variation/Explore?db=core;v=rs505922;vdb=variation
versus on the live website:
http://www.ensembl.org/Homo_sapiens/Variation/Explore?db=core;v=rs505922;vdb=variation
We are going to cleanup the phenotype_feature table in e98 to avoid this kind of issue in the future.
=> Hide phenotypes associated with non mapped variants

htdocs/components/05_DataTable.js, modules/EnsEMBL/Web/Document/Table.pm
Currently, if you change the columns of a data table that you want to view/hide, this configuration will be reset after a browser reload (see [example page in production](http://www.ensembl.org/Homo_sapiens/Gene/Matches?g=ENSG00000139618;r=13:32315474-32400266)). This got broken about a year ago (see, e.g. this configuration being correctly persisted for the transcript table on the [April 2018 archive site](http://apr2018.archive.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000139618;r=13:32315474-32400266))
There are two reasons why it is broken.
1) On the backend: [this pull request](https://github.com/Ensembl/ensembl-webcode/commit/e12769325ca37171366ac263d10baa5068727bf1) changed the variable used to pass hidden columns to the fronted for the one that was not using data …
=> Fix saving of datatable hidden columns

conf/ini-files/DEFAULTS.ini
Fix the LRG external links to point to the new URL on the (not so) new LRG website.
LRG portal, LRG track ZMenu.
Example of link: https://www.lrg-sequence.org/search/?query=LRG_1
=> Update LRG external links

modules/EnsEMBL/Web/ZMenu/Variation.pm
The variant coordinates built for the LOVD external links were wrong for `insertion` variants.
LOVD short variant ZMenus for Human on the ContingViewBottom panel (Region in detail)
=> Fix LOVD external links, which were wrong for the variant insertion type

modules/EnsEMBL/Web/Hub.pm
When you open a link from search result with url param db=otherfeatures and then go to Tools page, this param is carried across. It has no issues until a blast result link is clicked where db=core is needed.
So better to remove db param if accessing tools page which is not used in tools.
Only url change in Tools pages
Nothing I am aware of.
No
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5042
=> [ENSWEB-5042] remove db param from url for Tools

conf/ini-files/DEFAULTS.ini, modules/EnsEMBL/Web/Component/LRG/Summary.pm
Add a new url for the LRG website in order to fix the source link on the LRG summary panel.
See JIRA ticket https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5098
Example on my sandbox: http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/LRG/Summary?lrg=LRG_60
=> Fix external source link to the LRG website on the LRG summary panel

modules/EnsEMBL/Web/Component/Phenotype/RelatedConditions.pm
Change the link of the `Mapped ontology Term` to point to an Ensembl page (Phenotype/Locations) instead of an external page.
Also remove some unused column descriptions
Example on my sandbox:
http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Phenotype/RelatedConditions?db=core;oa=EFO:0004190
vs
live site: https://www.ensembl.org/Homo_sapiens/Phenotype/RelatedConditions?db=core;oa=EFO:0004190
=> Use internal links for ontology entries instead of external links

htdocs/components/15_ImageMap.js, htdocs/components/22_dynamic_content.css
Increased the max-width of the tooltip to prevent the species name getting displayed on multiple lines, creating a weird blinking effect of the tooltip.
http://test-plants.ensembl.org/Arabidopsis_thaliana/Location/Multi?db=core;r=1:10500-15500;r1=I:32986110-32996109:1;r2=KZ772744:980309-990308:1;s1=Theobroma_cacao;s2=Marchantia_polymorpha
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5084
=> Increase tooltip max width to prevent multiline bug

conf/ini-files/DEFAULTS.ini
Phenotypes are linked out to the original source. The OMIA source url has been updated in the variation db and requires also this update to the ini files.
sandbox url: http://ves-hx2-76.ebi.ac.uk:6080/Gallus_gallus/Phenotype/Locations?ph=338
staging url: http://staging.ensembl.org/Gallus_gallus/Phenotype/Locations?ph=338
e97 url: http://www.ensembl.org/Gallus_gallus/Phenotype/Locations?ph=338
_We appreciate this can be difficult but please highlight any views that you think might possibly be adversely affected by this …
=> Update OMIA phenotypes default url - e98

modules/EnsEMBL/Web/ZMenu/Genome.pm
Added `Alignment length` and `%id` to the zmenu of protein align features.
http://ves-hx2-76.ebi.ac.uk:42229/Homo_sapiens/Location/View?r=17:63992802-64038237
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-2615
=> Improve zmenu for protein align features

conf/ini-files/DEFAULTS.ini, modules/EnsEMBL/Web/Component/StructuralVariation/Phenotype.pm, modules/EnsEMBL/Web/Component/StructuralVariation/Summary.pm
- Add URL to the new SV data source for human (dbVar)
- Add phenotype links in the SV phenotype page, like we did for the Variation phenotype page
- StructuralVariation/Summary panel (dbVar source link)
- StructuralVariation/Phenotype page (phenotype links)
Example on my sandbox with `nsv1397926`:
http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/StructuralVariation/Phenotype?sv=nsv1397926
=> Update SV views to cope with new data source

conf/SiteDefs.pm, modules/EnsEMBL/Web/Component/Shared.pm
For some genes, the "About this gene" section of gene summary contains a link to protein families.
This link is now generated according to the same rule for both vertebrates and non-vertebrates sites; but in fact the rule should be slightly different. As a result, on non-vertebrates pages the link leads to a page with an error:
Gene page (gene summary, "about this gene" section)
fix on local sandbox: http://ves-hx2-76.ebi.ac.uk:8410/Magnaporthe_oryzae/Gene/Summary?db=core;g=MGG_01236;r=2:2789925-2792654;t=MGG_01236T0
This fix was tested on vertebrates and fungi sandboxes. Protists have the same url structure, so should be fixed with the change in this PR. I could not find genes with gene families for plants, bacteria, or metazoa.
GRCh37 plugin [does not seem to …
=> Fix gene families link for non-vertebrates sites

modules/EnsEMBL/Web/Component/Gene/GeneSummary.pm, modules/EnsEMBL/Web/Component/Transcript/TranscriptSummary.pm, modules/EnsEMBL/Web/Object/Gene.pm, modules/EnsEMBL/Web/Object/Transcript.pm
**Bug:** Currently, GeneSummary module expects a gene to always have a version number, which results in this Ensembl stable id for Saccharomyces (notice the dot in the end):
Currently, some of our components have code to generate the versioned stable id:
, although this functionality already exists in the Perl api of the objects that we are using:
This pull requests updates the code to rely on the parent objects to return the correct versioned stable id value. Also, hiding the Ensembl version field in Gene summary if Ensembl stable id does not have a version (as is done on Ensembl Genomes sites, e.g.: http://fungi.ensembl.org/Saccharomyces_cerevisiae/Gene/Summary?g=YDL168W;r=IV:159604-160764;t=YDL168W) 
**Note:** Shared.pm component has its own code to output stable id version of genes, …
=> Fix Ensembl version for Gene Summary

htdocs/components/15_ImageMap.js
**Bug:** While viewing a region, if a track is switched off, the highlighted region does not get updated.
**Steps to reproduce:** 
- visit http://www.ensembl.org/Homo_sapiens/Location/View?r=17%3A63992802-64038237
- make sure all tracks in the bottom image are turned on
- turn off a track that takes up a lot of vertical space (to better see the results); for example — Genes (Comprehensive set...)
- observe that the red box marking the region now extends past the bottom border of the image:
**Cause of the bug:** syntax error, combined with excessive javascript leniency and crazy type conversions. Apparently, an array can be compared with a number, and `[0] > 0 === false` (but `[1] > 0 === true`). It is the moment when one really wishes for typescript.
Location view …
=> Fix region highlighting after removal of a track

modules/EnsEMBL/Web/Component/StructuralVariation/Summary.pm
Fetch the ClinVar IDs from the ClinVar Structural Variation study (nstd102) and display them as alias
Structural Variation summary panel.
Example on my sandbox (nsv3916072 with 7 aliases):
http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/StructuralVariation/Explore?sv=nsv3916072
I also reformated the code of the method `get_alias`, to make it a bit more elegant.
=> Add the ClinVar IDs as alias for the ClinVar SV study

modules/EnsEMBL/Web/Document/HTML/Compara/MLSS.pm
The code was previously comparing species common / scientific names to find
out whether the alignment is a self-alignment. With strains those names
would be identical, so need to check the species-set size instead.
Was broken: http://staging.ensembl.org/info/genome/compara/mlss.html?mlss=1579
Now fixed: http://ves-hx2-77.ebi.ac.uk:5092/info/genome/compara/mlss.html?mlss=1579
Was _not_ broken (pairwise alignment): http://staging.ensembl.org/info/genome/compara/mlss.html?mlss=1037
Still working: http://ves-hx2-77.ebi.ac.uk:5092/info/genome/compara/mlss.html?mlss=1037
Was _not_ broken (self-alignment): http://staging.ensembl.org/info/genome/compara/mlss.html?mlss=739
Still working: http://ves-hx2-77.ebi.ac.uk:5092/info/genome/compara/mlss.html?mlss=739
None
On top of master …
=> ENSWEB-5247: bugfix: better detection of self-alignments

modules/EnsEMBL/Web/Document/Element/Acknowledgements.pm, modules/EnsEMBL/Web/ZMenu/StructuralVariation.pm
Fixed the issue with the menu not displaying the proper data.
Bio::EnsEMBL::Variation::StructuralVariationSample->individual was deprecated and removed in the following commit which caused this issue:
https://github.com/Ensembl/ensembl-variation/commit/b83934394c3c5b4bc252031576b7eeed1eb91336#diff-94790d4b956c63b792bb0639379da20eL233
Broken:
http://www.ensembl.org/Homo_sapiens/Location/View?r=12:118925-165410;db=core
Fixed:
http://debug.ensembl.org/Homo_sapiens/Location/View?r=12:118925-165410;db=core
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5254#
=> Fix SV- track ZMenu not refreshing - ENSWEB 5254

modules/EnsEMBL/Web/Document/HTML/FTPtable.pm
This PR is related to the changes made in the following PR: https://github.com/Ensembl/ensembl-webcode/pull/699
The meta key `variation.source.vcf` has been renamed to `variation_source.vcf` for this release (98).
http://ves-hx2-76.ebi.ac.uk:42228/info/data/ftp/index.html
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5149
=> Update variation meta key format for 'variation_source.vcf'

modules/EnsEMBL/Web/Controller/Psychic.pm
Fixes bug that can be reproduced by the following steps:
- go to home page of ensembl site
- from the dropdown box (in the centre of the screen), select a species (doesn't matter which)
- type "amelogenin" in the search box below
Observe that the search results come for panda (because the word "amelogenin" starts with the substring "amel", which is the short code for panda).
One possible solution is to update the regex in the Psychic module that assumes that if the beginning of a query matches any species present in a species hash, then it must be a query regarding this species. The updated regex will assume that if there is a species name in the query, it will be separated from the actual query by a space.
Search page.
Don't know
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5134
=> Update regex that guesses species from query in Psychic

conf/SiteDefs.pm, modules/EnsEMBL/Web/Component/Gene/FamilyProteins.pm
The Family proteins page for fungi shows "Download family alignment" button:
However, the actual attempt to download family alignment results in an error:
The reason for this is that we do not provide sequence alignments for non-vertebrates.
Family proteins (e.g., for fungi, http://fungi.ensembl.org/Multi/Family/Details?fm=MF_00505; for vertebrates: http://www.ensembl.org/Multi/Family/Details?fm=PTHR11289_SF0)
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5255
=> Show 'Download family alignment' button conditionally, using SiteDefs

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm
Orthologues tables should only display the strains from the same strain set. (Eg. Pigs should not show Mouse strains)
http://ves-hx2-76.ebi.ac.uk:42228/Mus_spretus/Gene/Strain_Compara_Ortholog?collapse=none;db=core;g=MGP_SPRETEiJ_G0031873;r=8:44062-175441
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5275
=> Hide strains from other species in the orthologues tables

modules/EnsEMBL/Web/Controller/Psychic.pm
Fixes bug with search from species page.
**Steps to reproduce the bug** (was introduced in release 98; can be seen on test site):
- go to species page (e.g. Mouse)
- click on the link to example gene
- (bug) the search results page will be empty
**Cause of bug:**
When generating redirect url for search page, Psychic adds incorrectly adds species common name as `facet_strain` parameter, e.g.:
`/mus_musculus/Search/Results?species=Mus_musculus;idx=;q=;facet_strain=Mouse;site=ensembl`
There was a guard in the code preventing generation of such urls, but when a metakey got renamed (in [this PR](https://github.com/Ensembl/ensembl-webcode/pull/728)), the guard stopped working.
**Solution:**
The code that adds the `facet_strain` parameter was added in [this …
=> Do not add facet_strain parameter to species search url in Psychic

modules/EnsEMBL/Web/ImageConfig.pm, modules/EnsEMBL/Web/ImageConfigExtension/Tracks.pm, modules/EnsEMBL/Web/ZMenu/CLS.pm, modules/EnsEMBL/Web/ZMenu/Gene/CLS.pm, modules/EnsEMBL/Web/ZMenu/Transcript/CLS.pm
Long reads tracks have different zmenu criteria and did not have a custom zmenu for them. CLS is the specified zmenu in webdata for these tracks, though they actually didn't exist in the code. So a CLS zmenu module was created for this. There is also a minor fix for the long reads menu entry and removing of track code that was separating the long reads tracks (as they are now separated using web data).
Control panel and long reads zmenu
Not sure
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5226
=> Add CLS zmenu for long reads tracks

modules/EnsEMBL/Web/ZMenu/AssemblyException.pm
Change url for the "What are assembly exceptions" link in zmenu.
Chromosome idiogram in /:species/Location/View
None that I can think of.
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5268
=> Change url for 'What are assembly exceptions' link in zmenu

conf/ini-files/COLOUR.ini
Added colour info for "long_read_nanopore" and "salmobase" to COULOUR.ini
"Region in detail view"
long_read_nanpore for Kakapo (nanopore track)
salmobase for Atlantic salmon (salmobase annotaiton import track)
=> Add colours for nanaopore long read and salmobase tracks

htdocs/components/05_DataTable.js, htdocs/components/85_spreadsheet_table.css, modules/EnsEMBL/Web/Component/VariationTable.pm
1. Add sticky headers for data tables. Data tables are wrapped in all sorts of wrappers that prevent use of a simple pure CSS solution for sticky headers; so the headers were made sticky using javascript. When the table that is higher than the window height is scrolled past the top border of the screen, the top row of column headings will still be visible at the top of the screen to make it easier to navigate the columns of the table.
2. Add sticky headers for new tables. This was done purely with CSS (`position: sticky; top: 0`). I tested that on a gene variant table, where the sticky header works fine. Won't work in browsers that do not support this CSS rule (e.g. in IE11).
- Any views containing data tables.
E.g.: http://ves-hx2-76.ebi.ac.uk:8410/Homo_sapiens/Gene/Phenotype?db=core;g=EN …
=> Add sticky headers to DataTables

htdocs/components/10_ZMenu.js
Fixes incorrect position of zmenu while it's being dragged.
**Steps to reproduce the bug**
- Open Chrome
- Open any page with an image that shows zmenu (for example, view of a human chromosome, or a detailed view of a region)
- Make sure to scroll the page down (the exact scroll distance is irrelevant, as long as the page is not exactly at the top)
- Click on the image to see a zmenu
- Drag the zmenu. You will see that it jumps down from your cursor (by the same distance that the page is scrolled down)
**Cause**
The current bug is result of several corrections:
1) [6 years ago](https://github.com/Ensembl/ensembl-webcode/commit/581c12020ee3b9d20ec013b5d57f409a3c4fb90b): `margin-top` and `top` css properties of zmenu were corrected when user started and stopped dragging. Without these …
=> Fix zmenu position

modules/EnsEMBL/Draw/GlyphSet/genetree.pm
A user recently reported some inconsistencies in the gene tree. This PR fixes those issues. The sandbox link is: http://ves-hx-78.ebi.ac.uk:8320/Homo_sapiens/Gene/Compara_Tree?db=core;g=ENSG00000175164;r=9:133250401-133276024.
The gene tree
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-4544
=> ENSWEB-4544: fix genetree inconsistencies

conf/httpd.conf, modules/EnsEMBL/Web/Apache/Handlers.pm
**Problem:** The 404 page is rendered when the apache handler dismisses the request.  At this point, apache re-routes the request to `/Error`, which is handled by the Apache::Error module (is it a good idea to re-route the request? probably not; but I'm not even attempting to touch this in this PR). As a result of this re-routing, the request object loses information about its initial uri; so the 404 page cannot behave differently depending on which page the user is coming from.
**Solution:** Add a custom header containing the original uri to the request object before dismissing it. This header can then be used to customise the 404 page depending on the requested url.
404 page
ENSWEB-5233
sandbox: http://ves-hx2-76.ebi.ac.uk:8430/
=> Preserve info about original uri when dismissing request

modules/EnsEMBL/Web/Object/Variation.pm
The ancestral allele used to be stored in the variation table. We moved the ancestral allele to the variation feature table and the API has been updated to return the ancestral allele for the variation_feature object. Trying to get it from the variation object has been deprecated and the API code for doing so has been removed now and added to the variation_feature object instead.
Variation summary page
The code update is necessary to work with ensemb-variation API release 100.
Tested on my [sandbox](http://ves-hx2-76.ebi.ac.uk:5040/Homo_sapiens/Variation/Mappings?db=core;r=6:33271592-33272592;v=rs17215231;vdb=variation;vf=63916212)
None
=> get ancestral allele from vf

modules/EnsEMBL/Web/Component/Transcript/ExternalRecordAlignment.pm
Fix alignment issue that became apparent with refseq sequences.
**Problem:**
when correct alignment would look like this:
**Cause:**
We [rely](https://github.com/Ensembl/ensembl-webcode/blob/2b4bc3ebab916797afb5a3dbe08d480f37d227a5/modules/EnsEMBL/Web/Object/Transcript.pm#L1429-L1430) on the `psw` (pairwise Smith-Waterman) script to perform alignments. 
When we align refseq sequence with the sequence of the transcript, the output currently looks as follows:
```
ENSP00000286100      MSLSENSVFAYESSVHSTNVLLSLNDQRKKDVLCDVTIFVEGQRFRAHR
MSLSENSVFAYESSVHSTNVLLSLNDQRKKDVLCDVTIFVEGQRFRAHR
NP_001177.1 1        MSLSENSVFAYESSVHSTNVLLSLNDQRKKDVLCDVTIFVEGQRFRAHR
ENSP00000286500      SVLAACSSYFHSRIVGQADGELNITLPEEVTVKGFEPLIQFAYTAKLIL
SVLAACSSYFHSRIVGQADGELNITLPEEVTVKGFEPLIQFAYTAKLIL
NP_001177.1 50 …
```
=> Fix munging of refseq alignment output

modules/EnsEMBL/Web/Component/Variation/Summary.pm
ClinVar RCVs  have been listed as variation synonyms. These have now been replaced with VCVs. RCVs will not be displayed as synonyms any more.
The variation summary page, 'Synonyms' 'ClinVar' source: 
http://ves-hx2-76.ebi.ac.uk:6080/Homo_sapiens/Variation/Explore?r=1:230709548-230710548;v=rs699;vdb=variation;vf=179
vs.
http://staging.ensembl.org/Homo_sapiens/Variation/Explore?r=1:230709548-230710548;v=rs699;vdb=variation;vf=179
None expected.
None.
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-1116
=> remove display ClinVar RCV as synonyms - e100

modules/EnsEMBL/Web/Apache/Handlers.pm
This PR is to fix the issue with redirection of links coming from ensemblgenomes.org
Sandbox: http://ves-hx2-76.ebi.ac.uk:42229/common/psychic?site=ensembl;genomic_unit=bacteria;x=0;y=0;q=ABQ19260
Prod: http://bacteria.ensembl.org/common/psychic?site=ensembl;genomic_unit=bacteria;x=0;y=0;q=ABQ19260
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5522
=> Update apache handler to handle 'common/psychic'

htdocs/components/25_ConfigMatrix.js
When configuring the RNASeq tracks, the numbers in the "tickboxes" are not correct. When not select it usually shows "0 1" and it shows "2 1" when selected. I would have expected "1 1" when the box is selected.
http://ves-hx2-76.ebi.ac.uk:42229/Homo_sapiens/Gene/Summary?g=ENSG00000139618;r=13:32315086-32400266
Configure this page -> RNASeq models
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5406
=> Fix ConfigMatrix incorrect numbers bug

htdocs/components/99_announcement_banner.css, modules/EnsEMBL/Web/Document/Element/TmpMessage.pm, modules/EnsEMBL/Web/Template/Legacy.pm
Added the option to display an announcement banner by adding a file to the tmp directory.
Steps to add the banner:
- Look for the ENSEMBL_TMP_MESSAGE_FILE in the SiteDefs and get the path.
- Create (if not exists) the file `ensembl_tmp_message` in the above path
- add an entry for `banner_message`.
- For example: `banner_message Hello World!` will display `Hello World!` inside the banner
Masthead
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5494
=> Add option to display announcement banner

modules/EnsEMBL/Web/Object/Variation.pm
Fetching the ancestral allele from the variation feature throws an error on staging.  
Before fetching the ancestral allele we need to check if the variant has any variation feature. 
Variation summary page
Tested on my [sandbox](http://ves-hx2-76.ebi.ac.uk:7040/Mus_musculus/Variation/Explore?db=core;v=rs2020807;vdb=variation)
Fix is necessary to work with API release 100. 
None
=> Check if variation feature is defined

modules/EnsEMBL/Web/Component/Variation/Summary.pm
Update CSS to wrap VCF sequences for long alleles.
Variation summary.
Before fix (notice the sequence in the Location field is cropped by the right edge of the viewport):
After fix (notice the sequence in the Location field wraps when it reaches the edge of the viewport):
Sandbox: http://ves-hx2-76.ebi.ac.uk:8410/Homo_sapiens/Variation/Explore?r=18:5307973-5309186;v=rs1567915543;vdb=variation;vf=456734367
🤷‍♂ 
ENSWEB-5582
=> Wrap long variation sequences

modules/EnsEMBL/Web/Apache/Handlers.pm
Updated the Apache handlers to handle incoming ID lookups redirects from ensemblgenomes.org.
I've made an update so that the `q` parameter form any URL matching the path `/common/psychic` will be considered as a stable ID and will be handled by the sub `stable_id_redirect_uri` present in `Handlers.pm`.
Prod:
http://plants.ensembl.org/common/psychic?site=ensembl;genomic_unit=plants;x=0;y=0;q=AT3G52430.1
Sandbox:
http://ves-hx2-76.ebi.ac.uk:42229/common/psychic?site=ensembl;genomic_unit=plants;x=0;y=0;q=AT3G52430.1
I am not very sure if this is the intended behaviour but the path `/common/psychic` doesn't seem to be handled elsewhere .
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5535
=> Handle ID lookup redirects from ensemblgenomes.org

htdocs/components/99_announcement_banner.css
Updated the announcement banner colour scheme to match the banner on the fallback site.
Current view:
http://uswest.ensembl.org/
Updated view:
http://ves-hx2-76.ebi.ac.uk:42228/index.html
=> Uopdate banner colours to match fallback

utils/indexing/indexXMLDumper
Non specified phenotypes are now tagged with the class_attrib_id 663 and this PR updates the search query to exclude them from the phenotype search creation.
Phenotype search page will not return any results for 'Clinvar: phenotype not specified'.
[Phenotype search ](http://www.ensembl.org/Multi/Search/Results?q=Clinvar%3A%20phenotype%20not%20specified;site=ensembl)
[Phenotype link out](http://www.ensembl.org/Homo_sapiens/Phenotype/Locations?db=core;name=ClinVar:%20phenotype%20not%20specified;ph=74869;r=1:230709548-230710548;v=rs699;vdb=variation;vf=179)
None.
None.
[ENSVAR-2926](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2926)
=> update phenotype sql to exclude non_specified

modules/EnsEMBL/Web/Component/Variation/Summary.pm
None
We started having problems retrieving files from the FTP site. This is still a problem for [staging](http://staging.ensembl.org/Homo_sapiens/Variation/Explore?r=1:230709548-230710548;v=rs699;vdb=variation;vf=179). The error message doesn't appear anymore on the page after applying the PR [[my sandbox](http://ves-hx2-76.ebi.ac.uk:5040/Homo_sapiens/Variation/Explore?r=1:230709548-230710548;v=rs699;vdb=variation;vf=179)].
For the release 99 page we changed a die to a warning message [[merged PR](https://github.com/Ensembl/ensembl-variation/pull/556)]. We are planning to revert the API update and also provide a web code update. It is likely that users will run an analysis with the API code and only after will notice the warning message about the FTP site problem. 
Variant summary page …
=> add eval around gerp score retrieval

modules/EnsEMBL/Web/Object/Variation.pm
Use a new variable (defined in [this PR](https://github.com/Ensembl/public-plugins/pull/320) in public plugins) to access variation files stored on the ftp server using http protocol rather than ftp.
The reasons for doing so are as follows:
- there is a firewall on web machines, which the FTP client was unaware of; so it currently can't retrieve ftp files
- even without the firewall problem, http protocol is more resilient than ftp, so it should be preferred
All Variation-related views that use variation files stored on the ftp server. 
See e.g. a SNP page on [sandbox](http://ves-hx2-76.ebi.ac.uk:8410/Homo_sapiens/Variation/Explore?r=1:230709548-230710548;v=rs699;vdb=variation;vf=179), where the GERP scor in the "Change tolerance"
line is retrieved from ftp (compare it with the same page …
=> Use ENSEMBL_FTP_OVER_HTTP_URL variable

utils/indexing/indexXMLDumper
While doing SOLR XML for e100, the family xml generation was extremely slow. It took 7 days to generate files for 88 species (out of 286 ones)
It was due to the fact that we run the same expensive query for each species.
This PR is to cache the result of that big query in memory, and thus making actual database query only once.
Family XML for all species has been generated in 15 hours.
Max memory usage: less than 750 MB
=> Cache result for an expensive query for Family xml

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm
Turns out, the Compara team wants to remove the dN/dS data from their database, which makes the dN/dS column in the orthologs table redundant. This PR removes this column.
Orthologs table in /:species/Gene/Compara_Ortholog
Sandbox: http://ves-hx2-76.ebi.ac.uk:8410/Homo_sapiens/Gene/Compara_Ortholog?db=core;g=ENSG00000139618;r=13:32315086-32400266;t=ENST00000380152
🤷‍♂
ENSWEB-5457
=> Remove dN/dS column from Compara orthologues table

conf/ini-files/COLOUR.ini
Added the following missing colour entries as instructed by Jyo:
- aligned_transcript = #86a2b9         Long read gene
- cdna = chartreuse3;join:darkolivegreen1
- transposable_element = blue  transposable element gene
- vault_rna = plum4;section:npc           RNA gene
- cdna_update = chartreuse3;join:darkolivegreen1
- ccds_gene = chartreuse3;join:darkolivegreen1
- ccds_import = chartreuse3;section:pc     CCDS set
The following entry is ignored as the key is already define with a different value:
- est = chartreuse3;join:darkolivegreen1
https://www.ebi.ac.uk/panda/jira/browse/ENSWEBREL-745
=> Add the missing colours

htdocs/components/25_ConfigTrackHubMatrixForm.js, htdocs/components/91_config_matrix.css
Adding reset all functionality for track selection (first panel) for Trackhub. When clicking the reset all, it should reset the track selection with the initial selection that is first time the interface was opened based on the values set in the trackhub file.
New trackhub matrix interface
None
None
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5577
=> ENSWEB-5577: Changing reset all functionality for track selection

modules/EnsEMBL/Web/Utils/TrackHub.pm
Hotfix for datahubs. Particularly high-priority because of forthcoming covid-site release.
Added multiple reviewers just prospectively. Feel free to look if you have the time, but don't feel obliged!
This fixes part of the problem with trackhub attachment for e100.
If bad data gets into the cache such that a cache get fails, then the get is retried without the cache. This limits the scope of cache get failures to the period when requests fail. The cache is populated in either case so if the request now succeeds the cache will be corrected.
A downside is that deleted datahubs will be contacted each time a page is loaded in-case they have sprung into life.
Region in detail (wiuth tracks attached)
See Description section, last para.
None envisaged.
None. Came through on slack from Jane.
=> Retreat to non-cache hub add if hub contains nonsense.

modules/EnsEMBL/Web/Component/Info/HomePage.pm
Hide gene tree when NO_COMPARA is set to 1.
http://ves-hx2-76.ebi.ac.uk:42227/Sars_cov_2/Info/Index?db=core;g=ENSSASG00005000003;r=MN908947.3:266-13483;t=ENSSAST00005000003
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5709
=> Hide gene tree when NO_COMPARA

modules/EnsEMBL/Web/Component/Variation/Publication.pm
Add a new column to the variant page to display citation sources. 
New column in variation/publication.pm
Sandbox: http://ves-hx2-76.ebi.ac.uk:7040/Homo_sapiens/Variation/Citations?db=core;r=1:161629403-161630403;v=rs448740;vdb=variation
Updated branch before making any change. 
ENSVAR-2709
=> Display citation sources

htdocs/components/10_Content.js, htdocs/components/15_PopulationGraph.js
Note the bug depends on the state of the browser (probably cookies, although I have not investigated this further)
-  Visit http://www.ensembl.org/Homo_sapiens/Variation/Population?db=core;r=1:230709548-230710548;v=rs699;vdb=variation;vf=179
- Clear site data for ensembl.org (in Chrome: open dev tools > Application > Clear site data)
- Refresh the page (make sure that there is no hash value in the end of the url)
- You should see population charts:
- Open one of the sub-populations
- Refresh the page again
- The charts will likely stop rendering
If the browser does not have certain values preserved in its state (🤷‍♂️) then loading the page will trigger the `toggleable` function in Content.js, which will [simulate click](https://github.com/Ensembl/ensembl-webcode/blob/release/100/htdocs/com …
=> Fix population graphs

conf/ini-files/DEFAULTS.ini, modules/EnsEMBL/Web/Component/Variation/Summary.pm
At least two places link out to ClinVar requiring two different URLs: variation synonyms section and phenotype data source column.
This PR is to fix it the broken source column ClinVar link out without breaking the synonyms link out.
Variation summary section, phenotype data source column and all views that contain it.
Phenotype data table -> source column ->  ClinVar link out:
- Broken link: http://staging.ensembl.org/Homo_sapiens/Variation/Phenotype?r=1:230709548-230710548;v=rs699;vdb=variation;vf=179
- Fixed: http://ves-hx2-76.ebi.ac.uk:6080/Homo_sapiens/Variation/Phenotype?r=1:230709548-230710548;v=rs699;vdb=variation;vf=179
None expected.
None.
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3252
=> fix clinvar phenotype source

conf/SiteDefs.pm, modules/EnsEMBL/Web/SpeciesDefs.pm
Species selector not adding species to its proper clade.
Reason is that it SPECIES_IMAGE_DIR is not set. This was added for RR site and is undef for the current site there by not setting the SPECIES_IMAGE variable.
Species selector in BLAST, Alignments and AlignSlice
Need to check why $config_packer->tree->{ASEEMBLY_VERSION} is not available here https://github.com/Ensembl/ensembl-webcode/compare/hotfix-sp-selector?expand=1#diff-93e79820da11cca1db9ee8ce3e7b1811L899
We will have to cherry pick this to master branch because I couldn't do it in postreleasefix/100 branch as this RR SPECIES_IMAGE addition commit is only available in master and release/100. This created a fix for release/100
No
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5873
=> fix species selector bug due to recent changes in SpeciesDefs

modules/EnsEMBL/Web/Component/Shared.pm
Currently, the 'RefSeq Match' tooltip content is hard coded. This PR retrieves it from Ensembl glossary.
Gene summary -> Transcripts table
[ENSWEB-5878](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5878)
=> Retrieve 'RefSeq Match' tooltip from ensembl glossary

modules/EnsEMBL/Web/Component/Gene/GenePhenotype.pm, modules/EnsEMBL/Web/Component/Gene/GenePhenotypeOrthologue.pm, modules/EnsEMBL/Web/Component/Gene/GenePhenotypeVariation.pm, modules/EnsEMBL/Web/Component/StructuralVariation/Phenotype.pm, modules/EnsEMBL/Web/Component/Variation/Phenotype.pm
Listed phenotypes link out to a view displaying all loci with this phenotypes. This link should be removed for the phenotypes that are of type 'non_specified'.
Gene, variation, structural variation phenotypes view.
example phenotype: "ClinVar: phenotype not specified"
Gene phenotypes view:
- e100: http://www.ensembl.org/Homo_sapiens/Gene/Phenotype?db=core;g=ENSG00000182372;r=8:1755778-1801711;source=dbSNP;v=rs184988046;vdb=variation;vf=144518072
- e101: http://ves-hx2-76.ebi.ac.uk:6080/Homo_sapiens/Gene/Phenotype?db=core;g …
=> Remove link out for non specified phenotypes

conf/ini-files/MULTI.ini, modules/EnsEMBL/Web/Controller/Ajax.pm, modules/EnsEMBL/Web/DBSQL/GeneStableIDAdaptor.pm, modules/EnsEMBL/Web/Tools/Registry.pm
******* IMPORTANT NOTE: This PR is for e101 *******
Created a separate database for the gene_autocomplete table called `ensembl_autocomplete_100` and removed it from `ensembl_website`
Sandbox URL:
http://ves-hx2-76.ebi.ac.uk:42229/Homo_sapiens/Location/View?r=7:116210506-116258783;g=ENSG00000135269;db=core
http://ves-hx2-76.ebi.ac.uk:42229/Homo_sapiens/Ajax/autocomplete?q=BRCA
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5366
=> Remove gene_autocomplete table from ensembl_website database

modules/EnsEMBL/Web/JSONServer/SpeciesSelector/Compara_Alignments.pm
Fix of a bug in Compara species selector panel.
The bug presents as follows (notice no strain name in the list of mouse species):
While this is what is expected (currently in production for e100):
The code in the compara module uses the "common name" of a species rather than its "display name":
```
$t_child->{title}      = encode_entities($ancestral ? '--Ancestral_sequences--' : $species_info->{$url_name}->{common});
```
`$species_info->{$url_name}->{common});` refers to [this line](https://github.com/Ensembl/ensembl-webcode/blob/release/100/modules/EnsEMBL/Web/Hub.pm#L354) in Hub:
```
'common'            => $species_defs->get_config($_, 'SPECIES_COMMON_NAME'),
```
In ConfigPacker for release 100, "SPECIES_COMMON_NAME" field was populated with the value of `species.display_name` meta key …
=> Use correct speciesdefs property in compara alignments species selector

modules/EnsEMBL/Web/ImageConfig/generegview.pm
The PR fixes an incorrect DOI in the description popup for the eQTL track,
(see [http://www.ensembl.org/Homo_sapiens/Gene/Regulation?db=core;g=ENSG00000248746;r=11:66546395-66563334](http://www.ensembl.org/Homo_sapiens/Gene/Regulation?db=core;g=ENSG00000248746;r=11:66546395-66563334)), and converts the DOI and PMID into links.
Helptext popup for eQTL track.
Should be none. Text fix only.
None.
[https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5896](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5896)
=> Update the helptext for the eQTL track popup

modules/EnsEMBL/Web/Object/Gene.pm
Method changed to receive stable_id passed as argument
This is a work related to the pan compara page. But no views will be affected by this change. This is related to a PR in eg-web-common.
N/A
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5635
=> Receive stable id as argument

htdocs/info/website/upload/index.html, modules/EnsEMBL/Web/Component/UserData.pm
Fix some links that got broken outdated after the refactoring in [this commit](https://github.com/Ensembl/ensembl-webcode/commit/0ca6abecd7efffd8da223e7e93b702a3f91c7e4d). 
- on [Adding Custom Tracks page](http://www.ensembl.org/info/website/upload/index.html): links "How to add track hubs" and  "TrackHubs with multiWigs"
- in the Custom Tracks popup, Personal Data tab, link to "support page":
http://ves-hx2-76.ebi.ac.uk:8410/
There is a link to the page that was deleted in [this commit](https://github.com/Ensembl/ensembl-webcode/commit/0ca6abecd7efffd8da223e7e93b702a3f91c7e4d) on the [Adding Track Hubs to Ensembl page](http://www.ensembl.org/info/website/trackhubs/adding_trackhubs.html) (link text: "search the Trackhub registry itself"). What should we do with it?
=> Fix links to trackhub help pages

conf/ini-files/DEFAULTS.ini, modules/EnsEMBL/Web/Component/Variation.pm, modules/EnsEMBL/Web/Component/Variation/PopulationGenotypes.pm
NCBI ALFA frequency data from VCF  has been included in population genetics pages for release/102
A description of the populations and terms of use  for this new data is needed for release/102
The links have been added to DEFAULTS.ini. The population url is similar to that done for 1000Genomes.
New code to include "Terms of use"
Population Genetics view - At the bottom of the table for NCBI ALFA
http://ves-hx2-76.ebi.ac.uk:5050/Homo_sapiens/Variation/Population?db=core;r=1:230709548-230710548;v=rs699;vdb=variation;vf=179#ncbialfa_anchor
None identified as conditions are for ALFA NCBI
Tested  on sandbox, branched from master.
ENSVAR-3485 - ALFA usage
ENSVAR-3340 - Adding ALFA data
=> Add links for NCBI ALFA pops and terms of use.

modules/EnsEMBL/Web/Component/Shared.pm
@ens-ma7 's explained the cause of this issue in the related Jira ticket:
_Since we moved the help system to using the EBI glossary (https://www.ebi.ac.uk/ols/api/ontologies/ensemblglossary/terms?size=500 ), the key for retrieving the help content for TSL has changed. Instead of TSL:1 it is now "TSL 1" and for TSL it is "Transcript support level"._
Transcript table TSL popup: …
=> Fix TSL popup issue on transcript table.

conf/SiteDefs.pm
This PR is to fix the error displayed in the following page:
http://www.ensembl.org/Mus_musculus/Location/Compara_Alignments/Image?align=835;db=core;r=4%3A136366473-136547301;time=1596020339619.619
I have increased the PERL_RLIMIT_AS value from `2048` to `2560` to fix this issue.
Temporarily fixed this on staging:
http://staging.ensembl.org/Mus_musculus/Location/Compara_Alignments/Image?align=835;db=core;r=4%3A136366473-136547301;time=1596020339619.619
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5908
=> Fix cactus alignment - out of memory error

htdocs/components/25_ConfigRegMatrixForm.js
The 'Configure trackhub display' button did not work as intended. Instead of showing the 'View tracks' section in the regulation matrix modal, it closes it. This makes it unable for the user to edit the trackhub display as necessary after selecting the tracks.
102
Regulation matrix
Don't think there are any as this fix should affect only the regulation matrix.
[ENSWEB-5740](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5740)
=> Fix broken 'configure trackhub display' button

htdocs/components/99_announcement_banner.css, modules/EnsEMBL/Web/Document/Element/TmpMessage.pm, modules/EnsEMBL/Web/Template/Legacy.pm
This PR adds an announcement banner to the page header. It's essentially a duplicate of an [old PR](https://github.com/Ensembl/ensembl-webcode/pull/753), which merged a feature branch with the same functionality into postreleasefix/99. 
Masthead
[ENSWEB-5907](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5907)
=> Retrofit announcement banner

utils/solr_replication.sh
The output of `solr_replication.sh` includes a comment that prints a `screen` command. The command uses the `-s` option (lowercase "S"), which is used to set the shell in the new session. Instead, it should use the `-S` option (capital "S"), which is for naming the new session. This PR changes `-s` to `-S`.
NA
NA
None
None
=> Fix option on screen command

modules/EnsEMBL/Web/Component/Shared.pm
Fixe the popup issue on the transcript table which TSL and APPRIS types were missing from the help popup.
http://www.ensembl.org/Homo_sapiens/Gene/Summary?g=ENSG00000139618;r=13:32315086-32400268
http://ves-hx2-76.ebi.ac.uk:8786/Homo_sapiens/Gene/Summary?g=ENSG00000139618;r=13:32315086-32400268
_ 
_
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5684
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6026
=> Fix TSL and APPRIS type description in popup.

htdocs/components/25_ConfigRegMatrixForm.js, htdocs/components/25_ConfigTrackHubMatrixForm.js
The popup for a regulation matrix cell doesn't move when the whole matrix is scrolled horizontally. This positions it in a different cell which can confuse the user. I have made the popup to hide when horizontally scrolling the matrix.
102
Regulation matrix
Since the popup gets hidden when scrolling horizontally, this could result in a bad user experience.
[ENSWEB-5058](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5058)
=> Hide regulation matrix on scroll

conf/ini-files/DEFAULTS.ini, modules/EnsEMBL/Web/Component/Gene/GeneSummary.pm, modules/EnsEMBL/Web/Component/Shared.pm
- Renamed the column name to `UniProt Match`
- `UniProt Match` column will no display the informs if they exist and shows the gene level links if not.
- Added external link entry to DEFAULTS.ini to `UNIPROT_ISOFORM`
http://ves-hx2-75.ebi.ac.uk:42228/Homo_sapiens/Gene/Summary?g=ENSG00000159840;r=7:143381295-143391111
http://ves-hx2-75.ebi.ac.uk:42228/Homo_sapiens/Gene/Matches?g=ENSG00000159840;r=7:143381295-143391111
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5877
=> Update transcript table to display uniprot isoform

modules/EnsEMBL/Web/Component/Variation/PopulationGenotypes.pm
Update of tooltip to cover * allele (alleles missing due to overlapping deletions)
VCFs can include * alleles (allele missing due to overlapping deletion)
Tooltip updated to include these alleles
Population Genetics view - info button. When allele is in VCF but not one of alleles of variant definition
See GEM-J frequency, click info buttons 
http://ves-hx2-76.ebi.ac.uk:5050/Homo_sapiens/Variation/Population?db=core;r=1:8044972-8045972;v=rs1293885450;vdb=variation;vf=507101856#gem-j_anchor
None, a documentation change
Tested on sandbox, branched from master
ENSVAR-3769 - Update Web frequency tooltip for variant alleles only in VCF
=> Update tooltip to include * alleles (overlapping deletion)

conf/ini-files/DEFAULTS.ini, modules/EnsEMBL/Web/Component/Variation.pm, modules/EnsEMBL/Web/Component/Variation/PopulationGenotypes.pm
GEM-J frequency data from VCF hs been included in the population genetics page for release/103
A description of the populations and terrms of use for this new data is needed for release/103
The links have been added to DEFAULTS.ini
The code changes for population url and terms of use is similar to that done for NCBI ALFA #785 
Population Genetics view - At the bottom of the table for GEM-J
http://ves-hx2-76.ebi.ac.uk:5050/Homo_sapiens/Variation/Population?db=core;r=1:230709548-230710548;v=rs699;vdb=variation;vf=179#gem-j_anchor
None identified as conditions are for GEM-J
Tested on sandbox, branched from master
ENSINT-520   New human frequency data GEM-J
ENSVAR-3413 Integrate GEM-J
ENSVAR-3771 GEM-J Add terms of use
=> Add links for GEM-J pops and terms of use

modules/EnsEMBL/Web/Component/Shared.pm
During sandbox web server testing, I came across a call to the deprecated (and removed) method `get_total_length`, which is currently in use at `ensembl-webcode/modules/EnsEMBL/Web/Component/Shared.pm`. This PR replaces the call to this method with the recommended replacement method, `get_ref_length`.
I came across this when my test web server consistently failed to load the Whole Genome Display web …
=> Replace deprecated method with get_ref_length

conf/ini-files/DEFAULTS.ini
Add PharmGKB external URL to be used in web VEP e103.
None
None
None
None
=> Add  PharmGKB URL

modules/EnsEMBL/Web/Object/Gene.pm
(Supersedes #791)
Downloading data (with "Download orthologues" button) from the Strains' Orthologues view currently returns the orthologues of the main species set, not of the strains. This PR is to fix that and return the orthologues of the strains instead.
- The definition of `my $strain_tree` is inspired from https://github.com/Ensembl/ensembl-webcode/blob/release/102/modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm#L41 . It seems to work with just the test of `$hub->param('data_action')` and I don't know if the rest (`|| $self->hub->species_defs->IS_STRAIN_OF || $self->hub->param('strain')`) would be needed too.
- I have made the function call the existing `get_compara_Member` and `get_GeneTree` to avoid duplicating code / functionality. It looks like these two functions cache the …
=> Fix strain orthologues downloads

modules/EnsEMBL/Web/Component/Info/VariationGallery.pm, modules/EnsEMBL/Web/Component/Variation/Explore.pm, modules/EnsEMBL/Web/Configuration/Variation.pm, modules/EnsEMBL/Web/Object/Variation.pm
The phylogenetic context view is broken for species with their main data source being VCF which are Atlantic salmon and vervet. After spending time to investigate the cause I could only confirm that it is related to API code which deals with VCF variants and only affects the two mentioned species. There is not enough time to investigate further which is why we decided to disable the view for the two …
=> add option to disable phylogentic view

modules/EnsEMBL/Web/ImageConfig/generegview.pm
Updated the track info from:
"Complete set of eQTL correlation statistics as computed by the GTEx consortium on<platelet> samples. Provided to Ensembl by the EBI eQTL catalog. The GTEx Consortium. Science. 8 May 2015: Vol 348 no. 6235 pp 648-660. DOI: 10.1126/science.1262110. PMID: 25954001"
To:
"Complete set of eQTL correlation statistics as computed on <platelet> samples. Provided to Ensembl by the EBI eQTL catalog (www.ebi.ac.uk/eqtl)"
http://ves-hx2-75.ebi.ac.uk:42229/Homo_sapiens/Gene/Regulation?g=ENSG00000139618;r=13:32315086-32400268
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6116
=> Update eQTL track info text

modules/EnsEMBL/Web/ViewConfig/Gene/ComparaTree.pm, modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm
Mice supertrees are now available and thus we need to remove the hack we used to hide the supertrees option in configuration.
Genetrees in general as there is a change in "Switch to supertree url" link in the supertree zmenu
Check it in sandbox:
Strain: 
http://ves-hx-78.ebi.ac.uk:9000/Mus_musculus_129S1_SvImJ/Gene/Strain_Compara_Tree?g=MGP_129S1SvImJ_G0016104;r=1:65277845-65279914;t=MGP_129S1SvImJ_T0020282
Breed:
http://ves-hx-78.ebi.ac.uk:9000/Sus_scrofa_bamei/Gene/Strain_Compara_Tree?g=ENSSSCG00050037595;r=LUXV01057655.1:1521438-1532941
N/A
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5419?filter=-1
=> [ENSWEB-5419] Enable supertrees for mice strains

modules/EnsEMBL/Web/Component/Variation/Summary.pm
Convert the URL with `uri_unescape` instead of manually replacing the characters. 
Variation synonyms on the variant summary page.
Sandbox: http://ves-hx2-76.ebi.ac.uk:7040/Homo_sapiens/Variation/Explore?db=core;r=1:230709548-230710548;v=rs699;vdb=variation;vf=94 
None
No conflicts
ENSVAR-3882
=> Variation summary page - uri escape

modules/EnsEMBL/Web/Apache/Handlers.pm
TextSequence race possible on all species: common in Basenji.
Initialise randomness in each thread.
Manifests as broken or never loading textsequences.
Text sequences.
Look out for broken text sequences leading to missing or duplicated blocks of sequence, particularly on pages (if any exist) with multiple, independent sequences on the page. No real reason to suspect this will happen, but that's the general area this fix is within.
These kinds of issues are also a likely effect of the original bug and are likely to not be reliably reproducible.
I'm not an expert on this area of code but I don't know who is these days.
None
@Ben-Ensembl on slack.
=> Initialise randomness for each worker thread.

modules/EnsEMBL/Web/ZMenu/Gene.pm
Fixed the issue with the genes in upper pane that are not linkable. As per the code before this change, the stableId does not getting displayed when the gene description is missing which I think shouldn't be the case.
http://ves-hx2-75.ebi.ac.uk:42228/Camarhynchus_parvulus_GCA_902806625.1/Location/Overview?db=core;r=2:1-152240728;region=2
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6141
=> Fix genes in upper pane that are not linkable

conf/httpd.conf
- Added the code back to disable tools on mirrors using the following commits:
-- https://github.com/Ensembl/ensembl-webcode/commit/03bab3dc#diff-67c427902d6bb8985d728ab4d2f1ec075564d3f61960969f4777e33ba1f914a7R108
-- https://github.com/Ensembl/ebi-plugins/commit/b5b7fa2d16a79cee89f1476652727a2a5c22157d
- To disable, we need to create the file `tools_down` in the location: `/nfs/services/nobackup/ensweb/` on the mirrors.
**NOTE:** This needs to be merged along with the following PR:
https://github.com/Ensembl/ebi-plugins/pull/80
http://ves-hx2-75.ebi.ac.uk:42229/info/docs/tools/index.html
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5595
=> Add option to disable tools on mirrors

modules/EnsEMBL/Web/Document/HTML/FTPtable.pm
Bug fixes for the FTP downloads page:
- Fixed the broken link for MySQL dumps.
- Removed dead variation file links for species that don't have these files (VCF/GVF column in the FTP table).
- Fixed a broken HTML tag.
Affects both V and NV version of the FTP downloads page.
V: http://wp-np2-1d.ebi.ac.uk:1610/info/data/ftp/index.html
NV (plants): http://wp-np2-1d.ebi.ac.uk:1620/info/data/ftp/index.html
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6021
=> Bugfix: broken links in FTP table

modules/EnsEMBL/Web/ImageConfig/gene_summary.pm
That the graphical representation of the gene transcripts in the gene summary page, cannot be scrolled (using the "Drag/Scroll to a region" option). The view never updates after dragging
http://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000135960;r=2:108894471-108989372
http://ves-hx2-75.ebi.ac.uk:8790/Homo_sapiens/Gene/Summary?g=ENSG00000139618;r=13:32336210-32441392;db=core
There's a …
=> Update configuration to disable image scrolling in gene summary page.

modules/EnsEMBL/Web/Component/Regulation/Evidence.pm, modules/EnsEMBL/Web/Component/Variation/Mappings.pm, modules/EnsEMBL/Web/Factory/Feature.pm, modules/EnsEMBL/Web/Object/Experiment.pm, modules/EnsEMBL/Web/Object/Slice.pm, modules/EnsEMBL/Web/Object/Transcript.pm, modules/EnsEMBL/Web/ZMenu/FeatureEvidence.pm
This bugfix updates the deprecated methods from Ensembl Regulation (Funcgen) API that are used in webcode and listed for removal in 104:
https://github.com/Ensembl/ensembl-funcgen/blob/release/104/DEPRECATED.md
New method names sourced from the API documentation: http://www.ensembl.org/info/docs/Doxygen/funcgen-api/annotated.html
Example URLs using the affected methods: 
- http://wp-np2-1d.ebi.ac.uk:1610/Homo_sapiens/Transcript/Oligos?db=core;g=ENSG00000128573;r=7:114414997-114693768;t=ENST00000403559
- http://wp-np2-1d.ebi.ac.uk:1610/Homo_sapiens/Regulation/Evidence?db=funcgen;fdb=funcgen;r=13:32313600-32318001;rf=ENSR00000060894
- http://wp-np2-1d.ebi.ac.uk:1620/Zea_mays/Transcript/Oligos?db=core;g=Zm00001eb113460;r=2:230473563-230476257;t=Zm00001eb113460_T001 …
=> Bugfix: update deprecated Ensembl FuncGen API methods

modules/EnsEMBL/Web/Component/Shared.pm
Modifications to the transcripts table (in gene summary and transcripts page):
- Added flag for canonical transcripts
- Updated flag order (see the ticket)
- Reordered transcripts (move canonical to the top)
- Some code refactoring
Example sandbox URLs:
- Long transcript table: http://wp-np2-1d.ebi.ac.uk:1610/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000198947;r=X:31097677-33339609
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6094
=> Update transcript table

htdocs/info/about/publications.html
This PR will add the the [Ensembl 2021 paper](https://doi.org/10.1093/nar/gkaa942) to the citations list in the publications page.
- Current site: https://www.ensembl.org/info/about/publications.html
- Sandbox: http://wp-np2-1d.ebi.ac.uk:1610/info/about/publications.html
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6191
=> Add Ensembl 2021 publication

modules/EnsEMBL/Web/Query/Generic/Base.pm
This PR is related to one in ebi-plugins. So Both should be merged together.
Precache runs for a set of species and this should be configurable in Sitedefs.
N/A
There shouldn't be any complications as this is used only for precache run.
N/A
No JIRA unfortunately.
=> move precache default species to precache plugin Sitedefs

htdocs/components/15_ComparaAlignSliceSelector.js, modules/EnsEMBL/Web/Command/DataExport/Output.pm
Alignment ID for compara alignments view is stored in sessions. It used to be passed in the url as param "align" before we implemented sessions. You could still pass it via url which gets priority over sessions. Sequence export code only looked at alignment ID from url param. Hub.pm has a method to get alignment id correctly which should be used in this case.
http://ves-hx-78.ebi.ac.uk:9000/index.html
Sequence alignment exports
Nothing that I am aware of.
N/A
https://www.ebi.ac.uk/panda/jira/browse/ENSWEBREL-1125
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=492456
=> get alignment from hub

htdocs/info/about/publications.html
This PR updates the publication list page:
- Publications are now in chronological order
- Update Ensembl 2017 citation
- Add missing </p> tags
- Current site: https://www.ensembl.org/info/about/publications.html
- Sandbox: http://wp-np2-1d.ebi.ac.uk:1610/info/about/publications.html
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6191
=> Update publications list.

modules/EnsEMBL/Web/Component/Shared.pm, modules/EnsEMBL/Web/Utils/FormatText.pm
Updates the glossary key for the help tooltip when hovering Ensembl canonical flag.
- Sandbox URL: http://wp-np2-1d.ebi.ac.uk:1610/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000198947;r=X:31097677-33339609
- JIRA ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6094
=> Update Ensembl canonical flag in transcript table

conf/SiteDefs.pm, modules/EnsEMBL/Web/Apache/Handlers.pm
We sometimes store very large data objects with Storable, a standard perl way of serialising and deserialising data. This means that we care about two built-in limits in Storable which limit the size of such objects to help programs which mistakenly try to serialise large objects. These two globals used to be configured at the module's build-time for the machine it is built on. At some point in the release sequence for Storable this was stopped (perhaps only in the vendor's branch, homebrew) and fixed, very low limits were instituted instead -- far too low for our uses.
Our new sharedsw build for CentOS7 upgraded Storable to the point where we were affected by this. This meant that "things" broke on the CentOS7 machines (though any new, theoretical build for RH6 would also have displayed …
=> Allow configurable storage limits.

modules/EnsEMBL/Web/Component/Shared.pm, modules/EnsEMBL/Web/Object/Transcript.pm
- Switched transcript ID and name columns
- Removed bolding of names
- http://ves-hx2-75.ebi.ac.uk:42229/Homo_sapiens/Gene/Summary?g=ENSG00000139618;r=13:32315086-32400268
- http://ves-hx2-75.ebi.ac.uk:42229/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000139618;r=13:32315086-32400268;t=ENST00000544455
- https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6331
- https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6332
=> Switch Transcript ID and name column

modules/EnsEMBL/Web/ZMenu/Transcript/RefSeq.pm
ZMenus for RefSeq GFF track in region in detail whe then track is configured to be expanded include a transcript xref to NCBI. This is broken for IG and tRNA genes due to a data bug. We need to remove this link for such transcripts.
when the biotype of the transcript begins "IG_" or equals "tRNA" then there should be no link in the zmenu.
http://ves-hx2-75.ebi.ac.uk:8790/Ovis_aries_rambouillet/Location/View?r=1:127570169-127570240;db=core
https://www.ensembl.org/Ovis_aries_rambouillet/Location/View?r=1:127570169-127570240;db=core
Enable RefSeq track in Configure this page. Update renderer to expanded. click on transcript and then note that when clicking on RefSeq transcript link you get to the wrong transcript
-
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6322
=> Disable refseq transcript link when biotype is tRNA & IG_*

modules/EnsEMBL/Web/DBHub.pm, modules/EnsEMBL/Web/Object/Gene.pm, modules/EnsEMBL/Web/PureHub.pm, modules/EnsEMBL/Web/Query/Availability/Gene.pm, modules/EnsEMBL/Web/Query/Generic/Availability.pm, modules/EnsEMBL/Web/QueryStore/Source/Adaptors.pm, modules/EnsEMBL/Web/SpeciesDefs.pm
Add support for single-species compara databases (and also remove some obsolete compara code).
Should only affect the rapid release site, enabling the configuration of the new Homologues view which is found in the ensembl-rapid repository.
Unlikely, as changes are triggered by the presence of the following configuration in ensembl-rapid:
`$SiteDefs::SINGLE_SPECIES_COMPARA = 1`
Unlikely - the changes …
=> Add support for single-species compara dbs

htdocs/components/15_ImageMap.js, modules/EnsEMBL/Draw/GlyphSet/draggable.pm, modules/EnsEMBL/Web/ImageConfig/gene_summary.pm
This PR restores exon rank information line in the zmenu when a gene is clicked in the Gene Summary view.
The zmenu exon info depends on the `draggable` pseudo-track that was removed in a [previous PR](https://github.com/Ensembl/ensembl-webcode/pull/825) because the scroll (image panning) functionality does not work in Gene Summary view.
This PR restores the `draggable` track (with region selection and exon rank info)  but adds a flag (`noscroll`) that disables image scrolling (and the drag/scroll toolbar switch with it).
Gene Summary view: [sandbox link](http://wp-np2-1d.ebi.ac.uk:1610/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000139618;r=13:32315086-32400268).  
Some other views use the draggable track (e.g.  Location view: [sandbox …
=> Restore zmenu exon rank in gene summary.

utils/dump_ensembl_valid_species.pl
Add a new argument to print production names which will feed into taxon tree generation script
To be merged with the below PR
https://github.com/EnsemblGenomes/eg-web-common/pull/81
N/A
Hopefully not
NA
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6325
=> add a param to print production name

modules/EnsEMBL/Web/Document/HTML/ConsequenceTable.pm
- this should go live with the 105 release
- resolve conflicting import reporting for regulatory_region_ablation variants. VEP reports [modifier](https://github.com/Ensembl/ensembl-variation/blob/master/modules/Bio/EnsEMBL/Variation/Utils/Constants.pm#L971) and docs say [moderate](https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html)
- https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html
- None
- None
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-2977
=> update impact for regulatory_region_ablation to modifier

modules/EnsEMBL/Web/Apache/Static.pm, modules/EnsEMBL/Web/Configuration/Transcript.pm, modules/EnsEMBL/Web/Object/Transcript.pm
This is a pull request intended to support https://github.com/Ensembl/public-plugins/pull/476
- a method is added to detect when a feature has an associated alphafold-predicted 3d structure (checks for the presence of alphafold analysis record in the database)
- the left-hand menu (configuration) has been updated to include a link to the Alphafold view
- the module for the caching of static files has been updated to allow for configurability (javascript files used for the alphafold view are not cached)
http://ves-hx2-75.ebi.ac.uk:8450/Arabidopsis_thaliana/Transcript/AFDB?db=core;g=AT3G52430;r=3:19431095-19434450;t=AT3G52430.1
The pull request is submitted against the `master` branch.
=> Support addition of alphafold molecule viewer

modules/EnsEMBL/Web/ZMenu/MotifFeature.pm
The zmenu for the motif feature track shows broken links for Location. So when a user clicks on it, the page is redirected to an invalid URL page. As suggested in the JIRA ticket, I replaced the broken link with a link to the Location View.
Ensembl live site -> Regulation -> Summary (Regulatory Feature) -> Motif feature track -> Location link
[ENSWEB-6305](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6305)
http://wp-np2-1e.ebi.ac.uk:8320/Homo_sapiens/Regulation/Summary?db=core;fdb=funcgen;r=17:68035636-68047364;rf=ENSR00000097453
=> Fix broken link in motif feature zmenu

modules/EnsEMBL/Web/Component/Gene/SimilarityMatches.pm, modules/EnsEMBL/Web/Document/Panel.pm, modules/EnsEMBL/Web/Document/Table.pm
**Step to reproduce**: Open https://www.ensembl.org/Homo_sapiens/Gene/Matches?db=core;g=ENSG00000139618;r=13:32315086-32400268 and click on the "Download all tables as CSV" button (if is is visible on the page)
**Symptom:** the downloaded CSV wasn't displaying properly in Excel
**Likely cause:** sometimes values in a column would start with a line break, making Excel unable to display the whole value properly.
**Solution:** always trim white space for values added to CSV columns 
**View after the fix:**
**Steps to reproduce:** click on the "Download all tables as CSV" button (if is is visible on the page) and refresh the page; the button will no longer be visible.
**Cause:**
- the button appears only when a certain counter that keeps track of the number of tables in a panel shows that …
=> Trim whitespace when generating CSVs

modules/EnsEMBL/Web/ImageConfigExtension/Tracks.pm
Regulation menus were only shown properly if the species having a Regulatory Build.
We have new data for sus_scrofa, but currently there is no Regulatory Build for it.  
This data is only peaks and signal and the Regulation menu didn't allow to select cell types, experiments, etc without a regulatory Build.
This could be also the case of new species/data comming in the near future.
I make some changes that allows the Regulation menu to be shown if there are cell types in the funcgen DB even if there is no Regulatory Build.
The changes were tested in my Sandbox
http://wp-np2-11.ebi.ac.uk:6008/Sus_scrofa/Location/View?r=1:90744429-90875118
Regulation Menu
_Please provide the URL(s) for any JIRA issues related to this PR._
=> Show regulation Cell Types menu without Regulatory Build

htdocs/info/about/contact/index.html
Fixes the collaborations info link in the contact page.
["Cotact us" page](https://www.ensembl.org/info/about/contact/index.html) on all divisions.
[ENSWEB-6420](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6420)
=> Fix collaboration info link

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm
`Triticum aestivum` has the strain group value set to `triticum_aestivum` which is causing them to be filtered from getting displayed in the orthologues list.
http://wp-np2-1d.ebi.ac.uk:42228/Triticum_turgidum/Gene/Compara_Ortholog?db=core;g=TRITD2Bv1G183370;r=2B:540943210-541159134;t=TRITD2Bv1G183370.1#list_no_ortho
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6474
=> Fix orthologues list strain filter

modules/EnsEMBL/Web/Query/GlyphSet/Transcript.pm
Updated the compact renderer to show either gene symbol or gene stable ID but not both.
http://wp-np2-1d.ebi.ac.uk:42229/Homo_sapiens/Location/View?db=core;g=ENSG00000139618;r=13:52589621-52667443;t=ENST00000544455
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6334
=> Do not display gene ID and symbol together

modules/EnsEMBL/Draw/GlyphSet.pm, modules/EnsEMBL/Draw/Utils/Text.pm
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6564
The upstream LibGD 2.3.3 disabled GD and GD2 format but the Perl wrapper GD::Simple still uses it as an internal format. We store the unsupported format in cache but can't read it back.
The PR changes GD::Simple to use PNG format.
Working on http://test.ensembl.org/Homo_sapiens/Location/View?r=8:26291508-26372680
=> ENSWEB-6564 Store GD::Simple in PNG format.

modules/EnsEMBL/Web/Apache/SpeciesHandler.pm
Ensembl code does not sanitise url path parameters, which can then me used on the server to inject malignant code into the html of the document.
See [example in production](https://www.ensembl.org/Homo_sapiens/Info/Index/%22%3E%3Cimg%20src%3Dx%20onerror%3Dconfirm(document.domain)%3E)
This PR adds the sanitisation of url path in the relevant Apache handler following one of the suggestions from [this article](https://www.perl.com/pub/2002/02/20/css.html).
[link](http://wp-np2-1e.ebi.ac.uk:8410/Homo_sapiens/Info/Index/%22%3E%3Cimg%20src%3Dx%20onerror%3Dconfirm(document.domain)%3E)
All pages that are built using the Legacy.pm template.
🤷‍♂️ 
Might potentially break any view; but from what I checked (e.g. the Search page), the site is holding up fine. …
=> Fix xss caused by unsanitised url path parameters

modules/EnsEMBL/Web/ImageConfig/contigviewbottom.pm
Stop showing %GC track by default in Region in detail.
Release version: 107
Sandbox URL: http://wp-np2-1e.ebi.ac.uk:8320/Homo_sapiens/Location/View?db=core;g=ENSG00000139618;r=13:32315086-32400268
Region in detail
[ENSWEB-6556](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6556)
=> Do not show %GC track by default

modules/EnsEMBL/Web/Component/VariationTable.pm
Metazoa variant table page the redirect from summary page to explore wasn't working.
[SandBox](http://wp-np2-1e:8785/Anopheles_gambiae/Gene/Variation_Gene/Table?db=core;g=AGAP029451;r=2R:11467344-11496378;source=VBP0000002;v=tmp_2R_11462677_C_T;vdb=variation;vf=52783028)
- Other variant tables might have the same issue.
- The explore page might not work in some websites.
Jira ticket: [ENSWEB-6539](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6539)
Jira ticket: [ENSWEB-6502](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6502)
=> Fix summary redirect issue in variant table.

modules/EnsEMBL/Draw/GlyphSet/_mane_plus_clinical.pm, modules/EnsEMBL/Draw/GlyphSet/_mane_select.pm, modules/EnsEMBL/Web/ImageConfigExtension/Tracks.pm, modules/EnsEMBL/Web/Query/GlyphSet/Transcript.pm
- Added separate tracks for MANE Select and MANE Plus Clinical Transcripts
- MANE Select transcript track will be on by default
http://wp-np2-1d.ebi.ac.uk:42229/Homo_sapiens/Location/View?db=core;g=ENSG00000053747;r=18:23689453-24689453;t=ENST00000313654
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6439
Related PR:
https://github.com/Ensembl/public-plugins/pull/510
=> e107: Add separate tracks for MANE Select & MANE Plus Clinical

htdocs/info/data/mysql.html
We are retiring the MySQL 4 branches on Fri 22nd April. This page should be updated on Mon 25th
Please can it be cherry picked onto master too
A static content page only 
http://wp-np2-1d.ebi.ac.uk:8096/info/data/mysql.html 
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6554
=> Mysql4 gone

htdocs/components/81_images_dynamic.css, modules/EnsEMBL/Web/Document/Image.pm
Added text to image header icons in this repo. There is [a separate PR in `public-plugins`](https://github.com/Ensembl/public-plugins/pull/541) to add text to `genoverse_switch`.
e107
http://wp-np2-1e.ebi.ac.uk:8320/Homo_sapiens/Location/View?db=core;g=ENSG00000139618;r=13:32315086-32400268
Configuration headers/toolbars in Region in detail and Gene pages
[ENSWEB-6553](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6553)
=> Add text to image header configuration icons

modules/EnsEMBL/Web/Component/Shared.pm
Change `incl readthrough` to `excl readthrough` for protein coding gene counts.
107
Species info (annotation) page
[ENSWEB-6618](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6618)
http://wp-np2-1e.ebi.ac.uk:8320/Homo_sapiens/Info/Annotation
=> Change incl to excl readthrough for protein coding gene counts

modules/EnsEMBL/Web/Component/Info/HomePage.pm
This change is for e!107. It removes a link in the Regulation pane on the [human overview page](https://www.ensembl.org/Homo_sapiens/Info/Index). 
The link refers to an old [ENCODE tutorial](https://www.ensembl.org/info/website/tutorials/encode.html) in public-plugins. 
[Sandbox view](http://wp-np2-11.ebi.ac.uk:6010/Homo_sapiens/Info/Index)
The encode.html page can be removed from public-plugins if there are no further dependencies.
No known conflicts.
None. The change has been approved by Outreach.
=> Remove link to old ENCODE tutorial

modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm
The highlighted gene ID is not displayed correctly in the Highlighted genes info box. This happens when the orthologue gene ID does not have a display name. The reason behind this was that the code checked if the display name of the orthologue exists and when it fails would display the stable ID of the orthologue instead of the current gene.
The changes in this PR will show the stable ID of the current gene when this check fails. It would be ideal to show the display name instead, but I couldn't figure out how to do it as everything I tried ended up breaking the code.
**Sandbox link:** http://wp-np2-1e.ebi.ac.uk:8330/Homo_sapiens/Gene/Compara_Tree?anc=46819155;db=core;g=ENSG00000133392;g1=ENSEEUG00000000659;r=16:15703135-15857028
**For comparison the staging link is:** …
=> Fix the highlighted gene ID in Gene tree

modules/EnsEMBL/Web/Component/Transcript.pm
Reverts a change made in https://github.com/Ensembl/ensembl-webcode/pull/894 to fix the following bug:
**Cause:** Transcript's child `EnsEMBL::Web::Component::Transcript::SimilarityMatches`, uses the `get_matches` method that is declared on `Component::Shared`.
=> Change the inheritance of the Transcript component back to Component::Shared

htdocs/components/91_config_matrix.css
The names of the samples on the left of the table for Configure Track Display are cut-off. 
Thus, a little more space would was added.
Configure this page -> Regulation -> Feature by Cell/Tissue -> Configure Track Display
[ENSREGULATION-1542](https://www.ebi.ac.uk/panda/jira/browse/ENSREGULATION-1542)
=> UI Fix: names of the samples in 'Configure Track Display'

htdocs/components/00_jquery_selecttotoggle.js
The ID History Converter assembly label was showing the genome of chicken which contains a dot (.). This was because when jQuery was querying the class name, which also happen to contain the dot, it couldn't find the element. Apparently, we need to either escape the dot in class names that we used to query with jQuery or query using an attribute name (source: https://stackoverflow.com/questions/32890749/use-a-dot-in-a-class-name-within-jquery-b-avf-toggle). This PR uses the latter, since escaping the dots in strings could become hacky.
http://wp-np2-1e.ebi.ac.uk:8310/Homo_sapiens/Tools/IDMapper
ID History Converter
[ENSWEB-6670](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6670)
=> Fix id history converter assembly label

modules/EnsEMBL/Web/Component/Gene/GeneSummary.pm, modules/EnsEMBL/Web/Component/Transcript/TranscriptSummary.pm
This PR does the following changes to the gene summary and transcript summary pages:
1. Move the CCDS link below RefSeq in gene pages
2. Add MANE section to both the pages
3. On transcript pages move the CCDS link to below UniProt
4. On transcript pages add text with links to RefSeq
108
Gene Summary: http://wp-np2-1e.ebi.ac.uk:8330/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000053747;r=18:23873020-23955066;t=ENST00000585600
Transcript Summary: http://wp-np2-1e.ebi.ac.uk:8330/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000053747;r=18:23873020-23955066;t=ENST00000313654
Gene Summary and Transcript Summary
[ENSWEB-6552](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6552)
=> Highlight MANE transcripts and proteins on gene and transcript pages

htdocs/components/00_jquery_selecttotoggle.js
The previous fix for ID History Converter assembly label (#906) broken the assembly label in other tools such as File Chameleon. This PR is a fix for that issue.
Please note that this PR is not a fix for the jobs submissions failing in ID History Converter. There is a separate ticket for it ([ENSWEB-6684](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6684)), which I am working on at the moment.
ID History Converter: http://wp-np2-1e.ebi.ac.uk:8310/Homo_sapiens/Tools/IDMapper
File Chameleon: http://wp-np2-1e.ebi.ac.uk:8310/Homo_sapiens/Tools/FileChameleon?db=core
VCF to PED: http://wp-np2-1e.ebi.ac.uk:8310/Homo_sapiens/Tools/VcftoPed
ID History Converter, File Chameleon and VCF to PED
[ENSWEB-6684](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6684)
=> Fix tools assembly label name that broke due to previous PR (#906)

modules/EnsEMBL/Web/Query/GlyphSet/Variation.pm
This PR aims to parse a flag `use_vcf_consequences` from the json file which allows the user to fetch consequences from the VCF file instead of calculating on the fly.
https://github.com/Ensembl/ensembl-variation/pull/830
=> Parse use_vcf_consequences from json file

htdocs/components/00_jquery_selecttotoggle.js
Fixes the broken multiple species selector in both V and NV sites. The fix suggested by @ens-ma7 worked perfectly and was less hacky than what I had in mind (slack conversation: https://genomes-ebi.slack.com/archives/C02HWL7NKR8/p1663673566999799?thread_ts=1663664300.510469&cid=C02HWL7NKR8).
Debug site: https://debug.ensembl.org/Multi/Tools/Blast
Debug EG site: https://debug-eg.ensembl.org/Multi/Tools/Blast
BLAST tools page
The fix was applied in `htdocs/components/00_jquery_selecttotoggle.js` which is commonly used in other tools forms. The previous fixes for particular tools (e.g. ID History Converter) applied in the same files caused issues in other tools.
[ENSWEB-6709](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6709)
=> Fix broken multiple species selector in BLAST form

modules/EnsEMBL/Web/Document/HTML/ToolsTable.pm
The Post-GWAS tool is being [retired in 108](https://www.ensembl.info/2022/07/28/retiring-the-post-gwas-tool/). This PR removes the row in the tools table that describes Post-GWAS.
See the complementary PRs in [public-plugins](https://github.com/Ensembl/public-plugins/pull/615) and [ebi-plugins](https://github.com/Ensembl/ebi-plugins/pull/133) that remove the configuration related to Post-GWAS.
Tools index page. See [sandbox](http://wp-np2-1f.ebi.ac.uk:8800/info/docs/tools/index.html).
None
None
This PR fulfills the first part of [ENSWEB-6588](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6588).
=> Remove postgap

conf/httpd.conf, conf/ini-files/DEFAULTS.ini, htdocs/info/data/ftp/rsync.html, htdocs/info/website/trackhubs/adding_trackhubs.html, htdocs/info/website/upload/sample_files/Pulmonary_function.vcf.txt, modules/EnsEMBL/Web/Document/HTML/FTPtable.pm
This PR updates all `http://ftp` URLs to https.
The affected URL hostnames have been tested working with https.
Similar PRs in other repos are listed in the JIRA ticket.
JIRA ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6632
Sandbox: http://wp-np2-1d.ebi.ac.uk:1680
=> Update ftp links to https

conf/ini-files/DEFAULTS.ini
This PR updates retired Pfam URLs to the new site (InterPro).
Other affected repos listed in the JIRA ticket.
JIRA ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6701
Sandbox: http://wp-np2-1d.ebi.ac.uk:1680
=> Update Pfam URLs

modules/EnsEMBL/Web/Configuration/Gene.pm
This PR removes the Ensembl protein family and Ensembl gene family left-side menu entries from gene view.
The menu entries have been disabled since its retirement in e102.
JIRA ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6678
Affected views: Gene view
Sandbox: http://wp-np2-1d.ebi.ac.uk:1680/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000139618;r=13:32315086-32400268
=> Remove Ensembl gene/protein family entries

conf/ini-files/DEFAULTS.ini
Add and update URL templates. This is required to add links to protein domains in web VEP results: https://github.com/Ensembl/public-plugins/pull/618
Web VEP results: http://wp-np2-11.ebi.ac.uk:6070/Homo_sapiens/Tools/VEP/Results?tl=Jhfkd0i4oa5KPvRV-82
Any view that uses external URLs based on the modified variables.
This PR replaces `PFAM` website with InterPro: the [Pfam website](http://pfam.xfam.org) is going to be decommissioned in January 2023 and redirects to InterPro. All links that make use of the `PFAM` variable to create an external URL should now direct to InterPro.
[ENSVAR-3396](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-3396)
=> Add/update URL templates for protein domains in VEP (109)

modules/EnsEMBL/Web/Component/Variation/Mappings.pm
Add external links to protein domains from multiple sources, including:
- AlphaFold
- Gene3D
- HAMAP
- PANTHER
- PDB
- Pfam
- CDD
- PIRSF
- PROSITE patterns
- PROSITE profiles
- SMART
- Superfamily
- SFLD
- TIGRFAM
- Prints
Variation page > Consequence details table > **Overlapping protein domains** row. Examples:
* [rs766926945](http://wp-np2-11.ebi.ac.uk:6070/Homo_sapiens/Variation/Mappings?db=core;r=8:109335664-109336664;v=rs766926945;vdb=variation;vf=729142651#ENST00000521688_729142651_A_tablePanel)
* [rs1567817867](http://wp-np2-11.ebi.ac.uk:6070/Homo_sapiens/Variation/Mappings?db=core;g=ENSG00000012048;r=17:43044295-43170245;t=ENST00000357654;v=rs1567817867;vdb=variation;vf=266701878#ENST00000352993_266701878_AT_tablePanel)
* …
=> Add links to protein domains in Variation page (e109)

htdocs/components/25_ConfigRegMatrixForm.js
If the regulation database does not contain entries in the `feature_type` table for all different classes of features (Open Chromatin, Histone and Transcription Factor), the regulation matrix becomes unusable. Here's what it looks like (trying to click a checkbox, but nothing happens):
https://user-images.githubusercontent.com/6834224/198000706-0c18d8b3-778e-486f-88de-c846133bcddf.mp4
The reason is because javascript is trying to access a field on an undefined object:
The null check added in this PR seems to be sufficient
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6517
Sandbox url:
http://wp-np2-1e.ebi.ac.uk:8410/Sus_scrofa/Location/View?r=14:10195351-10284707
_(when testing please check that the sandbox is using the test pig database that doesn't contain all classes of features)_
=> Fix regulation matrix when feature types are missing

conf/ini-files/DEFAULTS.ini
This PR updates xref URL template for GeneCards database.
[Sandbox](http://wp-np2-1d.ebi.ac.uk:1680) (xref not used in website)
[JIRA](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6642)
=> Update GeneCards xref

modules/EnsEMBL/Web/ImageConfig/structural_variation.pm
There is a long list of regulatory tracks that were turned on by default in the Structural Variation page. A side cause of this issue is that the page eventually breaks due to attempting to load a big amount of data into the page.
The issue was fixed after removing `regulatory_features` tracks which were enabled in the code. This was the longest list of regulatory tracks.
Relevant links:
- Live site where the page breaks: https://www.ensembl.org/Homo_sapiens/StructuralVariation/Context?r=13:99984196-99986821;sv=nsv916030;svf=121912273;vdb=variation
- Sandbox where it now works: http://wp-np2-1e.ebi.ac.uk:8310/Homo_sapiens/StructuralVariation/Context?r=13:99984196-99986821;sv=nsv916030;svf=121912273;vdb=variation
Structural variant (genome context)
Not sure about this yet …
=> Fix all regulation tracks enabled by default

conf/httpd.conf
www.ensembl.org/ftp is not working due to a recent change of http to https. 
Our Apache can't proxy requests to https, as it requires another module installed like mod_ssl.
Need to revert the latest commit.
=> Fix /ftp proxy to use http

modules/EnsEMBL/Web/Component/Variation/Mappings.pm
Add buttons to view 3D protein structure models for PDB and AlphaFold associated with variant consequences, similar to code from https://github.com/Ensembl/public-plugins/pull/555
AlphaFold button is only shown for missense variants.
Variation tab > Genes and regulation > Details of transcript consequences > Overlapping protein domains
For instance: http://wp-np2-11.ebi.ac.uk:6070/Homo_sapiens/Variation/Mappings?db=core;r=8:109335664-109336664;v=rs334;vdb=variation;vf=164384244#ENST00000335295_164384244_C_tablePanel
No complications, only adds HTML to variation page.
No conflicts.
[ENSVAR-5231](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5231)
=> Add 3D structure links to PDB and AlphaFold in variation page (e109)

modules/EnsEMBL/Web/Component/Variation/Summary.pm
Correct the text for the hyperlinks (not the actual href link) linking EnsEMBL Variation 'Original source' from 'About ClinVar' to 'View in ClinVar'.
Affects the region view - click on a variant's link along the track for ClinVar
examples with my Rapid Release sandbox:
[Example 1 - human T2T pangenome](http://wp-np2-25.ebi.ac.uk:8001/Homo_sapiens_GCA_009914755.4/Variation/Explore?db=core;r=2:179145571-179145780;source=ClinVar;v=467074;vdb=variation;vf=2:179145597:G_C:ClinVar)
[Example 2 - human pangenome GCA_018472595.1](http://wp-np2-25.ebi.ac.uk:8001/Homo_sapiens_GCA_018472595.1/Variation/Explore?db=core;r=JAHBCB010000019.1:53183300-53183427;source=ClinVar;v=1304774;vdb=variation;vf=JAHBCB010000019.1:53183379:G_C:ClinVar)
None expected
Tested just before submitting this pull request …
=> correct Variation ClinVar link in rapid release

htdocs/components/00_jquery_selecttotoggle.js
Fix BLAST form being broken because of a change that was made in #950. Now the `className` is explicitly checked if it is undefined or not before the rest of the function is executed.
Sandbox link: http://wp-np2-1e.ebi.ac.uk:8310/Multi/Tools/Blast?db=core
BLAST
Not sure
[ENSWEB-6794](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6794)
=> Fix escapeDot breaking BLAST form

modules/EnsEMBL/Web/Component/Gene/Alleles.pm, modules/EnsEMBL/Web/Object.pm
This PR contains changes to update the Gene Alleles table so that all gene alleles are now displayed, i.e. if the gene in question is associated with multiple alt allele groups, all of the gene alleles will be shown. Has been tested on Release 108 and currently testing on Release 110.
The view of the Gene Alleles table will be updated.
Example from an X PAR gene web page: …
=> Fetch multiple alt allele groups for display in Gene Alleles web table

conf/ini-files/DEFAULTS.ini
The URLs for OMIM are broken in the main site; see [ENSWEB-6803](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6803). This PR updates the URL in DEFAULTS.ini, as per Ben's ticket.
See the "MIM Morbid" link in the [phenotypes table](https://www.ensembl.org/Homo_sapiens/Gene/Phenotype?db=core;g=ENSG00000164405;r=5:132866630-132868847).
None.
None.
[ENSWEB-6803](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6803)
=> Update OMIM URLs

modules/EnsEMBL/Web/Document/HTML/Compara.pm
This allows for the multiple genome statistics page to be viewed for Cactus HAL alignments in which each subgenome of a polyploid genome is stored separately, so that the principal polyploid `genome_db_id` is not in the species tree associated with the Cactus MLSS.
In `EnsEMBL::Web::Document::HTML::Compara`, the `get_species_info` method fetches genomic coverage stats from the species-tree node corresponding to a given genome. However, if a genome does not correspond to a single node of a species tree — as is the case for the polyploid genomes in the Wheat Cactus alignment — then it is not currently possible to fetch any stats for that genome from a node of the species tree.
This results in an error which prevents the display of the multiple genome alignment stats page  (e.g. …
=> Fall back to MLSS if genome not in species tree

htdocs/info/website/browsers.html
This PR is to update the supported browser list page. The changes can be viewed here http://wp-np2-1f.ebi.ac.uk:10000/info/website/browsers.html. 
The list was generated by looking browser usage stats here https://caniuse.com/usage-table. Safari includes a bigger drop to account for the penultimate version of macOS being locked to version 15.6. 
More details can be seen in the ticket here https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6724
The ticket mentions that molstar should be taken into consideration. Sadly I could not find any minimum browser requirements so I just added a note about hardware acceleration
=> Jk ensweb 6724

modules/EnsEMBL/Draw/GlyphSet/fg_multi_wiggle.pm
This PR changes the style of regulation peak tracks from `Style::Feature::MultiBlocks` to `Style::Feature::Structured`. The reason being that `Style::Feature::Structured` is the style we use custom user tracks, and it supports gaps in the way that Regulation wants.
**Sandbox:**
http://wp-np2-1e.ebi.ac.uk:8410/Sus_scrofa/Location/View?r=1:162511400-162515687;time=1679479911277.277;db=core
To see gapped peaks, set:
- Cell/tissue: cerebellum (m, 6mo), and
- Experiment: H3K4me1 histone
To see narrow peaks, set:
- Cell/tissue: adipose tissue (m, 6 mo)
- no need to change the experiment
Here's what you should see:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6832?jql=order%20by%20lastViewed%20DESC
=> Change drawing style for regulation peak tracks

htdocs/components/16_Interaction.js, htdocs/components/99.Interaction.css
From user feedback, microbes team decided to add a small piece of text to the interactions pages that clarifies the sources and criteria we used. 
As per the XD screenshot below, 
Note, I personally dont like the code I added :-)  But as this is just a one off feature added for Interactions page I am OK. What you guys think?
To have a proper reusable solution, we may have to dive into [this component](https://github.com/Ensembl/ensembl-webcode/blob/main/modules/EnsEMBL/Web/Document/Panel.pm#L57).  Not sure if it is really necessary
=> Add more information near the page caption

modules/EnsEMBL/Web/Component/Compara_Alignments.pm
This PR fixes an ajax error in the compara alignments for plants. See the [ENSWEB bug report](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6839). The underlying issue appears to be a missing dependency (the method `pluralise`). Presumably this module was previously loaded in a parent module or another dependency but that `use` has been removed during refactoring and we're only now hitting the call in this code path.
[http://staging-plants.ensembl.org/Triticum_aestivum_landmark/Location/Compara_Alignments/Image?align=313160;db=core;r=6B:570561430-570563408](http://staging-plants.ensembl.org/Triticum_aestivum_landmark/Location/Compara_Alignments/Image?align=313160;db=core;r=6B:570561430-570563408)
The exception could be a symptom of a deeper problem, in which case simply adding the …
=> Add a missing dependency

modules/EnsEMBL/Web/JSONServer/RegulationData.pm, modules/EnsEMBL/Web/ZMenu/Regulation.pm
1. Update behaviour of the regulation matrix
- Do not enable epigenomic activity track by default
- Filter out segmentation features tracks if they are not available for a given cell line
2. Replace the "Stable ID" label with just "ID", because not all identifiers of regulatory features are truly stable (see ENSWEB-6827, section 2)
- Region view for Pig (shouldn't see any available segmentation features track):
http://wp-np2-1e.ebi.ac.uk:8410/Sus_scrofa/Location/View?r=1:162511400-162515687;time=1679479911277.277;db=core
- Region view for Human (shouldn't see any changes):
http://wp-np2-1e.ebi.ac.uk:8410/Homo_sapiens/Location/View?r=8:26291508-26372680;debug=js;time=1681285452321.321
To check zmenu label:
- http://wp-np2-1e.ebi.ac.uk:8410/Sus_scrofa/Regulation/Summary?db=core;fdb=funcgen;r …
=> Update regulation matrix behaviour and change zmenu label

modules/EnsEMBL/Web/Document/HTML/FTPtable.pm
_Website still shows the RDF download button within the FTP, however we retired that datasource in release 103.
_[Other annotations](https://www.ensembl.org/info/data/ftp/index.html)
_Sandbox: http://wp-np2-1e:8789/info/data/ftp/index.html
_[Please provide the URL(s) for any JIRA issues related to this PR.](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6808)
=> Remove RDF reference url.

conf/ini-files/DEFAULTS.ini
Add MaveDB URL. This is used to create hyperlinks from MaveDB plugin results in web VEP: https://github.com/Ensembl/public-plugins/pull/691.
No views affected.
No complications.
[ENSVAR-5485](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5485)
=> Add MaveDB URL (110)

modules/EnsEMBL/Web/Component/Variation/Mappings.pm
The way Ensembl databases are storing Alphaford ids has changed. Previously, Ensembl was adding `.A` (to represent protein chain) to an alphafold identifier, like so:
```
mysql> select protein_feature.hit_name from protein_feature join analysis on protein_feature.analysis_id = analysis.analysis_id where analysis.logic_name = "alphafold_import" limit 10;
+--------------------+
| hit_name           |
+--------------------+
| AF-A0A024RCN7-F1.A |
| AF-A0A024RCN7-F1.A |
| AF-A0A024RCN7-F1.A |
| AF-A0A024RCN7-F1.A |
| AF-A0A024RCN7-F1.A |
| AF-A0A024RCN7-F1.A |
| AF-A0A024RCN7-F1.A |
| AF-A0A024RCN7-F1.A |
| AF-A0A024RCN7-F1.A |
| AF-A0A024RBG1-F1.A |
+--------------------+
```
This was a bad idea, and starting from 110, Ensembl dbs store plain Alphafold identifiers:
```
mysql> select …
```
=> Remove alphafold id manipulation

modules/EnsEMBL/Web/Component/StructuralVariation/Summary.pm
Show allele types for any source in Variation summary page. Currently, this only works for variants from DGVa.
- Human (dbVar): [nsv4517655](http://wp-np2-11.ebi.ac.uk:6070/Homo_sapiens/StructuralVariation/Mappings?db=core;r=1:521700-621900;sv=nsv4517655;svf=127710255;vdb=variation) - added allele type compared to [current website](http://ensembl.org/Homo_sapiens/StructuralVariation/Mappings?db=core;r=1:521700-621900;sv=nsv4517655;svf=127710255;vdb=variation)
- Pig (DGVa): [nsv443016](http://wp-np2-11.ebi.ac.uk:6070/Sus_scrofa/StructuralVariation/Mappings?r=7:67148496-67211415;sv=nsv443016;svf=665;vdb=variation) - no change in header compared to [current website](http://ensembl.org/Sus_scrofa/StructuralVariation/Mappings?r=7:67148496-67211415;sv=nsv443016;svf=665;vdb=variation)
For CNVs …
=> Variation summary: show CNV allele type for any source (e110)

modules/EnsEMBL/Draw/GlyphSet/genetree.pm
This PR is in support of https://github.com/EnsemblGenomes/eg-web-common/pull/115. See full description there.
=> Treat highlight annotations (for non-vertebrate gene trees) as arrays of strings

conf/ini-files/DEFAULTS.ini
Add Open Targets Genetics link to gene and variant pages, required to link external results in web VEP.
Used for the `Open Targets L2G` column in web VEP to link to external resource: http://wp-np2-11.ebi.ac.uk:6070/Homo_sapiens/Tools/VEP/Results?tl=5tybNB2ISXldSibO-38
No complications expected.
[ENSVAR-5840](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5840)
=> Add Open Targets Genetics links (e111)

modules/EnsEMBL/Draw/GlyphSet/Vsynteny.pm, modules/EnsEMBL/Web/Component/Location/SyntenyImage.pm
The code to display a synteny alignment view is assuming that the alignment can only be done between two different species, and thus breaks when tasked to show a human self-alignment. Meanwhile, we are displaying a link to human self-alignment synteny page on a Compara help&docs page: https://www.ensembl.org/info/genome/compara/analyses.html
The changes in this PR are:
- handle the case when the "main species" is the same as the "other species" in `GlyphSet/Vsynteny.pm`
- make sure Human always shows up int the dropdown of species available for alignment view
Synteny for Human aligned against Human
http://wp-np2-1e.ebi.ac.uk:8410/Homo_sapiens/Location/Synteny?r=8:26291508-26372680;otherspecies=Homo_sapiens
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6820
=> Fix human self-alignment synteny

modules/EnsEMBL/Web/Query.pm
_This PR is in support of https://github.com/EnsemblGenomes/eg-web-metazoa/pull/25. See the full description of the problem there._
In availability queries, it was impossible to access to the hub, and from it, other things that might be useful. Curiously, this was possible in other kinds of queries, for example in glyphset queries ([link](https://github.com/Ensembl/ensembl-webcode/blob/release/110/modules/EnsEMBL/Web/Query/GlyphSet/Transcript.pm#L276-L277)) or in sequence queries ([link](https://github.com/Ensembl/ensembl-webcode/blob/release/110/modules/EnsEMBL/Web/Query/Sequence/Transcript.pm#L85)).
It turned out that the Query.pm module sometimes [calls the relevant method providing the context](https://github.com/Ensembl/ensembl-webcode/blob/release/110/modules/EnsEMBL/Web/Query.pm#L89 …
=> Ensure context presence in availability queries

modules/EnsEMBL/Web/Document/HTML/Compara.pm, modules/EnsEMBL/Web/Document/HTML/Compara/MLSS.pm
The Cactus stats view is updated as follows:
- The initial description of the alignment is made more consistent with that of other multiple genome alignments (e.g. "This alignment has been generated in Ensembl Plants release 57.").
- Coverage stats columns 'Genome length (bp)', 'Genome coverage (bp)' and 'Genome coverage (%)' are added to the stats table. These are populated from MLSS coverage stats where available. Where no coverage statistic is available, an `NA` value is displayed.
- A brief description of the coverage calculation method is added, as Cactus alignment coverage is currently calculated in a different way to the coverage of other multiple genome alignment methods (e.g. EPO).
- The species-order list used to populate the Cactus stats table is deduplicated. This is useful in …
=> Update Cactus stats view

modules/EnsEMBL/Web/Component/Regulation.pm, modules/EnsEMBL/Web/Component/Regulation/FeatureDetails.pm, modules/EnsEMBL/Web/Configuration/Regulation.pm, modules/EnsEMBL/Web/ViewConfig/Regulation/FeatureDetails.pm
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6845
- Remove track image component from regulation views
- When saving configs in regulation view, update location view config so that the tracks can be seen in location view.
- Remove Feature context and Details by cell types pages
http://wp-np2-1e.ebi.ac.uk:9000/Homo_sapiens/Regulation/Summary?db=funcgen;fdb=funcgen;r=8:37966115-37968453;rf=ENSR00001137252
Regulation
=> ENSWEB-6845 Use contigviewbottom configs to save regulation configs

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm, modules/EnsEMBL/Web/Object/Gene.pm
This PR:
- adds an option to restrict homologies returned by `EnsEMBL::Web::Object::Gene::get_homologies` to include only those in a specific gene tree; and
- uses that option in the `get_export_data` method of `EnsEMBL::Web::Component::Gene::ComparaOrthologs` if the export flag is `genetree`, which is currently used only in the case of OrthoXML and PhyloXML download formats.
These changes would cause OrthoXML and PhyloXML orthologue downloads accessed via the "Download orthologues" button to contain orthology data for genes in a specific tree, where the gene tree would be the one selected by by [method get_GeneTree of EnsEMBL::Web::Object::Gene](https://github.com/twalsh-ebi/ensembl-webcode/blob/20fa36a2dca860cee91ee91ba40313c4d7a8418b/modules/EnsEMBL/Web/Object/Gene.pm#L944) based on …
=> Add option to restrict orthologies by gene tree

conf/ini-files/DEFAULTS.ini
We changed the DDG2P source to G2P source 
https://www.ensembl.org/Homo_sapiens/Gene/Phenotype?db=core;g=ENSG00000134532;r=12:23529504-24562544 - The G2P source is not a link
=> Adding G2P config

modules/EnsEMBL/Web/Factory/Location.pm
When viewing an image alignment (e.g. in the [Cactus alignment of the Wheat reference genome example region](http://wp-np2-25.ebi.ac.uk:5098/Triticum_aestivum/Location/Compara_Alignments/Image?r=3D:2585940-2634711;align=313160;db=core)), clicking and dragging on a region in the alignment image triggers a Z-menu with a link saying something like, "Jump to best aligned region on Triticum aestivum".
Clicking on that link should bring the user to a new image alignment of the subregion defined by the clicked-and-dragged area in the original alignment. However, this currently does not always work as expected for the Wheat Cactus alignment, and may instead show a "Region too large" warning box.
For example, in this screenshot, the region which the webcode has attempted to display is much larger …
=> Filter by subgenome as needed when mapping from AlignSlice

modules/EnsEMBL/Draw/GlyphSet/genetree.pm
With the introduction in e111 of the polyploid GenomicAlignTree for the Wheat Cactus alignment, different leaves of the Wheat Cactus GenomicAlignTree can represent different subgenome components of polyploid Wheat genomes.
The leaves of the Wheat Cactus tree are currently labelled with the genome name. This PR would allow them to be labelled additionally with the subgenome component name, as in the following image:
This affects the GenomicAlignTree view shown above Wheat Cactus multiple sequence text alignments, and the text alignment view of any polyploid-aware Cactus multiple genome alignment introduced in future.
Example on Plants sandbox: http://wp-np2-25.ebi.ac.uk:5098/Triticum_aestivum/Location/Compara_Alignments?r=3D:2585940-2634711;align=313160;db=core
No complications are …
=> Show component in Wheat GenomicAlignTree leaf name

modules/EnsEMBL/Web/Document/HTML/Compara/GeneTrees.pm
This PR would ensure that gene-tree stats are displayed for the default gene-tree collection in general, and the default Metazoa protein-tree collection in particular. It would fix [ENSWEB-6881](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6881).
The code added in this PR would be used in protein-tree and ncRNA-tree stats on all Ensembl sites.
However, it would only affect the Metazoa protein-tree …
=> Give preference to default gene-tree stats

modules/EnsEMBL/Draw/GlyphSet/patch_ref_alignment.pm
Message from Jose:
The assembly_exception table in the core database used to contain the coordinates of the patches with respect to the corresponding reference chromosome. This was because patches were represented as fake chromosomes in the genome browser. Since release 110, patches are on its own, so the assembly exceptions don’t make sense anymore and have been deleted from the database.
I am not sure about the implications of this in the context of the webcode. Perhaps the patch start should always be 1 and the patch end be the patch length in this new scenario?
Adjusting the patch start and end fixed.
Region comparison and Region in detail
Sandbox for testing http://wp-np2-1e.ebi.ac.uk:9000/
Dont know
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6751 …
=> Human patches fix

htdocs/info/about/ensembl_powered.html
Updating the list of projects with bindings to Ensembl to include ensemblQueryR
We have been discussing with Aine Fairbrother-Browne if we would be happy to promote `ensemblQueryR` as a set of bindings to Ensembl's REST API. We have agreed and updated the documentation as appropriate. Change is in the final API section with text provided by Aine. I have included links to the GitHub repository.
- Ensembl powered. Live link at <https://www.ensembl.org/info/about/ensembl_powered.html>
None since this is a static HTML edit. Only issue is if I linked to the wrong branch, but according to the requirements I think this is fine since the edits should be applied into 111 and main.
Done directly against main so should be without conflict as far as I have checked
None
=> Add ensemblQueryR as a binding to Ensembl documentation

modules/EnsEMBL/Web/Component/Info/HomePage.pm
Update the Regulation pane text in Species index page.
Current: https://www.ensembl.org/Homo_sapiens/Info/Index
Updated: http://wp-np2-25.ebi.ac.uk:6020/Homo_sapiens/Info/Index
None.
None.
[ENSREGULATION-2080](https://www.ebi.ac.uk/panda/jira/browse/ENSREGULATION-2080)
=> [r112] Update the Regulation pane in Species index page

modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm
If accepted, this PR would add the `exons` parameter to the `@extra_params` array (and indirectly to `export_params`) in the [ensembl-webcode ComparaTree](https://github.com/Ensembl/ensembl-webcode/blob/507432c684afb3ad760b61863cc7ff3d478e904e/modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm#L360), effectively ensuring that this parameter is passed to the gene-tree image export functionality.
In …
=> Add exons to gene-tree export params

modules/EnsEMBL/Draw/GlyphSet/genetree.pm
This PR tweaks the order in which gene-tree labels are processed, so in a gene-tree view with a query gene and its homologue highlighted, the query and its homologue highlighting rules are given priority over query-genome and homologue-genome highlighting rules.
In practice, this means that in a gene tree view linked from a homoeologue table, the query gene label will be highlighted in red, as it is in a gene tree linked from an orthologue table.
Though the change is made in a module which affects gene-tree, gene gain/loss and genomic-align tree views, the effects of the change should only be noticeable in gene-tree views with a highlighted query gene and homologue in the same species (e.g. gene tree linked from homoeologue table).
Examples:
- [Homoeologue …
=> Tweak order of gene-tree highlighting rules

modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm
For gene-tree nodes with a corresponding species-tree node, the gene-tree ZMenu caption is taken from the taxon name or alias of the species-tree node.
For gene-tree nodes lacking a corresponding species-tree node, the ZMenu fails to load. This PR restores a previously used default caption, "Taxon: unknown", which has the effect of allowing a ZMenu to be displayed in such cases.
This update changes code which is used in the ZMenu of all gene-tree views.
However, its effects should be restricted to the ZMenu of those gene-tree nodes lacking a corresponding species-tree node.
To see the effect of this PR, select the `ftga_it_nj` tree of each of the example gene tree views, and click on the root node:
- Example on RC site: [ENSPANG00000013968](https://rc.ensembl.org/Papio_anubis/Gene/Compara_ …
=> Add default caption to gene-tree node ZMenu

modules/EnsEMBL/Web/Component/Summary.pm
The gene summary of projected genes may contain a link to a "reference strain equivalent" (e.g. a link to 'Cntnap1' in the gene summary of [MGP_AJ_G0019153](http://jan2024.archive.ensembl.org/Mus_musculus_A_J/Gene/Summary?g=MGP_AJ_G0019153)).
The generation of this link involves an initial lookup of the stable ID database, followed by the gene being fetched from the core database of the projection reference genome.
This can go wrong in a couple of ways:
1. If the stable ID is no longer current in the reference genome, an error message appears in the gene summary, though most of the gene web page is still shown. This less severe issue affects 44,648 Mouse strain genes in Ensembl 112.
2. If the stable ID clashes with that of another genome, a more severe error occurs which prevents the gene …
=> Check if projection parent is in ref core database

modules/EnsEMBL/Web/Command/DataExport/Output.pm
Gene-tree export functionality is not currently available for non-default Metazoa gene trees.
[eg-web-metazoa PR 36](https://github.com/EnsemblGenomes/eg-web-metazoa/pull/36) makes it possible to export data in most formats for the affected Metazoa gene trees.
This PR takes things a step further, by making it possible to export OrthoXML data.
This adjustment makes it possible to download OrthoXML tree data from the following Metazoa gene-tree views:
- [D. melanogaster His3.3A Protostomes tree](http://wp-np2-25.ebi.ac.uk:5094/Drosophila_melanogaster/Gene/Protostomes_Tree?db=core;g=FBgn0014857)
- [D. melanogaster His3.3A Insects tree](http://wp-np2-25.ebi.ac.uk:5094/Drosophila_melanogaster/Gene/Insects_Tree?db=core;g=FBgn0014857)
- [D. melanogaster His3.3A Drosophila …
=> Relax component regex in OrthoXML export

modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm
This PR adjusts the gene-tree fetching code in `genetree` export mode (used for OrthoXML and PhyloXML) to fetch the strain tree if the `strain` parameter has been set.
Currently, when the user tries to export gene-tree data from a strain/breed/cultivar tree in OrthoXML or PhyloXML format, the downloaded file contains data for the default gene-tree collection.
This change affects OrthoXML/PhyloXML export functionality in all strain/breed/cultivar views.
Example of Mouse Cntnap1 strain tree:
- Compara sandbox: http://wp-np2-25.ebi.ac.uk:5092/Mus_musculus/Gene/Summary?g=ENSMUSG00000017167
- RC site: https://rc.ensembl.org/Mus_musculus/Gene/Strain_Compara_Tree?g=ENSMUSG00000017167
Example of Pig PPP2R2A strain tree:
- Compara sandbox: …
=> Export strain data in OrthoXML and PhyloXML format

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm, modules/EnsEMBL/Web/SpeciesDefs.pm
This PR:
- Adds a `$compara_db` to `EnsEMBL::Web::SpeciesDefs::prodnames_to_urls_lookup`. If this is set to `compara_pan_ensembl`, the returned lookup is equivalent to the `PAN_COMPARA_LOOKUP`.
- Uses the updated `prodnames_to_urls_lookup` in `EnsEMBL::Web::Component::Gene::ComparaOrthologs` module in order to simplify access to the Pan Compara lookup as appropriate.
- Updates method …
=> Break down Pan Compara orthologue summary by division

modules/EnsEMBL/Draw/GlyphSet/genetree.pm, modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm, modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm
This PR tweaks supertree views, making it possible to follow most supertree view "Switch to that tree" links, including in Pan Compara gene trees, non-default Metazoa gene-tree views, Vertebrate strain trees, and, in conjunction with [eg-web-common PR 122](https://github.com/EnsemblGenomes/eg-web-common/pull/122), Non-Vertebrate strain tree views.
A key change is that preference is given to showing …
=> Tweak supertree links in gene tree view

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm
In conjunction with [eg-web-metazoa PR 37](https://github.com/EnsemblGenomes/eg-web-metazoa/pull/37), this PR makes it possible to highlight the ancestral node of orthologous genes in all Metazoa gene-tree collections.
Gene-tree links in Ensembl Metazoa orthologue views are affected.
Examples:
- Drosophila melanogaster His3.3A orthologues: [sandbox](http://wp-np2-25.ebi.ac.uk:5094/Drosophila_melanogast …
=> Add base method to fetch orthology ancestral nodes

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm, modules/EnsEMBL/Web/Component/Gene/ComparaParalogs.pm
To facilitate testing, this PR — in conjunction with [eg-web-common PR 123](https://github.com/EnsemblGenomes/eg-web-common/pull/123) — adds spacing between elements within the same cell of an orthology/paralogy/homoeology table view.
This set of changes primarily affects the spacing of elements within text files downloaded from orthologue, paralogue and homoeologue views.
Examples:
- Orthologues: …
=> Add spaces between elements in homolog table cells

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm
Currently Pan Compara OrthoXML and PhyloXML downloads are filtered by the URL lookup of the host division, resulting in OrthoXML/PhyloXML download files that lack homologies being displayed in the Pan Compara orthologue table of the same gene.
This PR ensures that the Pan Compara URL lookup is used for Pan Compara orthologue downloads, by passing the `$cdb` parameter to the `prodnames_to_urls_lookup` …
=> Filter Pan Compara homologies by Pan Compara lookup

modules/EnsEMBL/Web/ZMenu/MotifFeature.pm
Changes requested from regulation:
_We will be removing experimentally validated links from motifs to epigenomes in the funcgen database.  
Therefore, we need to remove the "experimentally verified in" information from the motif z-menu (see below) in release 113.
For consistency with regulatory features, please also change "Stable ID" to "ID"._
Regulation track zmenu
NA
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6921
=> remove experimentally verified from zmenu

conf/SiteDefs.pm, htdocs/components/25_ConfigRegMatrixForm.js, modules/EnsEMBL/Web/JSONServer/RegulationData.pm
In order to deal with changes that reg
ulation team are making, it makes sense to have our localstorage versioned rather than asking users to clear the cache for any data change.
Configuration > Activities by cell type
Users will lose all previous selection data if underlying data changes
NA
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6946
=> Versioned local storage for regulation

modules/EnsEMBL/Web/Document/HTML/GenomeList.pm
This PR increases the Pig breed count in the Vertebrates genome list to match the number of Pig breeds represented in Ensembl 113 (less the Pig reference genome).
This affects the genome list view in the Ensembl Vertebrates homepage.
This is a straightforward HTML text update, so no complications are expected. 
None detected.
N/A
=> Increase Pig breed count in Vertebrates genome list

modules/EnsEMBL/Web/ConfigPacker.pm, modules/EnsEMBL/Web/Configuration/Gene.pm
In the sidebar menu of a gene view, strain-level homologies can be accessed via a menu item which is named from the strain type of the current organism, specifically from the `strain.type` meta entry of the relevant core database.
This can result in inconsistent display of the homology menu item for different genomes in the same gene-tree collection. For example, in the [USMARC gene …
=> Fetch homology strain type from Compara database

modules/EnsEMBL/Web/Component/Gene/ComparaParalogs.pm
Alignment links in strain-level paralogue views are pointing to the default `Compara_Paralog` URL.
For non-reference genomes in strain-level gene-tree collections, clicking on the link leads to a page with the following genomes:
> Sorry, this page is not available for this feature. Please select a valid link from the menu on the left.
(This issue does not manifest in any reference genomes, because …
=> Fix strain-level paralogue alignment links

modules/EnsEMBL/Draw/GlyphSet/fg_regulatory_features.pm
For 113, a new regulatory feature called EMAR was added (epigenetically-modified accessible region)
The following reordering of the lane was suggested 
Top: promoter, enhancer, open chromatin
Middle: EMAR
Bottom: CTCF
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6948
Views that show regulatory builds - like location view, genoverse, gene page etc.
Probably no.
=> change lane order of regulatory build

modules/EnsEMBL/Web/Component/Variation/Summary.pm
Replace the 'overlap' text with 'has predicted consequences for' in the Variation summary page.
Test -
http://wp-np2-11.ebi.ac.uk:7070/Homo_sapiens/Variation/Explore?r=1:230709548-230710548;v=rs699;vdb=variation;vf=11
http://wp-np2-11.ebi.ac.uk:7070/Homo_sapiens/Variation/Explore?db=core;r=Y:14328321-14329321;v=rs745378073;vdb=variation;vf=1169235343
Variation summary page.
None. It is a static update.
None
https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6423
=> Update variation summary page for GENCODE primary (e113)

modules/EnsEMBL/Draw/GlyphSet/fg_regulatory_features.pm
Reg. features with no activity in `funcgen` appear as `active` in the Browser.
This PR fixes this, setting the activity for these features to `na`.
Location View, with at least one `Cell/Type - Epigenomic activity` enabled.
http://wp-np2-25.ebi.ac.uk:6020/Homo_sapiens/Location/View?r=17:63992802-64038237
[ENSREGULATION-2265](https://www.ebi.ac.uk/panda/jira/browse/ENSREGULATION-2265)
=> [r113] Deactivate activity track for Reg. feature with no activity in funcgen

modules/EnsEMBL/Web/Component/Regulation/Evidence.pm, modules/EnsEMBL/Web/Component/Regulation/FeatureDetails.pm
Update `Activity` and `Source` tabs on the Regulation Feature view.
- `Activity`: Add a descriptive note for features that have activity (so, not for CTCF and EMARs).
- `Source`: Add a link to the regulation subsite.
- http://wp-np2-25.ebi.ac.uk:6020/Homo_sapiens/Regulation/Summary?db=core;fdb=funcgen;r=17:63992802-64038237;rf=ENSR17_9XDSZ
- http://wp-np2-25.ebi.ac.uk:6020/Homo_sapiens/Regulation/Evidence?db=core;fdb=funcgen;r=17:63992802-64038237;rf=ENSR17_9XDSZ
[ENSREGULATION-2273](https://www.ebi.ac.uk/panda/jira/browse/ENSREGULATION-2273)
=> [r113] Update descriptions on regulation feature view

modules/EnsEMBL/Web/ConfigPacker.pm
Some genomes in strain-level gene-tree collections that are also in the default gene-tree collection lack a 'Strains' menu item. This is happening because the ConfigPacker query to fetch the `clusterset_id` of such genomes sometimes returns the `clusterset_id` of the strain collection, and sometimes returns the `clusterset_id` of the default collection.
This PR updates the strain metadata ConfigPacker query to retrieve both the `clusterset_id` and `strain_type`. Because only strain gene-tree collections have a `strain_type` tag, only strain `clusterset_id` values are fetched, so if a strain collection is available for a given genome, its genes will have a 'Strains' homology menu item.
This affects the gene view of genomes that are in both default and strain-level collections.
Here are …
=> Unify packing of strain gene-tree collection metadata

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm, modules/EnsEMBL/Web/Component/Gene/ComparaParalogs.pm, modules/EnsEMBL/Web/Component/Gene/HomologAlignment.pm
In homology and homology alignment views, the alignment type (whether coding or noncoding)  is determined based on whether the biotype of the gene contains the string `"RNA"`. This can result in protein-coding alignments being shown in cases where a noncoding biotype lacks this string (e.g. `"ribozyme"`).
This PR changes these views so that ncRNA homologies are identified by biotype group if …
=> Use biotype group to identify ncRNA homologies

modules/EnsEMBL/Web/Utils/HubParser.pm
With current code, when trackhub data gets parsed, the `link_template` field, which is used to generate a link to the feature might get transformed into a hash:
```
'link_template' => {
'http://srv00.recas.ba.infn.it/cgi/atlas/getpage_dev.py?rel' => 'hg38&acc=$$'
},
```
This transformation will prevent the generation of a link; so this PR adds the `url` field name to the list of names for which such transformation should never be done.
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6955
=> Fix to have feature url appear in zmenu for tracks from a trackhub

modules/EnsEMBL/Draw/GlyphSet/genetree.pm, modules/EnsEMBL/Web/Object/Gene.pm
In `ensembl_compara_113`, supertrees `RF00001` and `RF00413` have topology issues which are currently causing an error in the gene tree view of a combined total of 54,719 genes.
Work is in progress to fix the issue from e114 ([ENSCOMPARASW-7520](https://www.ebi.ac.uk/panda/jira/browse/ENSCOMPARASW-7520)), and a `SupertreeTopology` datacheck has been developed to catch supertree topology issues in future.
This PR  would put in place a `release/113`-only code fix which would mend these broken supertrees dynamically.
This affects the gene-tree view of genes in supertrees `RF00001` and `RF00413`.
- Example of RF00001 gene: [sandbox](http://wp-np2-25.ebi.ac.uk:5092/Scophthalmus_maximus/Gene/Compara_Tree?g=ENSSMAG00000028123) vs [RC site](https://rc.ensembl.org/Scophthalmus_maximus/Gene/Compara_ …
=> Repair broken supertrees dynamically

modules/EnsEMBL/Web/Configuration/Gene.pm
Some genomes that have strain metadata in their core database but are not in a strain-level gene-tree collection. Currently a Strains submenu is shown for these genomes, but this Strains submenu is unnecessary in such cases and could be removed.
This PR removes the Strains submenu in such cases.
This affects the gene view of genomes that have strain metadata but are not in a strain-level gene-tree collection.
Here are some examples of such genomes. In these cases, a Strains menu is not needed:
- Brassica rapa Z1: [sandbox](http://wp-np2-25.ebi.ac.uk:5098/Brassica_rapa_z1/Gene/Summary?g=A02g21140.2_BraZ1) vs [RC site](https://rc-plants.ensembl.org/Brassica_rapa_z1/Gene/Summary?g=A02g21140.2_BraZ1)
- Sheep - Texel: [sandbox](http://wp-np2-25.ebi.ac.uk:5092/Ovis_aries_texel/Gene/Summary?g=ENS …
=> Show Strain menu iff genome has strain gene trees

modules/EnsEMBL/Web/Component/Gene/TranscriptsImage.pm, modules/EnsEMBL/Web/ImageConfig/gene_summary.pm, modules/EnsEMBL/Web/ImageConfigExtension/Tracks.pm
The Manual Genome Annotation team have added a large amount of transcripts. In some cases 600 total transcripts. These transcripts will be seen on the comprehensive filter but not the basic.
Task: Update Gene and location pages to switch the default Gene and transcript filter from "Comprehensive" to "Basic gencode"
Location and Gene summary
Nothing that I am aware
No
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6951
=> Enable gencode basic

modules/EnsEMBL/Web/Document/HTML/FTPtable.pm
Add a line to the table in the help and docs page about the FTP site, describing the JSON format files.
https://www.ensembl.org/info/data/ftp/index.html
You can see the update in a sandbox: http://wp-np2-1f.ebi.ac.uk:8800/info/data/ftp/index.html
None.
None.
[ENSWEB-6958](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6958)
=> Add "JSON" to the FTP contents table

modules/EnsEMBL/Web/Component/Summary.pm
Add `GENCODE Primary` tag to the transcript table, before GENCODE Basic and update tooltip.
Gene page - transcript list table
NA
No
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6941
=> ENSWEB-6941 Add gencode primary tag to transcript table

modules/EnsEMBL/Draw/GlyphSet/fg_crispr.pm
Hardcode file path to fetch CRISPR SpCas9 in "Genome targeting" track data without patching Funcgen DB
r113-only
http://wp-np2-11.ebi.ac.uk:6010/Homo_sapiens/Location/View?r=17:64008595-64013672;db=core
=> Hardcode file path to fetch CRISPR SpCas9

modules/EnsEMBL/Web/ImageConfig/alignsliceviewbottom.pm
Some `CACTUS_DB` alignment views take a significant amount of time to load, leading to apparent timeout errors in some cases.
In some cases, much of this loading time is devoted to the loading of transcript tracks.
This PR would switch off transcript tracks by default in all but the `AlignSlice` reference genome shown at the top of the Viewbottom image.
This affects all Cactus image alignments.
- Wheat Lancer cultivar: [sandbox](http://wp-np2-25.ebi.ac.uk:5098/Triticum_aestivum_lancer/Location/Compara_Alignments/Image?r=2B:4300000-4325000;db=core;align=314995) vs [RC site](http://rc-metazoa.ensembl.org/Triticum_aestivum_lancer/Location/Compara_Alignments/Image?r=2B:4300000-4325000;db=core;align=314995)
- Drosophila melanogaster: [sandbox](http://wp-np2-25.ebi.ac.uk:5094/Drosophila_melanoga …
=> Hide non-reference gene tracks in Cactus image alignments

modules/EnsEMBL/Web/ImageConfig/gene_summary.pm, modules/EnsEMBL/Web/ImageConfigExtension/Tracks.pm
Request from Havana to change renderers to transcript with labels for gencode tracks.
http://wp-np2-1e.ebi.ac.uk:9000/Homo_sapiens/Location/View?r=17:63992802-64038237;debug=js
http://wp-np2-1e.ebi.ac.uk:9000/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000108622;r=17:63992802-64038237;t=ENST00000578892
=> Gencode renderer fix

modules/EnsEMBL/Web/Object/Slice.pm, modules/EnsEMBL/Web/ZMenu/FeatureEvidence.pm
Remove deprecated regulation peaks functions:
- Peaks are now being retrieved from a file for all assemblies, thus the `funcgen` DB `peak` table interaction is no longer required.
- http://wp-np2-25.ebi.ac.uk:6020/Homo_sapiens/Location/View?r=17:63992802-64038237 (Enable at least one Cell/Tissue peaks track).
- Z-menu associated with a Peak.
If no peak files are registered in `funcgen`, peaks will be missing.
- [ENSREGULATION-2281](https://www.ebi.ac.uk/panda/jira/browse/ENSREGULATION-2281)
=> [r114] Remove deprecated regulation Peaks functions

modules/EnsEMBL/Draw/GlyphSet/alignscalebar.pm
The legend of Cactus multiple image alignments currently includes the name of the last genome in the alignment having a particular feature.
This PR would change the legend of Cactus multiple image alignments to show a generic description of alignment features, similarly to EPO and Pecan views.
Examples:
- Rice Cactus: [sandbox](http://wp-np2-25.ebi.ac.uk:5098/Oryza_sativa/Location/Compara_Alignments/Im …
=> Tweak Cactus image alignment legend

modules/EnsEMBL/Web/Configuration/Location.pm
Remove invalid module import syntax that is generating server errors.
See [this slack thread](https://genomes-ebi.slack.com/archives/C0MUF0C3Y/p1729703830150509) for context.
http://wp-np2-1d.ebi.ac.uk:1640
=> Fix invalid module import

htdocs/info/data/ftp/rsync.html
The rsync command would be wrong for any directory with symlinks. Added -L to resolve them.
Considering no one noticed the original issue, I imagine none.
=> Update rsync command for symlinks

modules/EnsEMBL/Web/ZMenu/MotifFeature.pm
Binding matrix widget is now being replaced by the regulation subsite (regulation.ensembl.org).
Location view (motif features enabled)
http://wp-np2-25.ebi.ac.uk:6020/Homo_sapiens/Location/View?r=17:63992802-64038237
[ENSINT-2006](https://www.ebi.ac.uk/panda/jira/browse/ENSINT-2006)
=> [114] Update b. matrix link in motif feature z-menu

modules/EnsEMBL/Draw/GlyphSet/_gencode_basic.pm, modules/EnsEMBL/Draw/GlyphSet/_gencode_primary.pm, modules/EnsEMBL/Draw/GlyphSet_transcript.pm, modules/EnsEMBL/Draw/GlyphSet_transcript_new.pm, modules/EnsEMBL/Web/Component/Gene/TranscriptsImage.pm, modules/EnsEMBL/Web/Component/Transcript/TranscriptSummary.pm, modules/EnsEMBL/Web/ImageConfig/gene_summary.pm, modules/EnsEMBL/Web/ImageConfigExtension/Tracks.pm, modules/EnsEMBL/Web/Query/GlyphSet/Transcript.pm
This PR adds the Gencode Primary gene track. It will be enabled by default, while the Gencode basic primary track will be disabled. However, users should be able to switch between them using the track configuration modal. I used #1040 as reference when working on this PR.
There is another related PR that I created in `public-plugins` to enable Gencode Primary track in Region in Detail: https://github.com/Ensembl/public-plugins/pull/852
114
Location ([sandbox link](http://wp-np2-1e.ebi.ac.uk:8310/Homo_sapiens/Location/View?db=core;g=ENSG00000139618;r=13:32315086-32400268))
Gene ([sandbox link](http://wp-np2-1e.ebi.ac.uk:8310/Homo_sapiens/Gene/Summary?g=ENSG00000139618;r=13:32315086-32400268))
[ENSWEB-6947](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6947)
=> Add Gencode Primary track and disable Gencode Basic by default

modules/EnsEMBL/Web/Document/HTML/Compara/MLSS.pm
This PR would have the effect of always using the reference genome as the non-reference genome in self-alignment statistics views.
Currently the non-reference genome is set from a `non_reference_species` MLSS tag, which is present for the Human self-alignment in Ensembl Vertebrates, but not for the T. aestivum and T. dicoccoides self-alignments in Ensembl Plants.
The PR would have no effect on Human, …
=> Set non-ref species to ref in self-alignment

modules/EnsEMBL/Web/Component/Compara_Alignments.pm, modules/EnsEMBL/Web/Component/Location/Compara_AlignSliceBottom.pm, modules/EnsEMBL/Web/ConfigPacker.pm, modules/EnsEMBL/Web/Document/HTML/Compara.pm, modules/EnsEMBL/Web/ImageConfig/alignsliceviewbottom.pm, modules/EnsEMBL/Web/ImageConfigExtension/Tracks.pm
In conjunction with [eg-web-common PR 128](https://github.com/EnsemblGenomes/eg-web-common/pull/128) and [eg-web-plants PR 76](https://github.com/EnsemblGenomes/eg-web-plants/pull/76), this PR would facilitate display of `CACTUS_DB` alignments.
It would:
- alter default configuration of `CACTUS_DB` alignslice views to hide gene tracks when the size of the region being accessed exceeds a 'transcript' …
=> Facilitate CACTUS_DB alignment views in all divisions

modules/EnsEMBL/Web/Component/Gene/GeneSummary.pm, modules/EnsEMBL/Web/Component/Transcript/TranscriptSummary.pm
Fix for https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6989
Not all MANE Select transcripts are protein-coding.
- gene with non-coding MANE select transcript: http://wp-np2-33.ebi.ac.uk:8410/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000277027;r=9:35657750-35658019;t=ENST00000363046
- non-coding MANE select transcript: http://wp-np2-33.ebi.ac.uk:8410/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000277027;r=9:35657750-35658019;t=ENST00000363046
- coding transcript: http://wp-np2-33.ebi.ac.uk:8410/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000104635;r=8:22367278-22434129;t=ENST00000381237
=> Add some guards for non-protein-coding MANE transcripts

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm, modules/EnsEMBL/Web/Component/Gene/HomologAlignment.pm, modules/EnsEMBL/Web/SpeciesDefs.pm
In Pan Compara `EnsEMBL::Web::Component::Gene::ComparaOrthologs` and `EnsEMBL::Web::Component::Gene::HomologAlignment` views, URLs to features of genomes not in the current host division (e.g. Human in `plants.ensembl.org`) are prefixed with a Pan Compara-specific base URL.
This addition of a Pan-specific base URL is not currently implemented in `EnsEMBL::Web::ZMenu::Gene::ComparaTree`, and as a result, in Pan Compara gene trees, the ZMenu of a gene does not load if that gene is not in the host division.
This pull request would remove the addition of a base URL to Pan Compara URLs in the `ComparaOrthologs` and `HomologAlignment` modules, and would instead add a Pan Compara base URL as a second-to-last resort in the `SpeciesDefs::species_path` method.
This would extend the inclusion of a …
=> Prepend Pan Compara base URL to species path

modules/EnsEMBL/Web/Component/Gene/Compara_Portal.pm
This PR would ensure that the strain-level Compara portal would be displayed when a user clicks on the strains/breeds/cultivars menu item in a gene view.
This would affect the appearance and behaviour of a Compara portal accessed via the strains/breeds/cultivars menu item of a gene view.
Here is a screenshot illustrating the effect on the cultivar Compara portal of the Rice reference genome:
For comparison, here is the corresponding view on the Ensembl Plants live site: https://plants.ensembl.org/Oryza_sativa/Gene/Strain_Compara?g=Os08g0140500
None expected.
None detected.
N/A
=> Show strain Compara portal for all genomes in a strain collection

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm
In cases where a GOC score threshold is undefined, a GOC score of zero may be adorned with the green highlighting intended for high GOC scores.
This PR would remove such highlighting of zero-value GOC scores.
This change would affect the Compara orthologues view.
An up-to-date example is given in the comments of the related ticket.
None expected.
None detected.
- ENSWEB-6354
=> Remove highlighting of GOC score zero

modules/EnsEMBL/Web/ImageConfigExtension/Constants.pm, modules/EnsEMBL/Web/ImageConfigExtension/Tracks.pm, modules/EnsEMBL/Web/Query/GlyphSet/Transcript.pm
This addresses the problem of missing transcripts in gencode primary and gencode basic tracks raised in https://embl.atlassian.net/browse/ENSWEB-6993
As it turned out, the list of 'logic names' that selects transcripts for gencode tracks was missing three members: `ensembl_havana_tagene_gene`, `havana_tagene`, and `proj_havana_tagene`.
While fixing the problem, I've also moved the duplicated lists of strings into a separate file. Note that even now, the list of logic names for gencode and mane tracks is mostly identical — the following members between them are the same:
```
'proj_ensembl',
'proj_ncrna',
'proj_havana_ig_gene',
'havana_ig_gene',
'ensembl_havana_ig_gene',
'proj_ensembl_havana_lincrna',
'proj_havana',
'ensembl',
'mt_genbank_import',
'ensembl_havana_lincrna', …
```
=> Add logic names for gencode, and dry up the code a little

conf/httpd.conf
Our logs currently print the ip of the traffic manager, which isn't useful at all. This PR updates apache log format such that 
**Before:**
No proper information about where requests originated from:
```
[112714/- - -/-=-] 193.62.192.71/- -/- -/- [23/Jan/2024:19:22:29 +0000] "GET /__howsitgoing HTTP/1.0" 200 66 "-" "HTTP-Monitor/1.1" "-" -/-
[112713/- - -/-=-] 193.62.193.70/- -/- -/- [23/Jan/2024:19:22:28 +0000] "GET /index.html HTTP/1.1" 200 197174 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-" -/-
[112713/- - -/-=-] 193.62.193.70/- -/- -/- [23/Jan/2024:19:22:30 +0000] "GET /minified/e070e2b9af58bbaac1db99d52f3b9fbd.css HTTP/1.1" 200 41495 "https://test-rapid.ensembl.org/index.html" "Mozilla/5.0 (Macintosh; …
```
=> Update Apache access logs format: print request IP

modules/EnsEMBL/Web/Component/Location/Compara_AlignSliceBottom.pm
On `line 390 of ensembl-webcode/modules/EnsEMBL/Web/Object.pm` ...
https://github.com/Ensembl/ensembl-webcode/blob/370648c0e9e105faaefd3737e0c6928aed93bfdd/modules/EnsEMBL/Web/Object.pm#L390
...in method `EnsEMBL::Web::Object::get_slices`, the `'image'` parameter is used to control whether `underlying_slices` of a Compara `AlignSlice::Slice` are loaded for a formatted slice.
The loaded `underlying_slices` value is used in various places in text alignment views. However, in genomic alignment image (alignslice) views, it appears to be used only to control visibility of ancestral sequences, in line 417 of `ensembl-webcode/modules/EnsEMBL/Web/Object.pm`: https://github.com/Ensembl/ensembl-webcode/blob/370648c0e9e105faaefd3737e0c6928aed93bfdd/modules/EnsEMBL/Web/Object.pm#L417
This PR would …
=> Load underlying slices iff needed for alignslice view

modules/EnsEMBL/Web/Command/DataExport/Output.pm, modules/EnsEMBL/Web/Constants.pm, modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm
This PR would:
- add a `GENE_TREE_CONSTANTS` function in the `EnsEMBL::Web::Constants` module;
- make use of the `GENE_TREE_CONSTANTS` function to pass appropriate `cdb`, `action`, `component` and  `strain` parameters in **"Tree or Alignment"** or **"Sequences"** export URLs in gene-tree node ZMenus;
- ensure that `node` and `strain` parameters are passed when the **Back** button is used in a gene-tree download modal window.
The effects of this would be that:
- clicking the **"Tree or Alignment"** or **"Sequences"** subtree export options in a strain, Pan or Metazoa gene-tree node Zmenu would lead to the tree/alignment or sequences (respectively) of the subtree rooted at the given node;
- when previewing data for a strain/subtree, if a user clicks the **Back** button and clicks the …
=> Tweak handling of strain, Pan and subtree export

modules/EnsEMBL/Web/Component/Variation/Compara_Alignments.pm
This PR makes two adjustments to the variant phylogenetic context view:
- the return value of `check_for_align_problems` is handled more consistently with other alignment views;
- handling of species production names and URLs is adjusted to ensure the correct value is passed to methods such as `check_for_align_problems` and `species_label`.
This PR affects the variant phylogenetic context view in the following ways:
- **A**: the stray number `1` is removed;
- **B**: neighbouring variants are now shown;
- **C**: the list of genomes lacking a variation database is fixed.
Example view before changes:
Example view after changes:
None expected, because changes are made only to `EnsEMBL::Web::Component::Variation::Compara_Alignments`. 
None detected.
N/A
=> Tweak phylogenetic context view

htdocs/info/about/legal/policy/ensembl-1000g-browsing.html, htdocs/info/about/legal/policy/ensembl-1000g-contact.html, htdocs/info/about/legal/policy/ensembl-contact-signup.html, htdocs/info/about/legal/policy/ensembl-embassy-accounts.html, htdocs/info/about/legal/policy/ensembl-embassy-browsing.html, htdocs/info/about/legal/policy/ensembl-embassy-mart.html, htdocs/info/about/legal/policy/ensembl-mailing-lists.html, htdocs/info/about/legal/policy/ensembl-mirrors-accounts.html, htdocs/info/about/legal/policy/ensembl-mirrors-browsing.html, htdocs/info/about/legal/policy/ensembl-mirrors-mart.html, htdocs/info/about/legal/policy/ensembl-website-accounts.html, htdocs/info/about/legal/policy/ensembl-website-browsing.html, htdocs/info/about/legal/policy/ensembl-website-contact.html, htdocs/info/about/legal/policy/ensembl-website-mart.html, htdocs/info/about/legal/policy/ensemblgenomes-apollo.html, htdocs/info/about/legal/privacy.html
The EBI service that hosts Ensembl's privacy policy pages has been deactivated.  This PR creates static copies of the policy pages and updates the privacy policy main page to link to them.
The policy pages where generated based on offline copies of the EBI pages saved here https://ensembl.github.io/privacy_notices/
The only change is to  [Privacy policy](https://www.ensembl.org/info/about/legal/privacy.html)
The changes can be viewed here http://wp-np2-33.ebi.ac.uk:10000/info/about/legal/privacy.html
I may not have created the policy html pages in the correct way
=> Switch to local policy pages

modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm
In conjunction with [eg-web-common PR 139](https://github.com/EnsemblGenomes/eg-web-common/pull/139), this PR would remove the code to fetch the unused test tree returned by `EnsEMBL::Web::Component::Gene::ComparaTree::get_details`.
Removal of the unused test tree should reduce the work done to present the gene-tree view.
None expected.
None detected.
N/A
=> Remove unused test tree

conf/ini-files/DEFAULTS.ini
Adds constant `DOI` which is doi.org - by concatenating a doi after the URL like doi.org/<my_doi>, this can resolve any doi. 
Linked to [public-plugins PR #877 ](https://github.com/Ensembl/public-plugins/pull/877), linked to [VEP_plugins PR #794](https://github.com/Ensembl/VEP_plugins/pull/794) and [ticket 6760](https://embl.atlassian.net/browse/ENSVAR-6760).
=> Web MaveDB plug-in to display 1 additional column: `MaveDB_doi` as hyperlink

modules/EnsEMBL/Web/Component/Variation/Phenotype.pm, modules/EnsEMBL/Web/Object/Variation.pm
ClinVar supports a new type of classification (somatic) that we want to display in the current website for release 115.
This change adds a new table to the variant phenotype page to display the new clinvar somatic classification.
To test the new display we have to point the ensembl-variation repo to release/115 - the API changes are already merged.
- EnsEMBL::Web::Component::Variation::Phenotype
- EnsEMBL::Web::Object::Variation
Testing the affected page on the sandbox: http://wp-np2-33.ebi.ac.uk:7040/Homo_sapiens/Variation/Phenotype?db=core;r=13:48459208-48460208;v=rs137853294;vdb=variation;vf=813845583
This change should only affect the variant phenotype page.
No merge conflicts
Update ClinVar (main ticket): [ENSVAR-5941](https://embl.atlassian.net/browse/ENSVAR-5941)
Update the web …
=> Add table to display somatic classifications from ClinVar (release 115)

modules/EnsEMBL/Web/Component/DataExport/SpeciesTree.pm
This PR would remove unused fields from the gene gain/loss tree export form.
The existing checkbox fields — "cDNA rather than protein sequence", "Aligned sequences with gaps" and "Omit sequences" — are relevant to gene-tree export, but not to gene gain/loss (species) tree export.
This would affect the gene gain/loss tree config modal window, but because the removed options are unused, it would not affect the gene gain/loss tree view itself.
Example before:
Example after:
None expected.
None detected.
N/A
=> Remove unused fields from gene gain/loss tree export form

modules/EnsEMBL/Web/Component/Gene/ComparaOrthologs.pm, modules/EnsEMBL/Web/Component/Gene/ComparaParalogs.pm, modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm, modules/EnsEMBL/Web/Component/Gene/Compara_Portal.pm, modules/EnsEMBL/Web/Component/Gene/HomologAlignment.pm, modules/EnsEMBL/Web/ConfigPacker.pm, modules/EnsEMBL/Web/Configuration/Gene.pm, modules/EnsEMBL/Web/Form/ViewConfigForm.pm, modules/EnsEMBL/Web/Object/Gene.pm, modules/EnsEMBL/Web/Query/Availability/Gene.pm, modules/EnsEMBL/Web/Utils/Compara.pm, modules/EnsEMBL/Web/ViewConfig/Gene/ComparaOrthologs.pm, modules/EnsEMBL/Web/ViewConfig/Gene/ComparaTree.pm, modules/EnsEMBL/Web/ZMenu/ComparaOrthologs.pm
Strain-group metadata to represent strain-reference relationships have become increasingly common in recent years, with 75 genomes in about 15 such groups in Ensembl Vertebrates 115.
The same period has seen strain gene-tree collections being used more broadly, to a point where Ensembl Plants release 115 cultivar gene-tree collections are expected to have almost as many genomes (123) as are in the default gene-tree collection (126).
Lines between strain and non-strain comparative data are becoming increasingly blurred. For some time, a proportion of genomes in strain collections have not themselves been strains, and as of release 115, there is at least one strain-tagged genome in a default gene-tree collection.
Finally, gene-tree configuration has become more complex in release 115 with …
=> Take the strain, disentangle clustersets

modules/EnsEMBL/Web/Object/Gene.pm
This pull request would:
- add internal method `EnsEMBL::Web::Object::Gene::_get_basal_gene_tree` to fetch the basal gene tree, which is a gene tree or supertree linked to the relevant clusterset;
- use this new method to fetch the basal supertree in `EnsEMBL::Web::Object::Gene::get_GeneTree`;
- use the method in `EnsEMBL::Web::Object::Gene::get_homologies` to ensure that exported homology XML files …
=> Get basal tree when accessing supertree and supertree homologies

modules/EnsEMBL/Draw/GlyphSet/genetree.pm, modules/EnsEMBL/Web/Command/DataExport/Output.pm, modules/EnsEMBL/Web/Component/DataExport/GeneTree.pm, modules/EnsEMBL/Web/Component/Gene/ComparaTree.pm, modules/EnsEMBL/Web/Object/Gene.pm, modules/EnsEMBL/Web/ViewConfig/Gene/ComparaTree.pm
In conjunction with [eg-web-metazoa PR 48](https://github.com/EnsemblGenomes/eg-web-metazoa/pull/48), this pull request would facilitate handling of gene tree configuration.
This PR would:
- add method `EnsEMBL::Web::Object::Gene::_resolve_clusterset_ids`, which resolves the appropriate consensus and alternative `clusterset_id` values;
- update `EnsEMBL::Web::Object::Gene::get_GeneTree` to prioritise an explicit `clusterset_id` parameter over a consensus clusterset (e.g. `"pig_breeds"`) where that `clusterset_id` represents an alternative clusterset appropriate to the given gene-tree view, facilitating display of contributing clustersets of a strain gene tree (e.g. `"pig_breeds_raxml_parsimony"`);
- change `EnsEMBL::Web::Object::Gene::get_GeneTree` to use the consensus clusterset if a …
=> Facilitate config of contributing gene trees

modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm
For non-default Metazoa gene trees having a stable ID, there is an issue 
with inconsistent display of the gene-tree stable ID in the root node 
ZMenu on Ensembl Metazoa.
For example, if a given gene is in both the Metazoa default and Protostomes collections, the Zmenu of the root of its Protostomes gene tree lacks a stable ID. If that gene is absent from the Metazoa default collection and its Protostomes gene tree has a stable ID, its Protostomes gene-tree root Zmenu displays that gene-tree stable ID.
This PR addresses the issue by comparing `node_id` values instead of nodes in the `ComparaTreeNode` root status check.
This change affects the gene-tree view of Metazoa genomes that are in both a default and non-default gene-tree collection.
For example, if you access the gene tree view of …
=> Use node_id in gene-tree node ZMenu root status check

modules/EnsEMBL/Web/Constants.pm, modules/EnsEMBL/Web/ZMenu/ComparaTreeNode.pm
This PR would set the `pan_compara` function as appropriate in the `ComparaTreeNode` ZMenu entry linking to a subtree of a supertree.
This change would ensure that the resulting `Multi` gene-tree view would be configured to show a Pan Compara tree, so that for example, its Wasabi links would set the Ensembl REST `compara` parameter to `pan_homology`.
To see the effect of this change:
1. Go to a gene tree that is part of a supertree (e.g. Rice gene Os05g0421750 on the [sandbox](http://wp-np2-35.ebi.ac.uk:5098/Oryza_sativa/Gene/PanComparaTree?g=Os05g0421750) and [live site](https://plants.ensembl.org/Oryza_sativa/Gene/PanComparaTree?g=Os05g0421750)).
2. Click on the sidebar menu button to "Configure this page", and in the "Display options" section of the view config modal window, tick the …
=> Set pan_compara function in Pan gene tree node ZMenu

modules/EnsEMBL/Web/Document/HTML/GenomeList.pm
This PR would fetch the `ALL_STRAINS` list from the config of Pig reference genome `Sus_scrofa`, and use that list to set the number of Pig breeds in the genome list on the Ensembl Vertebrates homepage.
The code in this PR should automatically update the Pig breed count in the Ensembl Vertebrates homepage.
The Compara Vertebrates sandbox has been updated for e116, and currently counts 27 Pig breeds/isolates: http://wp-np2-35.ebi.ac.uk:5092/index.html
None expected.
None detected.
- N/A
=> Set Pig breed count from ALL_STRAINS config in genome list

modules/EnsEMBL/Web/Component/Info/HomePage.pm, modules/EnsEMBL/Web/Utils/Compara.pm
Example gene tree links in Ensembl species homepages are generated using the [Compara_Tree action](https://github.com/Ensembl/ensembl-webcode/blob/a88f841d346aab3b8e59319ab09b40eb36084cc3/modules/EnsEMBL/Web/Component/Info/HomePage.pm#L257) or [PanComparaTree action](https://github.com/EnsemblGenomes/eg-web-common/blob/8c6c5544afc00d8964779ad307f142f9ff279ff8/modules/EnsEMBL/Web/Component/Info/HomePage.pm#L391).
Genomes that are exclusively in a strain/breed gene-tree collection have broken example gene-tree links, because their gene-tree action is `Strain_Compara_Tree`.
This PR would mend these broken links by adding utility function `EnsEMBL::Web::Utils::Compara::get_sample_gene_tree_action` and calling it in the `EnsEMBL::Web::Component::Info::HomePage` to set the example gene-tree …
=> Set example gene-tree action dynamically

modules/EnsEMBL/Draw/GlyphSet/genetree.pm, modules/EnsEMBL/Web/ConfigPacker.pm, modules/EnsEMBL/Web/SpeciesDefs.pm, modules/EnsEMBL/Web/ZMenu/Gene/ComparaTree_pan_compara.pm
In Ensembl NV sites, the ZMenu of a Vertebrate gene does not load, but instead shows the _e!_ spinner with the text, "Loading component".
This is because the cross-site requests by which gene ZMenus may be populated in Ensembl NV gene-tree views ([here](https://github.com/EnsemblGenomes/eg-web-common/blob/8c6c5544afc00d8964779ad307f142f9ff279ff8/modules/EnsEMBL/Web/ZMenu.pm#L32-L39)) are JSONP, while those of the Ensembl Vertebrates site ([here](https://github.com/Ensembl/ensembl-webcode/blob/fd68602aad5c30693fbf5a7e6a45ea205784cf6b/modules/EnsEMBL/Web/ZMenu.pm#L240)) are JSON.
This PR would enable population of Vertebrate gene ZMenus from the Pan Compara database (if available) in Ensembl NV sites.
The resulting ZMenus would provide the subset of the regular gene ZMenu functionality that …
=> Populate Vertebrate gene ZMenus on NV sites from Pan Compara
